import {useEffect,useRef,useState} from 'react';
import {useProduction} from '../../features/production/ProductionProvider';
import {productionStageLabel,type ProductionRun,type ScheduleTarget} from '../../features/production/model';
import {useContentWorkflow} from '../../features/content/ContentWorkflowProvider';
import {useChat} from '../../features/chat/ChatProvider';
import {useAgents} from '../../features/agents/AgentsProvider';
import {useLanguage} from '../../app/LanguageProvider';
import {FlowDialog} from '../common/FlowDialog';
import {SelectMenu} from '../common/SelectMenu';
import {ContentAssetLibrary} from '../content/ContentAssetLibrary';
import {ContentPublications} from '../content/ContentPublications';
import {PublicationEditor} from '../content/ContentPublications';
import {PublicationNetworkSettings} from '../content/PublicationNetworkSettings';
import {storageProfile} from '../../data/IndexedDbStateStore';
import {updatePersistentValue} from '../../data/localPersistence';
import type {ProductionFlows} from '../../features/flows/flowModel';
import {localTimeToInstant,zonedDateTime} from '../../../publication-time.mjs';
import type {Platform,PublicationDelivery} from '../../features/content/model';
import {decodeChatDelivery} from '../../../chat-delivery-protocol.mjs';
import {useStudioDraftField,clearStudioDraft} from '../../features/content/studioDrafts';
import {startDraftScope,runDraftScope,scheduleDraftScope,validSelection,validNetworks,videoDraftValue,restoreVideo,targetsDraftValue,restoreTargets,validTimeZone,validLocalDate,scheduleFingerprint} from '../../features/production/productionDrafts';
import {ProductionProgress} from './ProductionProgress';
import {EditReview} from '../content/EditReview';
import {ProductionBudget} from './ProductionBudget';
import {ProductionPreflight} from './ProductionPreflight';
import {RecordingPackage} from './RecordingPackage';
import {CoversReview} from './CoversReview';
import {CaptionReview} from './CaptionReview';
import {MotionIntensityField,motionIntensity} from './MotionIntensity';
import type {PreflightReport} from '../../../production-preflight.mjs';
import './production.css';

function CoverPreview({run,delivery}:{run:ProductionRun;delivery:PublicationDelivery}){
 // Same protected route as the cover gallery: only covers of this run, served when the bytes still match their sha256.
 const [error,setError]=useState(false);
 useEffect(()=>setError(false),[delivery.cover?.assetId,delivery.cover?.versionId]);
 if(!delivery.cover)return <figure className="production-cover"><span>{'Sem capa nesta entrega.'}</span></figure>;
 const src=`/api/content/productions/${encodeURIComponent(run.id)}/cover?profile=${encodeURIComponent(storageProfile())}&assetId=${encodeURIComponent(delivery.cover.assetId)}&versionId=${encodeURIComponent(delivery.cover.versionId)}`;
 return <figure className="production-cover">{error?<span role="alert">{'Não foi possível carregar a capa; ela pode ter mudado no disco.'}</span>:<img src={src} alt={`Capa ${delivery.platform}`} onError={()=>setError(true)}/>}</figure>;
}
function focusField(label:string){document.querySelector<HTMLElement>(`[aria-label="${label}"]`)?.focus();}
function Prerequisites({items,onNavigate}:{items:Array<{text:string;focus?:string;href?:string}>;onNavigate?:()=>void}){
 return items.length?<ul className="editorial-hint" aria-live="polite">{items.map(item=><li key={item.text}>{item.focus?<button className="text-link" onClick={()=>focusField(item.focus!)}>{item.text}</button>:item.href?<a href={item.href} onClick={onNavigate}>{item.text}</a>:item.text}</li>)}</ul>:null;
}
function ScheduleForm({run,initialText,act,busy}:{run:ProductionRun;initialText?:string;busy:boolean;act:(action:string,data?:Record<string,unknown>)=>Promise<ProductionRun|undefined>}){
 const {publicationAccounts}=useContentWorkflow(),{locale}=useLanguage(),pt=locale==='pt-BR';
 const scope=scheduleDraftScope(run);
 const [initialDate]=useState(()=>!initialText&&run.schedule?zonedDateTime(run.schedule.plannedAt,run.schedule.timeZone):'');
 const [text,setText]=useStudioDraftField(scope,'text',initialText??''),[savedZone,setZone]=useStudioDraftField(scope,'zone',run.schedule?.timeZone??run.timeZone),[savedDate,setDate]=useStudioDraftField(scope,'date',initialDate),[savedTargets,setTargets]=useStudioDraftField(scope,'targets',targetsDraftValue(run.schedule?.targets??[]));
 const zone=validTimeZone(savedZone,validTimeZone(run.timeZone)),date=validLocalDate(savedDate);
 const [error,setError]=useState(''),[loading,setLoading]=useState(''),[reviewed,setReviewed]=useState<{fingerprint:string;hash:string}|null>(null),[accounts,setAccounts]=useState<Record<string,Array<{id:string;name:string}>>>({});
 const [confirmations,setConfirmations]=useState<Record<string,{fingerprint:string;preview:boolean;consent:boolean}>>({});
 const targets=restoreTargets(savedTargets,run).map(target=>{const confirmation=confirmations[target.platform],fingerprint=targetsDraftValue([target]);const t=target.networkSettings?.tiktokSettings;if(!t)return target;return {...target,networkSettings:{...target.networkSettings,tiktokSettings:{...t,content_preview_confirmed:confirmation?.fingerprint===fingerprint&&confirmation.preview===true,express_consent_given:confirmation?.fingerprint===fingerprint&&confirmation.consent===true}}};});
 const fingerprint=scheduleFingerprint(scope,text,date,zone,targets),accountKey=(target:ScheduleTarget)=>`${target.provider}:${target.platform}`;
 const accountsValid=targets.length>0&&targets.every(t=>accounts[accountKey(t)]?.some(a=>a.id===t.accountId));
 const timeValid=!!text.trim()||!!date,consentsValid=targets.every(t=>t.platform!=='TikTok'||!!t.networkSettings?.tiktokSettings?.content_preview_confirmed&&!!t.networkSettings.tiktokSettings.express_consent_given);
 const patch=(platform:string,change:Partial<ScheduleTarget>)=>{const before=targets.find(t=>t.platform===platform);if(!before)return;const next={...before,...change},unchanged=targetsDraftValue([before])===targetsDraftValue([next]);setTargets(targetsDraftValue(targets.map(t=>t.platform===platform?next:t)));setReviewed(null);setConfirmations(current=>({...current,[platform]:{fingerprint:targetsDraftValue([next]),preview:unchanged&&next.networkSettings?.tiktokSettings?.content_preview_confirmed===true,consent:unchanged&&next.networkSettings?.tiktokSettings?.express_consent_given===true}}));};
 const load=async(target:ScheduleTarget)=>{setLoading(target.platform);setError('');setReviewed(null);try{const result=await publicationAccounts(target.provider,target.platform);setAccounts(current=>({...current,[accountKey(target)]:result.accounts}));if(target.accountId&&!result.accounts.some(a=>a.id===target.accountId))patch(target.platform,{accountId:''});}catch(error){setError((error as Error).message)}finally{setLoading('')}};
 const missing=[...(!targets.length?[{text:pt?'Revise e aprove um pacote com plataformas antes de agendar.':'Review and approve a package with platforms before scheduling.'}]:[]),...(!timeValid?[{text:pt?'Informe data e horário acima.':'Enter a date and time above.',focus:'Production exact date'}]:[]),...targets.filter(t=>!accounts[accountKey(t)]?.some(a=>a.id===t.accountId)).map(t=>({text:pt?`${t.platform}: consulte as contas e escolha uma conta atual.`:`${t.platform}: check accounts and choose a current account.`,focus:`Conta ${t.platform}`})),...(!consentsValid?[{text:pt?'Revise a mídia e marque os consentimentos TikTok desta versão acima.':'Review the media and check the TikTok consents for this version above.'}]:[])];
 return <div className="production-section"><h3>{pt?'Quando e onde agendar?':'When and where to schedule?'}</h3><label>{pt?'Data e horário pela conversa':'Date and time in words'}<input aria-label="Horário da produção" value={text} disabled={busy} onChange={event=>{setReviewed(null);setText(event.target.value)}} placeholder={pt?'Amanhã às 18h':'Tomorrow at 18:00'}/></label><label>{pt?'Ou escolha uma data exata':'Or choose an exact date'}<input aria-label="Production exact date" type="datetime-local" value={date} disabled={busy} onChange={event=>{setReviewed(null);setDate(event.target.value)}}/></label><label>{pt?'Fuso':'Time zone'}<SelectMenu value={zone} disabled={busy} onChange={value=>{setReviewed(null);setZone(value)}} ariaLabel="Fuso da produção" options={[...new Set([zone,'America/Sao_Paulo','America/Manaus','America/Recife','Europe/Lisbon','UTC'])].map(value=>({value,label:value}))}/></label>
  {targets.map(target=><section className="production-target" key={target.platform}><strong>{target.platform}</strong><SelectMenu ariaLabel={`Provedor ${target.platform}`} value={target.provider} disabled={busy||!!loading} onChange={value=>{patch(target.platform,{provider:value as ScheduleTarget['provider'],accountId:''});setAccounts(current=>({...current,[accountKey(target)]:[]}))}} options={[{value:'zernio',label:'Zernio'},{value:'publora',label:'Publora',disabled:target.platform!=='LinkedIn'||!!run.reviewDeliveries?.find(d=>d.platform===target.platform)?.cover,description:pt?'Este conector não envia capa de vídeo LinkedIn.':'This connector does not send LinkedIn video covers.'}]}/><button className="soft-button" disabled={busy||!!loading} onClick={()=>void load(target)}>{loading===target.platform?(pt?'Consultando…':'Checking…'):(pt?'Consultar contas':'Check accounts')}</button><SelectMenu ariaLabel={`Conta ${target.platform}`} value={target.accountId} disabled={busy||!!loading} onChange={accountId=>patch(target.platform,{accountId})} options={[{value:'',label:pt?'Escolher conta':'Choose account'},...(target.accountId&&!accounts[accountKey(target)]?[{value:target.accountId,label:target.accountId}]:[]),...(accounts[accountKey(target)]??[]).map(a=>({value:a.id,label:a.name}))]}/><PublicationNetworkSettings platform={target.platform as Platform} settings={target.networkSettings??{}} onChange={networkSettings=>patch(target.platform,{networkSettings})} disabled={busy||!!loading} mediaType="video" accountId={target.accountId}/></section>)}
  {error&&<p className="delivery-error" role="alert">{error}</p>}<Prerequisites items={missing}/><button className="primary-button" disabled={busy||!!loading||!accountsValid||!timeValid||!consentsValid} onClick={async()=>{setError('');setReviewed(null);try{const result=await act('prepare-schedule',{timeZone:zone,targets,...(date?{plannedAt:localTimeToInstant(date,zone)}:{text})});if(result?.scheduleHash)setReviewed({fingerprint,hash:result.scheduleHash})}catch(error){setError((error as Error).message)}}}>{pt?'Conferir agendamento':'Review schedule'}</button>
  {run.schedule&&<div className="production-confirmation"><strong>{pt?'Confira antes de autorizar':'Review before authorizing'}</strong><p>{zonedDateTime(run.schedule.plannedAt,run.schedule.timeZone).replace('T',' ')} · {run.schedule.timeZone}</p>{run.schedule.targets.map(t=><p key={t.platform}>{t.platform} · {t.provider} · {t.accountId}</p>)}<p>{pt?'Envia as versões aprovadas do vídeo, capas e legendas. O provedor publica no horário confirmado.':'Sends the approved video, covers and captions. The provider publishes at the confirmed time.'}</p>{run.schedule.targets.some(t=>t.platform==='TikTok')&&<p>{pt?'Dependendo da conexão TikTok, o Zernio incorpora a capa como um frame inicial do vídeo.':'Depending on the TikTok connection, Zernio incorporates the cover as an initial video frame.'}</p>}{reviewed?.fingerprint!==fingerprint&&<p className="editorial-hint">{pt?'Clique em Conferir agendamento para revisar estes dados antes de autorizar.':'Click Review schedule to review these details before authorizing.'}</p>}<button className="primary-button" disabled={busy||!accountsValid||!consentsValid||reviewed?.fingerprint!==fingerprint||!run.scheduleHash||reviewed?.hash!==run.scheduleHash} onClick={async()=>{const result=await act('schedule',{authorize:true,expectedHash:run.scheduleHash});if(result){clearStudioDraft(scope);setReviewed(null);setConfirmations({})}}}>{pt?'Autorizar agendamentos':'Authorize schedules'}</button></div>}
 </div>;
}

const sameVideo=(a?:{assetId:string;versionId:string;sha256:string},b?:{assetId:string;versionId:string;sha256:string})=>!!a&&!!b&&a.assetId===b.assetId&&a.versionId===b.versionId&&a.sha256===b.sha256;
const captionJobRunning=(run:ProductionRun)=>run.captions?.transcription?.status==='running'||run.captions?.render?.status==='running';
/** B05: going back to the video withdraws covers, package and schedule approvals; the post texts are kept (no new AI call). */
function ReopenVideo({run,pt,busy,act}:{run:ProductionRun;pt:boolean;busy:boolean;act:(action:string,data?:Record<string,unknown>)=>Promise<ProductionRun|undefined>}){
 const [confirm,setConfirm]=useState(false),captioned=!!run.captions?.output&&sameVideo(run.captions.output,run.approvedVideo);
 return <details className="production-section"><summary>{captioned?(pt?'Mudar as legendas gravadas no vídeo':'Change the captions burned into the video'):(pt?'Adicionar legendas de fala ao vídeo':'Add speech captions to the video')}</summary>
  <p className="editorial-hint">{pt?'Reabre o vídeo aprovado para revisão. A aprovação do vídeo, das capas, do pacote e do horário é retirada e precisa ser feita de novo; as legendas do post são mantidas. Nada externo é alterado.':'Reopens the approved video for review. Video, cover, package and schedule approvals are withdrawn and must be given again; post captions are kept. Nothing external changes.'}</p>
  <label className="production-check"><input type="checkbox" checked={confirm} disabled={busy} onChange={event=>setConfirm(event.target.checked)}/>{pt?'Entendo que as aprovações seguintes serão refeitas.':'I understand the following approvals will be redone.'}</label>
  <button className="soft-button" disabled={busy||!confirm||run.covers?.render?.status==='running'} onClick={()=>void act('reopen-video',{authorize:true}).then(()=>setConfirm(false))}>{pt?'Reabrir vídeo':'Reopen video'}</button></details>;
}
const providerName=(id?:string)=>id==='claude'?'Claude Code':id==='codex'?'Codex':id??'—';
const shortHash=(hash?:string)=>hash?hash.slice(0,8):'';
/** Script gate: pick hook/CTA/path, edit, save a version, then approve that exact version (hash). */
function ScriptReview({run,act,busy,pt,editingApproved=false}:{run:ProductionRun;busy:boolean;pt:boolean;editingApproved?:boolean;act:(action:string,data?:Record<string,unknown>)=>Promise<ProductionRun|undefined>}){
 const latest=run.scriptVersions?.at(-1),options=run.scriptOptions;
 const [hook,setHook]=useState(latest?.hook??''),[cta,setCta]=useState(latest?.cta??''),[pathIndex,setPathIndex]=useState(()=>Math.max(0,options?.paths.findIndex(p=>p.title===latest?.path.title&&p.outline===latest?.path.outline)??0)),[text,setText]=useState(latest?.text??''),[confirm,setConfirm]=useState(false),[notes,setNotes]=useState('');
 if(!latest)return <div className="production-section"><p>{pt?'Aguardando a primeira versão do roteiro.':'Waiting for the first script version.'}</p></div>;
 const path=options?.paths[pathIndex]??latest.path,dirty=hook.trim()!==latest.hook||cta.trim()!==latest.cta||text.trim()!==latest.text||path.title!==latest.path.title||path.outline!==latest.path.outline;
 const approved=run.scriptApproval?.hash===latest.hash&&!run.scriptApproval.reviewRequired,cardHasVersion=run.notion?.scriptHash===latest.hash;
 const pick=(values:string[]|undefined,current:string)=>[...new Set([current,...(values??[])])].filter(Boolean).map(value=>({value,label:value.length>90?`${value.slice(0,90)}…`:value}));
 return <div className="production-section production-script"><h3>{pt?`Roteiro v${latest.version}`:`Script v${latest.version}`} <small>{latest.source==='user'?(pt?'editado por você':'edited by you'):latest.source==='legacy'?(pt?'produção anterior':'earlier production'):(pt?'proposto pelo agente':'proposed by the agent')} · #{shortHash(latest.hash)}</small></h3>
  {editingApproved&&<p className="editorial-hint">{pt?`Salvar uma alteração invalida a aprovação atual: a gravação volta a ficar bloqueada até você aprovar a nova versão${run.scriptMode==='local'?'.':' e o Notion confirmar.'}`:`Saving a change invalidates the current approval: recording is blocked again until you approve the new version${run.scriptMode==='local'?'.':' and Notion confirms it.'}`}</p>}
  <label>Hook<SelectMenu ariaLabel="Opções de hook" value={hook} disabled={busy} onChange={value=>{setHook(value);setConfirm(false)}} options={pick(options?.hooks,hook)}/></label><input aria-label="Hook do roteiro" value={hook} disabled={busy} onChange={event=>{setHook(event.target.value);setConfirm(false)}}/>
  <label>CTA<SelectMenu ariaLabel="Opções de CTA" value={cta} disabled={busy} onChange={value=>{setCta(value);setConfirm(false)}} options={pick(options?.ctas,cta)}/></label><input aria-label="CTA do roteiro" value={cta} disabled={busy} onChange={event=>{setCta(event.target.value);setConfirm(false)}}/>
  <label>{pt?'Caminho narrativo':'Narrative path'}<SelectMenu ariaLabel="Caminho do roteiro" value={String(pathIndex)} disabled={busy||!options?.paths.length} onChange={value=>{setPathIndex(Number(value));setConfirm(false)}} options={(options?.paths.length?options.paths:[latest.path]).map((p,index)=>({value:String(index),label:p.title,description:p.outline}))}/></label><p>{path.outline}</p>
  <label>{pt?'Texto para gravar':'Text to record'}<textarea aria-label="Texto do roteiro" rows={10} value={text} disabled={busy} onChange={event=>{setText(event.target.value);setConfirm(false)}}/></label>
  {dirty?<button className="primary-button" disabled={busy||!hook.trim()||!cta.trim()||text.trim().length<20} onClick={()=>void act('save-script',{baseVersion:latest.version,hook,cta,path,text})}>{pt?`Salvar como v${latest.version+1}`:`Save as v${latest.version+1}`}</button>
  :approved?<p role="status">{pt?`v${latest.version} aprovada${run.scriptMode==='local'?' (modo local, sem Notion)':cardHasVersion?' e confirmada no Notion':'; aguardando o Notion'}.`:`v${latest.version} approved${run.scriptMode==='local'?' (local mode, no Notion)':cardHasVersion?' and confirmed in Notion':'; waiting for Notion'}.`}</p>
  :<><label className="production-check"><input type="checkbox" checked={confirm} disabled={busy} onChange={event=>setConfirm(event.target.checked)}/>{pt?`Aprovo a v${latest.version} (#${shortHash(latest.hash)}) e autorizo ${run.scriptMode==='local'?'liberar a gravação no modo local':cardHasVersion?'liberar a gravação (o card já contém esta versão)':'registrar esta versão no card Notion'}.`:`I approve v${latest.version} (#${shortHash(latest.hash)}) and authorize ${run.scriptMode==='local'?'releasing recording in local mode':cardHasVersion?'releasing recording (the card already holds this version)':'saving this version to the Notion card'}.`}</label>
   <button className="primary-button" disabled={busy||!confirm} onClick={()=>void act('approve-script',{authorize:true,version:latest.version,expectedHash:latest.hash})}>{pt?'Aprovar roteiro':'Approve script'}</button></>}
  <details><summary>{pt?'Gerar outra versão com o agente':'Generate another version with the agent'}</summary><label>{pt?'O que mudar':'What to change'}<textarea value={notes} disabled={busy} onChange={event=>setNotes(event.target.value)}/></label><p className="editorial-hint">{pt?`Usa uma chamada de IA (${providerName(run.providers?.source)}); suas versões anteriores continuam no histórico.`:`Uses one AI call (${providerName(run.providers?.source)}); your earlier versions stay in history.`}</p><button className="soft-button" disabled={busy||!notes.trim()} onClick={()=>void act('regenerate-script',{notes})}>{pt?'Gerar nova versão':'Generate new version'}</button></details>
  <details><summary>{pt?'Versões':'Versions'} ({run.scriptVersions?.length??0})</summary><ol>{run.scriptVersions?.map(v=><li key={v.version}>v{v.version} · {v.source} · #{shortHash(v.hash)}{run.scriptApproval?.hash===v.hash?(pt?' · aprovada':' · approved'):''}{run.notion?.scriptHash===v.hash?(pt?' · no Notion':' · in Notion'):''}</li>)}</ol></details>
 </div>;
}

export function ProductionDialog({workspaceId,flowId,sessionId,agentId,initialText,onClose,onSelectAgent}:{workspaceId:string;flowId?:string;sessionId?:string;agentId?:string;initialText?:string;onClose:()=>void;onSelectAgent?:(id:string)=>void}){
 const [reviewEdit,setReviewEdit]=useState(''),[editScript,setEditScript]=useState(false);
 const production=useProduction(),editorial=useContentWorkflow(),chat=useChat(),{agents}=useAgents(),{locale}=useLanguage(),pt=locale==='pt-BR';
 // A content session opens only its own content's production: other contents' runs and ideas are not offered here.
 const contentSession=chat.sessions.find(s=>s.id===sessionId&&s.contentId),ownedContents=new Set(chat.sessions.filter(s=>s.contentId).map(s=>s.contentId));
 const available=production.runs.filter(run=>run.workspaceId===workspaceId&&(!flowId||run.flowId===flowId)&&(!contentSession||run.contentId===contentSession.contentId));
 const flows=production.flows.flows.filter(f=>f.workspaceId===workspaceId),contextScope=startDraftScope(workspaceId,flowId??'',sessionId);
 const [selected,setSelected]=useStudioDraftField(contextScope,'run',available.find(run=>run.sourceSession.id===sessionId||run.editorSession.id===sessionId)?.id??''),[savedFlow,setChosenFlow]=useStudioDraftField(contextScope,'flow',flowId??flows.find(f=>f.nodes.some(n=>n.kind==='content-agent'&&n.agentId===agentId))?.id??flows[0]?.id??'');
 const chosenFlow=validSelection(savedFlow,flows),startScope=startDraftScope(workspaceId,chosenFlow,sessionId);
 const [savedTopic,setTopicId]=useStudioDraftField(startScope,'topic',''),[notionInput,setNotionInput]=useStudioDraftField(startScope,'notion-input','');
 const [destination,setDestination]=useState(''),[authorize,setAuthorize]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[resend,setResend]=useState(false),[editing,setEditing]=useState<PublicationDelivery>();
 const run=available.find(run=>run.id===selected)??(contentSession?available.find(item=>item.sourceSession.id===sessionId&&!['complete','canceled'].includes(item.stage)):undefined),topics=editorial.state.topics.filter(topic=>topic.workspaceId===workspaceId&&['review','approved'].includes(topic.status)&&(contentSession?topic.contentId===contentSession.contentId:!topic.contentId||!ownedContents.has(topic.contentId))),topicId=validSelection(savedTopic,topics),content=editorial.state.contents.find(content=>content.id===run?.contentId&&content.workspaceId===workspaceId),assets=(editorial.state.assets??[]).filter(a=>a.contentId===run?.contentId&&a.workspaceId===workspaceId);
 const notesScope=runDraftScope(workspaceId,run?.id??'','notes'),videoScope=runDraftScope(workspaceId,run?.id??'','video'),platformScope=runDraftScope(workspaceId,run?.id??'','platforms');
 const [notes,setNotes]=useStudioDraftField(notesScope,'notes',''),[savedVideo,setSavedVideo]=useStudioDraftField(videoScope,'video',''),[savedFormat,setFormat]=useStudioDraftField(videoScope,'format','original'),[savedEditMode,setEditMode]=useStudioDraftField(videoScope,'editMode','smart'),[savedMotion,setMotion]=useStudioDraftField(videoScope,'motion','balanced'),[savedNetworks,setNetworks]=useStudioDraftField<string[]>(platformScope,'networks',run?.platforms??['Instagram','TikTok']);
 const sourceVideo=restoreVideo(savedVideo,assets),format=['original','portrait'].includes(savedFormat)?savedFormat:'original',editMode=savedEditMode==='basic'?'basic':'smart',networks=validNetworks(savedNetworks);
 const flow=flows.find(f=>f.id===chosenFlow);
 // B07: explicit per-start choice (flow keeps the last one as a starting point). Notion stays the default.
 const [scriptMode,setScriptModeState]=useState<'notion'|'local'>('notion');
 useEffect(()=>{setScriptModeState(flow?.scriptMode==='local'?'local':'notion')},[flow?.id]);// eslint-disable-line react-hooks/exhaustive-deps
 const setScriptMode=(mode:'notion'|'local')=>{setScriptModeState(mode);if(flow)updatePersistentValue<ProductionFlows>('production-flows',production.flows,current=>({...current,flows:current.flows.map(f=>f.id===flow.id?{...f,scriptMode:mode}:f)}));};
 const [enableNotion,setEnableNotion]=useState(false);
 const [preflight,setPreflight]=useState<PreflightReport|null>(null),[preflightError,setPreflightError]=useState(''),[checkMedia,setCheckMedia]=useState(false);
 const roleAgents=JSON.stringify(flow?.nodes.map(n=>agents.find(a=>a.id===n.agentId)).map(a=>a&&[a.id,a.providerId,a.modelId]));
 const preflightBlockers=(preflight?.blockers??[]).filter(c=>!['flow','topic','notion-destination'].includes(c.id)).map(c=>({text:c.message,...(c.id.endsWith('-agent')?{href:'#flow'}:{})}));
 const startMissing=[...(!chosenFlow?[{text:pt?'Escolha um fluxo.':'Choose a flow.',focus:'Fluxo da produção'}]:[]),...(chosenFlow&&!preflight?[{text:preflightError||(pt?'Aguarde a verificação antes de iniciar.':'Wait for the pre-start check.')}]:[]),...preflightBlockers,...(!topicId?[{text:pt?'Escolha uma ideia estruturada atual.':'Choose a current structured idea.',focus:'Ideia da produção'}]:[]),...(scriptMode==='notion'&&!destination?[{text:pt?'Configure o destino Notion abaixo ou escolha o modo local.':'Configure the Notion destination below or choose local mode.',focus:'Notion destination'}]:[]),...(!authorize?[{text:pt?'Revise a ideia e o destino e marque a autorização acima.':'Review the idea and destination, then check the authorization above.'}]:[])];
 const setSourceVideo=(id:string)=>{const asset=assets.find(a=>a.id===id);setSavedVideo(asset?videoDraftValue(asset):'')};
 // Recording package: explicit import of the video recorded outside the app, then it becomes the video to edit.
 const [pendingVideo,setPendingVideo]=useState('');
 useEffect(()=>{if(!pendingVideo)return;const asset=assets.find(a=>a.kind==='video'&&a.role==='source'&&a.versions.some(v=>v.sha256===pendingVideo));if(asset){setSourceVideo(asset.id);setPendingVideo('');document.querySelector<HTMLElement>('[aria-label="Vídeo da produção"]')?.scrollIntoView({block:'nearest'});}},[pendingVideo,assets]); // eslint-disable-line react-hooks/exhaustive-deps
 const importVideo=async()=>{
  const native=window.mainsAgentsDesktop?.files;if(!run||!content)return;
  if(!native){focusField('Vídeo da produção');return;}
  setBusy(true);setError('');
  try{const files=await native.select(storageProfile(),content.id,false),video=files.find(f=>f.status==='available'&&f.kind==='video');if(!files.length)return;if(!video){setError(files.map(f=>f.error||(pt?`${f.name}: escolha um arquivo de vídeo.`:`${f.name}: choose a video file.`)).join('\n'));return;}await editorial.attachFiles(content.id,[video],'source');setPendingVideo(video.sha256!);}
  catch(failure){setError((failure as Error).message)}finally{setBusy(false)}
 };
 const prepTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const savePrep=(data:Record<string,unknown>,delay=0)=>{if(!run?.scriptApproval)return;clearTimeout(prepTimer.current);prepTimer.current=setTimeout(()=>{void production.command(run,'recording-prep',{version:run.scriptApproval!.version,hash:run.scriptApproval!.hash,...data}).catch(failure=>setError((failure as Error).message));},delay);};
 useEffect(()=>{let live=true;setDestination('');void editorial.getNotionConnection(workspaceId).then(config=>{if(live)setDestination(config.autoSync?config.dataSourceId:'')}).catch(()=>{});return()=>{live=false}},[workspaceId,editorial.getNotionConnection]);
 useEffect(()=>{setAuthorize(false)},[workspaceId,selected,chosenFlow,JSON.stringify(flow),topicId,JSON.stringify(topics.find(t=>t.id===topicId)),destination,scriptMode,preflight?.fingerprint]);
 // Read-only server check whenever the reviewed inputs change; it never starts or queues work. FFmpeg is probed only after an explicit request.
 useEffect(()=>{if(run||!chosenFlow){setPreflight(null);return;}let live=true;setPreflight(null);setPreflightError('');const timer=setTimeout(()=>void production.preflight({flowId:chosenFlow,topicId,expectedTopic:topics.find(t=>t.id===topicId),scriptMode,...(scriptMode==='notion'?{notionDestination:destination}:{}),language:locale,probeMedia:checkMedia}).then(report=>{if(live)setPreflight(report)}).catch(error=>{if(live)setPreflightError((error as Error).message)}),250);return()=>{live=false;clearTimeout(timer)}},[run?.id,workspaceId,chosenFlow,JSON.stringify(flow),roleAgents,topicId,JSON.stringify(topics.find(t=>t.id===topicId)),destination,scriptMode,checkMedia,locale]);
 useEffect(()=>{setResend(false);setError('');setEditing(undefined)},[workspaceId,selected,run?.reviewHash,run?.outputVideo?.versionId]);
 const configureNotion=async()=>{setBusy(true);setError('');try{await editorial.configureNotion(workspaceId,{dataSourceId:notionInput.trim().replace(/^collection:\/\//,''),autoSync:true});const configured=await editorial.getNotionConnection(workspaceId);setDestination(configured.dataSourceId);}catch(error){setError((error as Error).message)}finally{setBusy(false)}};
 const action=async(type:string,data:Record<string,unknown>={}):Promise<ProductionRun|undefined>=>{if(!run||busy)return;setBusy(true);setError('');try{const result=await production.command(run,type,data);if(['revise-video','revise-package'].includes(type))clearStudioDraft(notesScope);if(type==='video')clearStudioDraft(videoScope);if(type==='platforms')clearStudioDraft(platformScope);return result}catch(error){setError((error as Error).message)}finally{setBusy(false)}};
 const start=async()=>{if(busy)return;const topic=topics.find(t=>t.id===topicId);if(!topic)return;setBusy(true);setError('');try{const value=await production.start({flowId:chosenFlow,topicId,expectedTopic:topic,sourceSessionId:sessionId,scriptMode,...(scriptMode==='notion'?{notionDestination:destination}:{}),authorize,timeZone:'America/Sao_Paulo',language:locale,preflightFingerprint:preflight?.fingerprint});clearStudioDraft(startScope);setAuthorize(false);setSelected(value.id);}catch(error){setError((error as Error).message)}finally{setBusy(false)}};
 const captureIdeas=async()=>{const session=chat.sessions.find(s=>s.id===sessionId),message=session?.messages.filter(m=>m.type==='message'&&m.role==='agent'&&m.deliveryState==='completed'&&decodeChatDelivery(m.content)?.kind==='research').at(-1);if(message?.type!=='message'){setError(pt?'Peça ideias estruturadas ao agente ou faça uma pesquisa no Estúdio.':'Ask the agent for structured ideas or run research in Studio.');return;}setBusy(true);setError('');try{await editorial.captureChatDelivery(session!.id,message.id,message.content)}catch(error){setError((error as Error).message)}finally{setBusy(false)}};
 const openSession=(editor=false)=>{if(!run)return;const session=editor?run.editorSession:run.sourceSession;chat.openSession(session.agentId,session.id);onSelectAgent?.(session.agentId);onClose()};
 if(reviewEdit&&run)return <EditReview contentId={run.contentId} jobId={reviewEdit} onClose={()=>setReviewEdit('')} onUseVersion={jobId=>action('use-edited-video',{jobId,authorize:true})}/>;
 if(editing)return <PublicationEditor delivery={editing} onClose={()=>{setEditing(undefined);void production.refresh()}}/>;
 return <FlowDialog title={run?`${run.topic.title} · ${productionStageLabel(run.stage,pt)}`:(pt?'Produção semiautomática':'Semi-automatic production')} description={pt?'Chat e Fluxo acompanham a mesma produção. As aprovações ficam ligadas à versão apresentada.':'Chat and Flow follow the same production. Approvals apply to the displayed version.'} onClose={()=>{if(!busy)onClose()}}>
  <div className="production-panel-body" data-od-id="production-panel"><div className="production-section"><SelectMenu ariaLabel="Produção atual" value={run?.id??''} disabled={busy} onChange={id=>{setSelected(id);setError('')}} options={[...(contentSession&&available.some(item=>!['complete','canceled'].includes(item.stage))?[]:[{value:'',label:pt?'Nova produção a partir de uma ideia':'New production from an idea'}]),...available.map(run=>({value:run.id,label:run.topic.title,description:productionStageLabel(run.stage,pt)}))]}/></div>
   {run?.entry?.kind==='recorded'&&<p className="editorial-hint production-entry-origin">{pt?`Entrada com vídeo já gravado (${run.entry.video.name}) e ${run.entry.origin==='notion'?'card do Notion existente, só leitura':'contexto colado'}. Roteiro e gravação não são refeitos aqui.`:`Entered with an already recorded video (${run.entry.video.name}) and ${run.entry.origin==='notion'?'an existing Notion card, read-only':'pasted context'}. Script and recording are not redone here.`}</p>}
   {!run?<div className="production-section"><label>{pt?'Fluxo':'Flow'}<SelectMenu ariaLabel="Fluxo da produção" value={chosenFlow} onChange={setChosenFlow} options={production.flows.flows.filter(f=>f.workspaceId===workspaceId).map(f=>({value:f.id,label:f.name}))}/></label><label>{pt?'Ideia para aprovar':'Idea to approve'}<SelectMenu ariaLabel="Ideia da produção" value={topicId} onChange={setTopicId} options={[{value:'',label:pt?'Escolher ideia estruturada':'Choose structured idea'},...topics.map(t=>({value:t.id,label:t.title,description:t.summary}))]}/></label>{sessionId&&!contentSession&&<button className="soft-button" disabled={busy} onClick={()=>void captureIdeas()}>{pt?'Usar ideias desta conversa':'Use ideas from this chat'}</button>}{contentSession&&<p className="editorial-hint">{pt?'Esta sessão é de um conteúdo: a ideia é a do próprio conteúdo.':'This is a content session: the idea is the content’s own.'}</p>}{!topics.length&&<p>{pt?'Peça ideias ao agente e use “Usar ideias desta conversa”, ou crie uma pesquisa no Estúdio.':'Ask the agent for ideas and use “Use ideas from this chat”, or create research in Studio.'}</p>}<fieldset className="production-mode" disabled={busy}><legend>{pt?'Onde fica o roteiro aprovado':'Where the approved script lives'}</legend>
     <label className="production-check"><input type="radio" name="production-script-mode" checked={scriptMode==='notion'} onChange={()=>setScriptMode('notion')}/>{pt?'Notion: o card é criado com o roteiro aprovado e a gravação só é liberada depois da confirmação.':'Notion: the card is created with the approved script and recording is released only after confirmation.'}</label>
     <label className="production-check"><input type="radio" name="production-script-mode" checked={scriptMode==='local'} onChange={()=>setScriptMode('local')}/>{pt?'Local: sem Notion. Aprovar o roteiro libera a gravação neste PC; dá para ativar o Notion depois, com o mesmo roteiro.':'Local: no Notion. Approving the script releases recording on this PC; you can enable Notion later with the same script.'}</label></fieldset>
    {scriptMode==='notion'&&<><p>{pt?'Destino Notion autorizado':'Authorized Notion destination'}: {destination|| (pt?'Configure a base abaixo.':'Configure the database below.')}</p>{!destination&&<><label>{pt?'ID da base Notion (collection)':'Notion data source ID (collection)'}<input aria-label="Notion destination" value={notionInput} onChange={event=>setNotionInput(event.target.value)} placeholder="collection://…"/></label><button className="soft-button" disabled={busy||!notionInput.trim()} onClick={()=>void configureNotion()}>{pt?'Salvar destino Notion':'Save Notion destination'}</button></>}</>}<label className="production-check"><input type="checkbox" checked={authorize} disabled={busy||!preflight||preflight.blockers.length>0} title={!preflight?(pt?'Aguarde a verificação antes de aprovar.':'Wait for the pre-start check before approving.'):undefined} onChange={event=>setAuthorize(event.target.checked)}/>{scriptMode==='local'?(pt?'Aprovo esta ideia e autorizo gerar o roteiro no modo local, sem Notion.':'I approve this idea and authorize script generation in local mode, without Notion.'):(pt?'Aprovo esta ideia e autorizo gerar o roteiro e criar/atualizar o card nesta base Notion.':'I approve this idea and authorize script generation and card creation/update in this Notion database.')}</label>{preflight&&<ProductionPreflight report={preflight} pt={pt} busy={busy} onCheckMedia={()=>setCheckMedia(true)}/>}<Prerequisites items={startMissing} onNavigate={onClose}/><button className="primary-button" disabled={busy||!!startMissing.length} onClick={()=>void start()}>{pt?'Aprovar ideia e iniciar produção':'Approve idea and start production'}</button></div>:<>
    <ProductionProgress run={run} pt={pt}/><ProductionBudget key={run.id} run={run} pt={pt} busy={busy} act={action}/><div className="production-section production-stage"><strong>{productionStageLabel(run.stage,pt)}</strong><p>{run.name}</p><div className="production-chat-links"><button className="soft-button" onClick={()=>openSession()}>{pt?'Conversa do conteúdo':'Content chat'}</button><button className="soft-button" onClick={()=>openSession(true)}>{pt?'Conversa da edição':'Editing chat'}</button></div><p className="editorial-hint">{pt?'Quem executa cada papel':'Who runs each role'}: {([[pt?'conteúdo':'content',run.sourceAgent],[pt?'edição':'editing',run.editorAgent],[pt?'publicação':'publishing',run.publisherAgent??run.sourceAgent]] as const).map(([role,agent])=>`${role} ${providerName(agent.providerId??'codex')} · ${agent.modelId||(pt?'modelo padrão do provedor':'provider default model')}`).join(' — ')}</p>{run.notion&&<a href={run.notion.url} target="_blank" rel="noopener noreferrer">{pt?'Abrir card do Notion':'Open Notion card'}</a>}{run.error&&<p className="delivery-error" role="alert">{run.error}</p>}</div>
    {(run.stage==='script-review'||['paused','blocked'].includes(run.stage)&&['script-review','notion'].includes(run.resumeStage??'')&&!!run.scriptVersions?.length)&&<ScriptReview key={run.scriptVersions?.at(-1)?.hash??run.id} run={run} act={action} busy={busy} pt={pt}/>}
    {run.stage==='recording'&&!!run.scriptVersions?.length&&<div className="production-section"><p>{run.recordingReady?(run.scriptMode==='local'?(pt?`Gravação liberada para o roteiro aprovado v${run.scriptApproval?.version} (#${shortHash(run.scriptApproval?.hash)}), modo local sem Notion.`:`Recording released for approved script v${run.scriptApproval?.version} (#${shortHash(run.scriptApproval?.hash)}), local mode without Notion.`):(pt?`Gravação liberada para o roteiro aprovado v${run.scriptApproval?.version} (#${shortHash(run.scriptApproval?.hash)}), confirmado no Notion.`:`Recording released for approved script v${run.scriptApproval?.version} (#${shortHash(run.scriptApproval?.hash)}), confirmed in Notion.`)):(run.scriptMode==='local'?(pt?'A gravação está bloqueada: aprove o roteiro atual.':'Recording is blocked: approve the current script.'):(pt?'A gravação está bloqueada: aprove o roteiro atual e aguarde a confirmação do Notion.':'Recording is blocked: approve the current script and wait for Notion confirmation.'))}</p><button className="text-link" disabled={busy} onClick={()=>setEditScript(value=>!value)}>{editScript?(pt?'Fechar edição do roteiro':'Close script editing'):(pt?'Editar roteiro (exige nova aprovação)':'Edit script (requires new approval)')}</button>{editScript&&<ScriptReview key={run.scriptVersions.at(-1)?.hash} run={run} act={action} busy={busy} pt={pt} editingApproved/>}</div>}
    {run.scriptMode==='local'&&['script-review','recording'].includes(run.stage)&&<details className="production-section"><summary>{pt?'Ativar o Notion nesta produção':'Enable Notion for this production'}</summary>
     <p className="editorial-hint">{pt?'Opcional. O roteiro aprovado (mesma versão e hash) vira um card no destino autorizado; repetir não cria card duplicado. Enquanto o Notion não confirmar, a gravação fica bloqueada.':'Optional. The approved script (same version and hash) becomes a card in the authorized destination; repeating never creates a duplicate. Until Notion confirms, recording is blocked.'}</p>
     <p>{pt?'Destino Notion autorizado':'Authorized Notion destination'}: {destination||(pt?'nenhum configurado neste espaço.':'none configured in this workspace.')}</p>
     <label className="production-check"><input type="checkbox" checked={enableNotion} disabled={busy||!destination} onChange={event=>setEnableNotion(event.target.checked)}/>{pt?'Autorizo criar/atualizar o card desta produção nesta base Notion.':'I authorize creating/updating this production’s card in this Notion database.'}</label>
     <button className="soft-button" disabled={busy||!destination||!enableNotion} onClick={()=>void action('enable-notion',{authorize:true,notionDestination:destination}).then(()=>setEnableNotion(false))}>{pt?'Ativar Notion':'Enable Notion'}</button></details>}
    {run.stage==='recording'&&run.recordingReady&&(()=>{const prep=run.recordingPrep&&run.recordingPrep.version===run.scriptApproval?.version&&run.recordingPrep.hash===run.scriptApproval?.hash?run.recordingPrep:null;return <RecordingPackage run={run} pt={pt} busy={busy} ready={!!run.recordingReady} checklist={prep?{version:prep.version,hash:prep.hash,items:prep.checklist}:null} suggestions={prep?.suggestions??null} onChecklistChange={next=>savePrep({checklist:next.items})} onSuggestionsChange={(_version,_hash,list)=>savePrep({suggestions:list},800)} onImportVideo={()=>void importVideo()}/>;})()}
    {run.stage==='recording'&&content&&<div className="production-section"><ContentAssetLibrary content={content}/><label>{pt?'Vídeo para editar':'Video to edit'}<SelectMenu ariaLabel="Vídeo da produção" value={sourceVideo} onChange={setSourceVideo} options={[{value:'',label:pt?'Escolher gravação':'Choose recording'},...assets.filter(a=>a.kind==='video'&&a.role==='source').map(a=>({value:a.id,label:a.name,disabled:a.status!=='available'}))]}/></label><label>{pt?'Formato autorizado':'Authorized format'}<SelectMenu ariaLabel="Formato da edição" value={format} onChange={setFormat} options={[{value:'original',label:pt?'Preservar enquadramento':'Keep framing'},{value:'portrait',label:pt?'Recortar para vertical 9:16':'Crop to vertical 9:16'}]}/></label><label>{pt?'Tipo de edição':'Editing mode'}<SelectMenu ariaLabel="Tipo de edição" value={editMode} onChange={setEditMode} options={[{value:'smart',label:pt?'Automática: cortar silêncios e animar':'Automatic: cut silences and animate'},{value:'basic',label:pt?'Básica: um corte contínuo':'Basic: one continuous cut'}]}/></label>{editMode==='smart'&&<MotionIntensityField value={savedMotion} onChange={setMotion} pt={pt} disabled={busy}/>}<p>{editMode==='smart'?(pt?'O FFmpeg local detecta e remove silêncios com margem para proteger a fala; o Editor escolhe título, tarja e CTA, renderizados com Remotion quando disponível. O original é preservado e você revisa o vídeo antes de aprovar.':'Local FFmpeg detects and removes silences with padding to protect speech; the editor picks title, lower third and CTA, rendered with Remotion when available. The original is preserved and you review the video before approving.'):(pt?'O Editor propõe cortes, normalização de áudio e transições discretas; o executor local cria outro arquivo. Suas alterações no Notion entram no briefing.':'The editor plans cuts, audio normalization and subtle fades; the local executor creates a new file. Your Notion edits enter the briefing.')}</p>{!sourceVideo&&<Prerequisites items={[{text:pt?'Associe uma gravação disponível na biblioteca acima e escolha o vídeo.':'Attach an available recording in the library above and choose the video.',focus:'Vídeo da produção'}]}/>}{!run.recordingReady&&<Prerequisites items={[{text:pt?'Aprove o roteiro atual e aguarde a confirmação do Notion.':'Approve the current script and wait for Notion confirmation.'}]}/>}<button className="primary-button" disabled={busy||!sourceVideo||!run.recordingReady} onClick={()=>void action('video',{assetId:sourceVideo,format,editMode,motion:motionIntensity(savedMotion),authorize:true})}>{editMode==='smart'?(pt?'Enviar vídeo e iniciar edição automática':'Send video and start automatic editing'):(pt?'Enviar vídeo e iniciar edição básica':'Send video and start basic editing')}</button></div>}
    {run.stage==='video-review'&&run.outputVideo&&<div className="production-section">{run.videoJobId&&editorial.mediaJobs.some(job=>job.id===run.videoJobId&&job.mode==='advanced')&&<button className="primary-button" onClick={()=>setReviewEdit(run.videoJobId!)}>{pt?'Conferir edição (bruto × editado)':'Review edit (raw × edited)'}</button>}<button className="soft-button" onClick={()=>void window.mainsAgentsDesktop?.files?.open(storageProfile(),run.contentId,run.outputVideo!.assetId).catch(error=>setError(error.message))}>{pt?'Abrir vídeo editado':'Open edited video'}</button><p>{pt?'Revise esta versão antes de aprovar. O original continua salvo.':'Review this version before approval. The original remains saved.'}</p><button className="primary-button" disabled={busy||captionJobRunning(run)} onClick={()=>void action('approve-video',{authorize:true,expectedVideo:run.outputVideo})}>{run.captions?.output&&sameVideo(run.captions.output,run.outputVideo)?(pt?'Aprovar este vídeo legendado':'Approve this captioned video'):(pt?'Aprovar este vídeo':'Approve this video')}</button><label>{pt?'Pedir ajuste':'Request revision'}<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label><button className="soft-button" disabled={busy||!notes.trim()} onClick={()=>void action('revise-video',{notes})}>{pt?'Enviar ajuste ao editor':'Send revision to editor'}</button></div>}
    {run.stage==='video-review'&&run.outputVideo&&<CaptionReview key={`${run.outputVideo.sha256}`} run={run} pt={pt} busy={busy} act={action}/>}
    {['platforms','covers-review','package-review','schedule'].includes(run.stage)&&run.approvedVideo&&<ReopenVideo run={run} pt={pt} busy={busy} act={action}/>}
    {run.stage==='covers-review'&&run.covers&&<CoversReview key={`${run.covers.source.sha256}:${run.covers.destinations.map(d=>d.platform).join()}`} run={run} pt={pt} busy={busy} act={action}/>}
    {run.stage==='covers-review'&&<div className="production-section"><label>{pt?'Pedir novas legendas':'Request new captions'}<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label><button className="soft-button" disabled={busy||!notes.trim()||run.covers?.render?.status==='running'} onClick={()=>void action('revise-package',{notes})}>{pt?'Gerar novas legendas (usa uma chamada de IA)':'Generate new captions (uses one AI call)'}</button></div>}
    {run.stage==='platforms'&&<div className="production-section"><h3>{pt?'Onde deseja publicar?':'Where would you like to publish?'}</h3>{['Instagram','TikTok','LinkedIn'].map(platform=><label className="production-check" key={platform}><input type="checkbox" checked={networks.includes(platform)} onChange={()=>setNetworks(current=>{const valid=validNetworks(current);return valid.includes(platform)?valid.filter(p=>p!==platform):[...valid,platform]})}/>{platform}</label>)}<p>{pt?'Vou preparar uma legenda por rede (IA de texto do agente de publicação). Depois você exporta três capas locais por formato neste PC, sem IA, e aprova uma por rede. Edição e capas usam FFmpeg.':'I will prepare one caption per network (text AI from the publishing agent). Then you export three local covers per format on this PC, without AI, and approve one per network. Editing and covers use FFmpeg.'}</p><button className="primary-button" disabled={busy||!networks.length} onClick={()=>void action('platforms',{platforms:networks})}>{pt?'Gerar capas e legendas':'Generate covers and captions'}</button></div>}
    {['package-review','schedule'].includes(run.stage)&&<div className="production-section"><h3>{pt?'Pacote por plataforma':'Per-platform package'}</h3>{run.reviewDeliveries?.map(delivery=><article className="production-package" key={delivery.id}><CoverPreview run={run} delivery={delivery}/><strong>{delivery.platform} · v{delivery.version}</strong><p>{delivery.text}</p><button className="text-link" onClick={()=>setEditing(delivery)}>{pt?'Editar esta entrega':'Edit this delivery'}</button></article>)}<button className="primary-button" disabled={busy||!run.reviewHash} onClick={()=>void action('approve-package',{authorize:true,expectedHash:run.reviewHash})}>{pt?'Aprovar vídeo, capas e legendas':'Approve video, covers and captions'}</button><label>{pt?'Pedir novas capas ou legendas':'Request new covers or captions'}<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label><button className="soft-button" disabled={busy||!notes.trim()} onClick={()=>void action('revise-package',{notes})}>{pt?'Gerar nova versão com ajustes':'Generate revised version'}</button></div>}
    {run.stage==='schedule'&&<ScheduleForm key={scheduleDraftScope(run)} run={run} initialText={initialText} act={action} busy={busy}/>}
    {['paused','blocked'].includes(run.stage)&&<div className="production-section"><p>{pt?'Retomar verifica o turno e os arquivos salvos antes de continuar. Um envio externo incerto deve ser consultado nas entregas.':'Resume checks saved turns and files before continuing. Uncertain external sends must be checked in deliveries.'}</p><label className="production-check"><input type="checkbox" checked={resend} onChange={event=>setResend(event.target.checked)}/>{pt?'Se necessário, autorizo reenviar a instrução de IA e consumir novos tokens.':'If needed, I authorize resending the AI instruction and consuming more tokens.'}</label><button className="primary-button" disabled={busy||run.imported} onClick={()=>void action('resume',{authorize:true,resend})}>{pt?'Retomar e verificar produção':'Resume and verify production'}</button>{run.imported&&<p>{pt?'Histórico importado não autoriza execução. Inicie uma nova produção com revisão da ideia e destino.':'Imported history does not authorize execution. Start a new production after reviewing the idea and destination.'}</p>}</div>}
    {['scheduling','complete','blocked'].includes(run.stage)&&content&&<ContentPublications content={content}/>}
    {run.step?.output&&!['recording','video-review','package-review','schedule','complete'].includes(run.stage)&&<details><summary>{pt?'Resposta da etapa':'Stage response'}</summary><pre className="production-output">{run.step.output}</pre></details>}
    <details className="production-section"><summary>{pt?'Histórico desta produção':'Production history'}</summary><ol>{run.events?.map((event,index)=><li key={index}>{new Date(event.at).toLocaleString(locale)} · {productionStageLabel(event.action,pt)}{event.detail&&<small>{event.detail}</small>}</li>)}</ol></details>
    {!['scheduling','complete','canceled'].includes(run.stage)&&<button className="text-link" disabled={busy} onClick={()=>void action('cancel')}>{pt?'Interromper próximas etapas':'Stop next stages'}</button>}
   </>}
   {error&&<p className="delivery-error" role="alert">{error}</p>}{production.error&&<p role="alert">{production.error}</p>}{busy&&<p role="status">{pt?'Salvando sua decisão…':'Saving your decision…'}</p>}
  </div>
 </FlowDialog>;
}
