import {useEffect,useState} from 'react';
import {useProduction} from '../../features/production/ProductionProvider';
import {productionStageLabel,type ProductionRun,type ScheduleTarget} from '../../features/production/model';
import {useContentWorkflow} from '../../features/content/ContentWorkflowProvider';
import {useChat} from '../../features/chat/ChatProvider';
import {useAgents} from '../../features/agents/AgentsProvider';
import {useLanguage} from '../../app/LanguageProvider';
import {FlowDialog} from '../common/FlowDialog';
import {SelectMenu} from '../common/SelectMenu';
import {ContentAssetLibrary} from '../content/ContentAssetLibrary';
import {ContentPublications} from '../content/ContentPublications';
import {PublicationEditor} from '../content/ContentPublications';
import {PublicationNetworkSettings} from '../content/PublicationNetworkSettings';
import {storageProfile} from '../../data/IndexedDbStateStore';
import {localTimeToInstant,zonedDateTime} from '../../../publication-time.mjs';
import type {Platform,PublicationDelivery} from '../../features/content/model';
import {decodeChatDelivery} from '../../../chat-delivery-protocol.mjs';
import {useStudioDraftField,clearStudioDraft} from '../../features/content/studioDrafts';
import {startDraftScope,runDraftScope,scheduleDraftScope,validSelection,validNetworks,videoDraftValue,restoreVideo,targetsDraftValue,restoreTargets,validTimeZone,validLocalDate,scheduleFingerprint} from '../../features/production/productionDrafts';
import {ProductionProgress} from './ProductionProgress';
import {ProductionBudget} from './ProductionBudget';
import './production.css';

function CoverPreview({run,delivery}:{run:ProductionRun;delivery:PublicationDelivery}){
 const [src,setSrc]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let live=true;setSrc('');if(!delivery.cover)return;const preview=window.mainsAgentsDesktop?.files?.preview;if(preview)void preview(storageProfile(),run.contentId,delivery.cover.assetId).then(src=>{if(live)setSrc(src)}).catch(error=>{if(live)setError(error.message)});return()=>{live=false}},[run.contentId,delivery.cover?.assetId,delivery.cover?.versionId]);
 return <figure className="production-cover">{src?<img src={src} alt={`Capa ${delivery.platform}`}/>:<span>{error||'Capa disponível na biblioteca e na conversa.'}</span>}</figure>;
}
function focusField(label:string){document.querySelector<HTMLElement>(`[aria-label="${label}"]`)?.focus();}
function Prerequisites({items,onNavigate}:{items:Array<{text:string;focus?:string;href?:string}>;onNavigate?:()=>void}){
 return items.length?<ul className="editorial-hint" aria-live="polite">{items.map(item=><li key={item.text}>{item.focus?<button className="text-link" onClick={()=>focusField(item.focus!)}>{item.text}</button>:item.href?<a href={item.href} onClick={onNavigate}>{item.text}</a>:item.text}</li>)}</ul>:null;
}
function ScheduleForm({run,initialText,act,busy}:{run:ProductionRun;initialText?:string;busy:boolean;act:(action:string,data?:Record<string,unknown>)=>Promise<ProductionRun|undefined>}){
 const {publicationAccounts}=useContentWorkflow(),{locale}=useLanguage(),pt=locale==='pt-BR';
 const scope=scheduleDraftScope(run);
 const [initialDate]=useState(()=>!initialText&&run.schedule?zonedDateTime(run.schedule.plannedAt,run.schedule.timeZone):'');
 const [text,setText]=useStudioDraftField(scope,'text',initialText??''),[savedZone,setZone]=useStudioDraftField(scope,'zone',run.schedule?.timeZone??run.timeZone),[savedDate,setDate]=useStudioDraftField(scope,'date',initialDate),[savedTargets,setTargets]=useStudioDraftField(scope,'targets',targetsDraftValue(run.schedule?.targets??[]));
 const zone=validTimeZone(savedZone,validTimeZone(run.timeZone)),date=validLocalDate(savedDate);
 const [error,setError]=useState(''),[loading,setLoading]=useState(''),[reviewed,setReviewed]=useState<{fingerprint:string;hash:string}|null>(null),[accounts,setAccounts]=useState<Record<string,Array<{id:string;name:string}>>>({});
 const [confirmations,setConfirmations]=useState<Record<string,{fingerprint:string;preview:boolean;consent:boolean}>>({});
 const targets=restoreTargets(savedTargets,run).map(target=>{const confirmation=confirmations[target.platform],fingerprint=targetsDraftValue([target]);const t=target.networkSettings?.tiktokSettings;if(!t)return target;return {...target,networkSettings:{...target.networkSettings,tiktokSettings:{...t,content_preview_confirmed:confirmation?.fingerprint===fingerprint&&confirmation.preview===true,express_consent_given:confirmation?.fingerprint===fingerprint&&confirmation.consent===true}}};});
 const fingerprint=scheduleFingerprint(scope,text,date,zone,targets),accountKey=(target:ScheduleTarget)=>`${target.provider}:${target.platform}`;
 const accountsValid=targets.length>0&&targets.every(t=>accounts[accountKey(t)]?.some(a=>a.id===t.accountId));
 const timeValid=!!text.trim()||!!date,consentsValid=targets.every(t=>t.platform!=='TikTok'||!!t.networkSettings?.tiktokSettings?.content_preview_confirmed&&!!t.networkSettings.tiktokSettings.express_consent_given);
 const patch=(platform:string,change:Partial<ScheduleTarget>)=>{const before=targets.find(t=>t.platform===platform);if(!before)return;const next={...before,...change},unchanged=targetsDraftValue([before])===targetsDraftValue([next]);setTargets(targetsDraftValue(targets.map(t=>t.platform===platform?next:t)));setReviewed(null);setConfirmations(current=>({...current,[platform]:{fingerprint:targetsDraftValue([next]),preview:unchanged&&next.networkSettings?.tiktokSettings?.content_preview_confirmed===true,consent:unchanged&&next.networkSettings?.tiktokSettings?.express_consent_given===true}}));};
 const load=async(target:ScheduleTarget)=>{setLoading(target.platform);setError('');setReviewed(null);try{const result=await publicationAccounts(target.provider,target.platform);setAccounts(current=>({...current,[accountKey(target)]:result.accounts}));if(target.accountId&&!result.accounts.some(a=>a.id===target.accountId))patch(target.platform,{accountId:''});}catch(error){setError((error as Error).message)}finally{setLoading('')}};
 const missing=[...(!targets.length?[{text:pt?'Revise e aprove um pacote com plataformas antes de agendar.':'Review and approve a package with platforms before scheduling.'}]:[]),...(!timeValid?[{text:pt?'Informe data e horário acima.':'Enter a date and time above.',focus:'Production exact date'}]:[]),...targets.filter(t=>!accounts[accountKey(t)]?.some(a=>a.id===t.accountId)).map(t=>({text:pt?`${t.platform}: consulte as contas e escolha uma conta atual.`:`${t.platform}: check accounts and choose a current account.`,focus:`Conta ${t.platform}`})),...(!consentsValid?[{text:pt?'Revise a mídia e marque os consentimentos TikTok desta versão acima.':'Review the media and check the TikTok consents for this version above.'}]:[])];
 return <div className="production-section"><h3>{pt?'Quando e onde agendar?':'When and where to schedule?'}</h3><label>{pt?'Data e horário pela conversa':'Date and time in words'}<input aria-label="Horário da produção" value={text} disabled={busy} onChange={event=>{setReviewed(null);setText(event.target.value)}} placeholder={pt?'Amanhã às 18h':'Tomorrow at 18:00'}/></label><label>{pt?'Ou escolha uma data exata':'Or choose an exact date'}<input aria-label="Production exact date" type="datetime-local" value={date} disabled={busy} onChange={event=>{setReviewed(null);setDate(event.target.value)}}/></label><label>{pt?'Fuso':'Time zone'}<SelectMenu value={zone} disabled={busy} onChange={value=>{setReviewed(null);setZone(value)}} ariaLabel="Fuso da produção" options={[...new Set([zone,'America/Sao_Paulo','America/Manaus','America/Recife','Europe/Lisbon','UTC'])].map(value=>({value,label:value}))}/></label>
  {targets.map(target=><section className="production-target" key={target.platform}><strong>{target.platform}</strong><SelectMenu ariaLabel={`Provedor ${target.platform}`} value={target.provider} disabled={busy||!!loading} onChange={value=>{patch(target.platform,{provider:value as ScheduleTarget['provider'],accountId:''});setAccounts(current=>({...current,[accountKey(target)]:[]}))}} options={[{value:'zernio',label:'Zernio'},{value:'publora',label:'Publora',disabled:target.platform!=='LinkedIn'||!!run.reviewDeliveries?.find(d=>d.platform===target.platform)?.cover,description:pt?'Este conector não envia capa de vídeo LinkedIn.':'This connector does not send LinkedIn video covers.'}]}/><button className="soft-button" disabled={busy||!!loading} onClick={()=>void load(target)}>{loading===target.platform?(pt?'Consultando…':'Checking…'):(pt?'Consultar contas':'Check accounts')}</button><SelectMenu ariaLabel={`Conta ${target.platform}`} value={target.accountId} disabled={busy||!!loading} onChange={accountId=>patch(target.platform,{accountId})} options={[{value:'',label:pt?'Escolher conta':'Choose account'},...(target.accountId&&!accounts[accountKey(target)]?[{value:target.accountId,label:target.accountId}]:[]),...(accounts[accountKey(target)]??[]).map(a=>({value:a.id,label:a.name}))]}/><PublicationNetworkSettings platform={target.platform as Platform} settings={target.networkSettings??{}} onChange={networkSettings=>patch(target.platform,{networkSettings})} disabled={busy||!!loading} mediaType="video" accountId={target.accountId}/></section>)}
  {error&&<p className="delivery-error" role="alert">{error}</p>}<Prerequisites items={missing}/><button className="primary-button" disabled={busy||!!loading||!accountsValid||!timeValid||!consentsValid} onClick={async()=>{setError('');setReviewed(null);try{const result=await act('prepare-schedule',{timeZone:zone,targets,...(date?{plannedAt:localTimeToInstant(date,zone)}:{text})});if(result?.scheduleHash)setReviewed({fingerprint,hash:result.scheduleHash})}catch(error){setError((error as Error).message)}}}>{pt?'Conferir agendamento':'Review schedule'}</button>
  {run.schedule&&<div className="production-confirmation"><strong>{pt?'Confira antes de autorizar':'Review before authorizing'}</strong><p>{zonedDateTime(run.schedule.plannedAt,run.schedule.timeZone).replace('T',' ')} · {run.schedule.timeZone}</p>{run.schedule.targets.map(t=><p key={t.platform}>{t.platform} · {t.provider} · {t.accountId}</p>)}<p>{pt?'Envia as versões aprovadas do vídeo, capas e legendas. O provedor publica no horário confirmado.':'Sends the approved video, covers and captions. The provider publishes at the confirmed time.'}</p>{run.schedule.targets.some(t=>t.platform==='TikTok')&&<p>{pt?'Dependendo da conexão TikTok, o Zernio incorpora a capa como um frame inicial do vídeo.':'Depending on the TikTok connection, Zernio incorporates the cover as an initial video frame.'}</p>}{reviewed?.fingerprint!==fingerprint&&<p className="editorial-hint">{pt?'Clique em Conferir agendamento para revisar estes dados antes de autorizar.':'Click Review schedule to review these details before authorizing.'}</p>}<button className="primary-button" disabled={busy||!accountsValid||!consentsValid||reviewed?.fingerprint!==fingerprint||!run.scheduleHash||reviewed?.hash!==run.scheduleHash} onClick={async()=>{const result=await act('schedule',{authorize:true,expectedHash:run.scheduleHash});if(result){clearStudioDraft(scope);setReviewed(null);setConfirmations({})}}}>{pt?'Autorizar agendamentos':'Authorize schedules'}</button></div>}
 </div>;
}

export function ProductionDialog({workspaceId,flowId,sessionId,agentId,initialText,onClose,onSelectAgent}:{workspaceId:string;flowId?:string;sessionId?:string;agentId?:string;initialText?:string;onClose:()=>void;onSelectAgent?:(id:string)=>void}){
 const production=useProduction(),editorial=useContentWorkflow(),chat=useChat(),{agents}=useAgents(),{locale}=useLanguage(),pt=locale==='pt-BR';
 const available=production.runs.filter(run=>run.workspaceId===workspaceId&&(!flowId||run.flowId===flowId));
 const flows=production.flows.flows.filter(f=>f.workspaceId===workspaceId),contextScope=startDraftScope(workspaceId,flowId??'',sessionId);
 const [selected,setSelected]=useStudioDraftField(contextScope,'run',available.find(run=>run.sourceSession.id===sessionId||run.editorSession.id===sessionId)?.id??''),[savedFlow,setChosenFlow]=useStudioDraftField(contextScope,'flow',flowId??flows.find(f=>f.nodes.some(n=>n.kind==='content-agent'&&n.agentId===agentId))?.id??flows[0]?.id??'');
 const chosenFlow=validSelection(savedFlow,flows),startScope=startDraftScope(workspaceId,chosenFlow,sessionId);
 const [savedTopic,setTopicId]=useStudioDraftField(startScope,'topic',''),[notionInput,setNotionInput]=useStudioDraftField(startScope,'notion-input','');
 const [destination,setDestination]=useState(''),[authorize,setAuthorize]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[resend,setResend]=useState(false),[editing,setEditing]=useState<PublicationDelivery>();
 const run=available.find(run=>run.id===selected),topics=editorial.state.topics.filter(topic=>topic.workspaceId===workspaceId&&['review','approved'].includes(topic.status)),topicId=validSelection(savedTopic,topics),content=editorial.state.contents.find(content=>content.id===run?.contentId&&content.workspaceId===workspaceId),assets=(editorial.state.assets??[]).filter(a=>a.contentId===run?.contentId&&a.workspaceId===workspaceId);
 const notesScope=runDraftScope(workspaceId,run?.id??'','notes'),videoScope=runDraftScope(workspaceId,run?.id??'','video'),platformScope=runDraftScope(workspaceId,run?.id??'','platforms');
 const [notes,setNotes]=useStudioDraftField(notesScope,'notes',''),[savedVideo,setSavedVideo]=useStudioDraftField(videoScope,'video',''),[savedFormat,setFormat]=useStudioDraftField(videoScope,'format','original'),[savedNetworks,setNetworks]=useStudioDraftField<string[]>(platformScope,'networks',run?.platforms??['Instagram','TikTok']);
 const sourceVideo=restoreVideo(savedVideo,assets),format=['original','portrait'].includes(savedFormat)?savedFormat:'original',networks=validNetworks(savedNetworks);
 const flow=flows.find(f=>f.id===chosenFlow),sourceId=flow?.nodes.find(n=>n.kind==='content-agent')?.agentId;
 const agentsValid=!!flow&&[sourceId,flow.nodes.find(n=>n.kind==='video-agent')?.agentId,flow.nodes.find(n=>n.kind==='publishing-agent')?.agentId??sourceId].every(id=>agents.some(a=>a.id===id&&a.workspaceId===workspaceId&&(a.providerId??'codex')==='codex'));
 const startMissing=[...(!chosenFlow?[{text:pt?'Escolha um fluxo.':'Choose a flow.',focus:'Fluxo da produção'}]:[]),...(!agentsValid?[{text:pt?'Configure agentes Codex de conteúdo, vídeo e publicação no Fluxo.':'Configure Codex content, video and publishing agents in Flow.',href:'#flow'}]:[]),...(!topicId?[{text:pt?'Escolha uma ideia estruturada atual.':'Choose a current structured idea.',focus:'Ideia da produção'}]:[]),...(!destination?[{text:pt?'Configure o destino Notion abaixo.':'Configure the Notion destination below.',focus:'Notion destination'}]:[]),...(!authorize?[{text:pt?'Revise a ideia e o destino e marque a autorização acima.':'Review the idea and destination, then check the authorization above.'}]:[])];
 const setSourceVideo=(id:string)=>{const asset=assets.find(a=>a.id===id);setSavedVideo(asset?videoDraftValue(asset):'')};
 useEffect(()=>{let live=true;setDestination('');void editorial.getNotionConnection(workspaceId).then(config=>{if(live)setDestination(config.autoSync?config.dataSourceId:'')}).catch(()=>{});return()=>{live=false}},[workspaceId,editorial.getNotionConnection]);
 useEffect(()=>{setAuthorize(false)},[workspaceId,selected,chosenFlow,JSON.stringify(flow),topicId,JSON.stringify(topics.find(t=>t.id===topicId)),destination]);
 useEffect(()=>{setResend(false);setError('');setEditing(undefined)},[workspaceId,selected,run?.reviewHash,run?.outputVideo?.versionId]);
 const configureNotion=async()=>{setBusy(true);setError('');try{await editorial.configureNotion(workspaceId,{dataSourceId:notionInput.trim().replace(/^collection:\/\//,''),autoSync:true});const configured=await editorial.getNotionConnection(workspaceId);setDestination(configured.dataSourceId);}catch(error){setError((error as Error).message)}finally{setBusy(false)}};
 const action=async(type:string,data:Record<string,unknown>={}):Promise<ProductionRun|undefined>=>{if(!run||busy)return;setBusy(true);setError('');try{const result=await production.command(run,type,data);if(['revise-video','revise-package'].includes(type))clearStudioDraft(notesScope);if(type==='video')clearStudioDraft(videoScope);if(type==='platforms')clearStudioDraft(platformScope);return result}catch(error){setError((error as Error).message)}finally{setBusy(false)}};
 const start=async()=>{if(busy)return;const topic=topics.find(t=>t.id===topicId);if(!topic)return;setBusy(true);setError('');try{const value=await production.start({flowId:chosenFlow,topicId,expectedTopic:topic,sourceSessionId:sessionId,notionDestination:destination,authorize,timeZone:'America/Sao_Paulo',language:locale});clearStudioDraft(startScope);setAuthorize(false);setSelected(value.id);}catch(error){setError((error as Error).message)}finally{setBusy(false)}};
 const captureIdeas=async()=>{const session=chat.sessions.find(s=>s.id===sessionId),message=session?.messages.filter(m=>m.type==='message'&&m.role==='agent'&&m.deliveryState==='completed'&&decodeChatDelivery(m.content)?.kind==='research').at(-1);if(message?.type!=='message'){setError(pt?'Peça ideias estruturadas ao agente ou faça uma pesquisa no Estúdio.':'Ask the agent for structured ideas or run research in Studio.');return;}setBusy(true);setError('');try{await editorial.captureChatDelivery(session!.id,message.id,message.content)}catch(error){setError((error as Error).message)}finally{setBusy(false)}};
 const openSession=(editor=false)=>{if(!run)return;const session=editor?run.editorSession:run.sourceSession;chat.openSession(session.agentId,session.id);onSelectAgent?.(session.agentId);onClose()};
 if(editing)return <PublicationEditor delivery={editing} onClose={()=>{setEditing(undefined);void production.refresh()}}/>;
 return <FlowDialog title={run?`${run.topic.title} · ${productionStageLabel(run.stage,pt)}`:(pt?'Produção semiautomática':'Semi-automatic production')} description={pt?'Chat e Fluxo acompanham a mesma produção. As aprovações ficam ligadas à versão apresentada.':'Chat and Flow follow the same production. Approvals apply to the displayed version.'} onClose={()=>{if(!busy)onClose()}}>
  <div className="production-panel-body" data-od-id="production-panel"><div className="production-section"><SelectMenu ariaLabel="Produção atual" value={run?.id??''} disabled={busy} onChange={id=>{setSelected(id);setError('')}} options={[{value:'',label:pt?'Nova produção a partir de uma ideia':'New production from an idea'},...available.map(run=>({value:run.id,label:run.topic.title,description:productionStageLabel(run.stage,pt)}))]}/></div>
   {!run?<div className="production-section"><label>{pt?'Fluxo':'Flow'}<SelectMenu ariaLabel="Fluxo da produção" value={chosenFlow} onChange={setChosenFlow} options={production.flows.flows.filter(f=>f.workspaceId===workspaceId).map(f=>({value:f.id,label:f.name}))}/></label><label>{pt?'Ideia para aprovar':'Idea to approve'}<SelectMenu ariaLabel="Ideia da produção" value={topicId} onChange={setTopicId} options={[{value:'',label:pt?'Escolher ideia estruturada':'Choose structured idea'},...topics.map(t=>({value:t.id,label:t.title,description:t.summary}))]}/></label>{sessionId&&<button className="soft-button" disabled={busy} onClick={()=>void captureIdeas()}>{pt?'Usar ideias desta conversa':'Use ideas from this chat'}</button>}{!topics.length&&<p>{pt?'Peça ideias ao agente e use “Usar ideias desta conversa”, ou crie uma pesquisa no Estúdio.':'Ask the agent for ideas and use “Use ideas from this chat”, or create research in Studio.'}</p>}<p>{pt?'Destino Notion autorizado':'Authorized Notion destination'}: {destination|| (pt?'Configure a base abaixo.':'Configure the database below.')}</p>{!destination&&<><label>{pt?'ID da base Notion (collection)':'Notion data source ID (collection)'}<input aria-label="Notion destination" value={notionInput} onChange={event=>setNotionInput(event.target.value)} placeholder="collection://…"/></label><button className="soft-button" disabled={busy||!notionInput.trim()} onClick={()=>void configureNotion()}>{pt?'Salvar destino Notion':'Save Notion destination'}</button></>}<label className="production-check"><input type="checkbox" checked={authorize} onChange={event=>setAuthorize(event.target.checked)}/>{pt?'Aprovo esta ideia e autorizo gerar o roteiro e criar/atualizar o card nesta base Notion.':'I approve this idea and authorize script generation and card creation/update in this Notion database.'}</label><Prerequisites items={startMissing} onNavigate={onClose}/><button className="primary-button" disabled={busy||!!startMissing.length} onClick={()=>void start()}>{pt?'Aprovar ideia e iniciar produção':'Approve idea and start production'}</button></div>:<>
    <ProductionProgress run={run} pt={pt}/><ProductionBudget key={run.id} run={run} pt={pt} busy={busy} act={action}/><div className="production-section production-stage"><strong>{productionStageLabel(run.stage,pt)}</strong><p>{run.name}</p><div className="production-chat-links"><button className="soft-button" onClick={()=>openSession()}>{pt?'Conversa do conteúdo':'Content chat'}</button><button className="soft-button" onClick={()=>openSession(true)}>{pt?'Conversa da edição':'Editing chat'}</button></div>{run.notion&&<a href={run.notion.url} target="_blank" rel="noopener noreferrer">{pt?'Abrir card do Notion':'Open Notion card'}</a>}{run.error&&<p className="delivery-error" role="alert">{run.error}</p>}</div>
    {run.stage==='recording'&&content&&<div className="production-section"><ContentAssetLibrary content={content}/><label>{pt?'Vídeo para editar':'Video to edit'}<SelectMenu ariaLabel="Vídeo da produção" value={sourceVideo} onChange={setSourceVideo} options={[{value:'',label:pt?'Escolher gravação':'Choose recording'},...assets.filter(a=>a.kind==='video'&&a.role==='source').map(a=>({value:a.id,label:a.name,disabled:a.status!=='available'}))]}/></label><label>{pt?'Formato autorizado':'Authorized format'}<SelectMenu ariaLabel="Formato da edição" value={format} onChange={setFormat} options={[{value:'original',label:pt?'Preservar enquadramento':'Keep framing'},{value:'portrait',label:pt?'Recortar para vertical 9:16':'Crop to vertical 9:16'}]}/></label><p>{pt?'O Editor propõe cortes, normalização de áudio e transições discretas; o executor local cria outro arquivo. Suas alterações no Notion entram no briefing.':'The editor plans cuts, audio normalization and subtle fades; the local executor creates a new file. Your Notion edits enter the briefing.'}</p>{!sourceVideo&&<Prerequisites items={[{text:pt?'Associe uma gravação disponível na biblioteca acima e escolha o vídeo.':'Attach an available recording in the library above and choose the video.',focus:'Vídeo da produção'}]}/>}<button className="primary-button" disabled={busy||!sourceVideo} onClick={()=>void action('video',{assetId:sourceVideo,format,authorize:true})}>{pt?'Enviar vídeo e iniciar edição básica':'Send video and start basic editing'}</button></div>}
    {run.stage==='video-review'&&run.outputVideo&&<div className="production-section"><button className="soft-button" onClick={()=>void window.mainsAgentsDesktop?.files?.open(storageProfile(),run.contentId,run.outputVideo!.assetId).catch(error=>setError(error.message))}>{pt?'Abrir vídeo editado':'Open edited video'}</button><p>{pt?'Revise esta versão antes de aprovar. O original continua salvo.':'Review this version before approval. The original remains saved.'}</p><button className="primary-button" disabled={busy} onClick={()=>void action('approve-video',{authorize:true,expectedVideo:run.outputVideo})}>{pt?'Aprovar este vídeo':'Approve this video'}</button><label>{pt?'Pedir ajuste':'Request revision'}<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label><button className="soft-button" disabled={busy||!notes.trim()} onClick={()=>void action('revise-video',{notes})}>{pt?'Enviar ajuste ao editor':'Send revision to editor'}</button></div>}
    {run.stage==='platforms'&&<div className="production-section"><h3>{pt?'Onde deseja publicar?':'Where would you like to publish?'}</h3>{['Instagram','TikTok','LinkedIn'].map(platform=><label className="production-check" key={platform}><input type="checkbox" checked={networks.includes(platform)} onChange={()=>setNetworks(current=>{const valid=validNetworks(current);return valid.includes(platform)?valid.filter(p=>p!==platform):[...valid,platform]})}/>{platform}</label>)}<p>{pt?'Vou gerar uma capa real e uma legenda por rede para sua revisão. Capas usam a ferramenta nativa do Codex; edição requer FFmpeg neste PC.':'I will generate a real cover and caption per network for review. Covers use the native Codex tool; editing requires FFmpeg on this PC.'}</p><button className="primary-button" disabled={busy||!networks.length} onClick={()=>void action('platforms',{platforms:networks})}>{pt?'Gerar capas e legendas':'Generate covers and captions'}</button></div>}
    {['package-review','schedule'].includes(run.stage)&&<div className="production-section"><h3>{pt?'Pacote por plataforma':'Per-platform package'}</h3>{run.reviewDeliveries?.map(delivery=><article className="production-package" key={delivery.id}><CoverPreview run={run} delivery={delivery}/><strong>{delivery.platform} · v{delivery.version}</strong><p>{delivery.text}</p><button className="text-link" onClick={()=>setEditing(delivery)}>{pt?'Editar esta entrega':'Edit this delivery'}</button></article>)}<button className="primary-button" disabled={busy||!run.reviewHash} onClick={()=>void action('approve-package',{authorize:true,expectedHash:run.reviewHash})}>{pt?'Aprovar vídeo, capas e legendas':'Approve video, covers and captions'}</button><label>{pt?'Pedir novas capas ou legendas':'Request new covers or captions'}<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label><button className="soft-button" disabled={busy||!notes.trim()} onClick={()=>void action('revise-package',{notes})}>{pt?'Gerar nova versão com ajustes':'Generate revised version'}</button></div>}
    {run.stage==='schedule'&&<ScheduleForm key={scheduleDraftScope(run)} run={run} initialText={initialText} act={action} busy={busy}/>}
    {['paused','blocked'].includes(run.stage)&&<div className="production-section"><p>{pt?'Retomar verifica o turno e os arquivos salvos antes de continuar. Um envio externo incerto deve ser consultado nas entregas.':'Resume checks saved turns and files before continuing. Uncertain external sends must be checked in deliveries.'}</p><label className="production-check"><input type="checkbox" checked={resend} onChange={event=>setResend(event.target.checked)}/>{pt?'Se necessário, autorizo reenviar a instrução de IA e consumir novos tokens.':'If needed, I authorize resending the AI instruction and consuming more tokens.'}</label><button className="primary-button" disabled={busy||run.imported} onClick={()=>void action('resume',{authorize:true,resend})}>{pt?'Retomar e verificar produção':'Resume and verify production'}</button>{run.imported&&<p>{pt?'Histórico importado não autoriza execução. Inicie uma nova produção com revisão da ideia e destino.':'Imported history does not authorize execution. Start a new production after reviewing the idea and destination.'}</p>}</div>}
    {['scheduling','complete','blocked'].includes(run.stage)&&content&&<ContentPublications content={content}/>}
    {run.step?.output&&!['recording','video-review','package-review','schedule','complete'].includes(run.stage)&&<details><summary>{pt?'Resposta da etapa':'Stage response'}</summary><pre className="production-output">{run.step.output}</pre></details>}
    <details className="production-section"><summary>{pt?'Histórico desta produção':'Production history'}</summary><ol>{run.events?.map((event,index)=><li key={index}>{new Date(event.at).toLocaleString(locale)} · {productionStageLabel(event.action,pt)}{event.detail&&<small>{event.detail}</small>}</li>)}</ol></details>
    {!['scheduling','complete','canceled'].includes(run.stage)&&<button className="text-link" disabled={busy} onClick={()=>void action('cancel')}>{pt?'Interromper próximas etapas':'Stop next stages'}</button>}
   </>}
   {error&&<p className="delivery-error" role="alert">{error}</p>}{production.error&&<p role="alert">{production.error}</p>}{busy&&<p role="status">{pt?'Salvando sua decisão…':'Saving your decision…'}</p>}
  </div>
 </FlowDialog>;
}
