import {productionStages} from './production-protocol.mjs';
import {sanitizeBudget} from './production-budget.mjs';
export function productionSnapshot(db,profile){return db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='production_runs'").get()?db.prepare('SELECT * FROM production_runs WHERE profile_id=? ORDER BY id').all(profile):[];}
export function restoreProductions(db,profile,rows=[],mode='replace'){
 if(!Array.isArray(rows))throw Error('Invalid production history backup.');
 if(!db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='production_runs'").get()){if(rows.length)throw Error('Production history storage is unavailable.');return;}
 if(mode==='replace'){db.prepare('DELETE FROM production_authority WHERE profile_id=?').run(profile);db.prepare('DELETE FROM production_commands WHERE profile_id=?').run(profile);db.prepare('DELETE FROM production_runs WHERE profile_id=?').run(profile);}
 for(const row of rows){if(!row||['id','workspace_id','content_id','data_json','updated_at'].some(k=>typeof row[k]!=='string')||!Number.isSafeInteger(row.revision)||row.revision<1)throw Error('Invalid production record.');const p=JSON.parse(row.data_json);if(p.id!==row.id||p.workspaceId!==row.workspace_id||p.contentId!==row.content_id||!productionStages.includes(p.stage)||!p.sourceAgent?.id||!p.editorAgent?.id||!Array.isArray(p.sourceSession?.messages)||!Array.isArray(p.editorSession?.messages))throw Error('Inconsistent production history.');const old=db.prepare('SELECT profile_id FROM production_runs WHERE id=?').get(row.id);if(old&&old.profile_id!==profile)throw Error('Production belongs to another profile.');p.profileId=profile;p.imported=true;if(p.scriptMode!==undefined&&p.scriptMode!=='local')delete p.scriptMode;for(const job of [p.covers?.render,p.captions?.transcription,p.captions?.render])if(job?.status==='running')Object.assign(job,{status:'interrupted',finishedAt:job.finishedAt??new Date().toISOString()});const budget=sanitizeBudget(p.budget);if(budget)p.budget=budget;else{delete p.budget;delete p.budgetStop;}if(!['complete','canceled'].includes(p.stage)){p.resumeStage=p.resumeStage??p.stage;p.stage='paused';p.error='Histórico importado sem autorizações. Inicie uma nova produção após revisar ideia e destino.';}db.prepare('INSERT OR IGNORE INTO production_runs VALUES(?,?,?,?,?,?,?)').run(p.id,profile,p.workspaceId,p.contentId,row.revision,JSON.stringify(p),row.updated_at);}
}
