import {useStudioDraftField,studioDraftKey} from '../../features/content/studioDrafts';
import {useState} from 'react';
import {useLanguage} from '../../app/LanguageProvider';
import {useContentWorkflow} from '../../features/content/ContentWorkflowProvider';
import type {EditorialArtifact,FileDelivery} from '../../features/content/model';
import {FlowDialog} from '../common/FlowDialog';
import {SelectMenu} from '../common/SelectMenu';
export function FileDeliveryReview({artifact,onClose,initialDecision='approve',initialNotes=''}:{artifact:EditorialArtifact;onClose:()=>void;initialDecision?:'approve'|'rejected'|'revision-requested';initialNotes?:string}){
 const {locale}=useLanguage(),pt=locale==='pt-BR', {state,reviewFiles}=useContentWorkflow();
 const scope=studioDraftKey('file-dialog',artifact.workspaceId,artifact.id,String(artifact.version),initialDecision,initialNotes.slice(0,100));
 const [decision,setDecision]=useStudioDraftField<'approved'|'rejected'|'revision-requested'>(scope,'decision',initialDecision==='approve'?'approved':initialDecision),[notes,setNotes]=useStudioDraftField<string>(scope,'notes',initialNotes),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const content=state.contents.find(item=>item.id===artifact.contentId),current=content?.fileDeliveryArtifactId===artifact.id;
 const submit=async()=>{if(busy)return;setBusy(true);setError('');try{await reviewFiles(artifact,decision,notes);onClose();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 return <FlowDialog title={pt?'Revisar arquivos':'Review files'} description={`${content?.title??''} · v${artifact.version}`} onClose={()=>{if(!busy)onClose()}}><div className="delivery-review-fields"><p>{(artifact.data as FileDelivery).summary}</p>{(artifact.data as FileDelivery).files.map(file=><p key={file.assetId}><b>{file.path.split(/[\\/]/).pop()}</b><small> SHA-256 {file.sha256.slice(0,12)}</small><br/>{file.caption}</p>)}<SelectMenu value={decision} ariaLabel={pt?'Decisão dos arquivos':'File decision'} onChange={value=>setDecision(value as typeof decision)} options={[{value:'approved',label:pt?'Aprovar':'Approve'},{value:'revision-requested',label:pt?'Pedir ajuste':'Request changes'},{value:'rejected',label:pt?'Rejeitar':'Reject'}]}/><label>{pt?'Observações':'Notes'}<textarea value={notes} onChange={event=>setNotes(event.target.value)}/></label><small>{pt?'A aprovação confere novamente os arquivos e vale somente para esta versão. Não autoriza publicação.':'Approval verifies files again and applies only to this version. It does not authorize publication.'}</small>{!current&&<p role="alert">{pt?'A entrega mudou. Abra a versão atual.':'The delivery changed. Open the current version.'}</p>}{error&&<p role="alert">{error}</p>}</div><footer className="delivery-review-footer"><button className="primary-button" disabled={busy||!current||decision==='revision-requested'&&!notes.trim()} onClick={()=>void submit()}>{busy?(pt?'Conferindo e salvando…':'Verifying and saving…'):(pt?'Confirmar decisão':'Confirm decision')}</button></footer></FlowDialog>;
}
