import {useState} from 'react';
import type {Agent} from '../../features/agents/model/Agent';
import type {AgentSession,ChatMessageItem} from '../../features/chat/model/Chat';
import type {EditorialArtifact,FileDelivery} from '../../features/content/model';
import {useContentWorkflow} from '../../features/content/ContentWorkflowProvider';
import {useLanguage} from '../../app/LanguageProvider';
import {storageProfile} from '../../data/IndexedDbStateStore';
import {useChat} from '../../features/chat/ChatProvider';
import {FlowDialog} from '../common/FlowDialog';
import {FileDeliveryReview} from './FileDeliveryReview';
import {SelectMenu} from '../common/SelectMenu';
export function FileDeliveryCard({agent,session,message,delivery}:{agent:Agent;session:AgentSession;message:ChatMessageItem;delivery:{summary:string;files:{path:string;caption:string}[]}}){
 const {locale}=useLanguage(),pt=locale==='pt-BR',native=window.mainsAgentsDesktop?.files;
 const {state,captureChatDelivery}=useContentWorkflow(),{sendMessage}=useChat();
 const [contentId,setContentId]=useState(session.contentId??''),[choose,setChoose]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<EditorialArtifact|null>(null);
 const artifact=state.artifacts.find(item=>item.type==='file-delivery'&&item.source?.sessionId===session.id&&item.source?.messageId===message.id);
 const content=state.contents.find(item=>item.id===artifact?.contentId),current=Boolean(artifact&&content?.fileDeliveryArtifactId===artifact.id&&(artifact.data as FileDelivery).files.every(ref=>state.assets?.some(asset=>asset.id===ref.assetId&&asset.currentVersionId===ref.versionId&&asset.status==='available'))),saved=artifact?.data as FileDelivery|undefined;
 const result=state.approvals.find(item=>item.artifactId===artifact?.id&&item.action==='file-review');
 async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <section className="chat-delivery" aria-label={pt?'Arquivos entregues':'Delivered files'}><header><b>{pt?'Arquivos entregues':'Delivered files'}</b><span>{artifact?`v${artifact.version}`:(pt?'A verificar':'Needs verification')}</span></header><p>{delivery.summary}</p><div className="delivery-preview">{(saved?.files??delivery.files).map((file,index)=>{
  const ref=saved?.files[index],asset=state.assets?.find(item=>item.id===ref?.assetId),valid=asset?.currentVersionId===ref?.versionId&&asset?.status==='available';
  return <article key={index}><b>{file.path.split(/[\\/]/).pop()}</b><p>{file.caption}</p>{ref&&<div className="delivery-actions"><button className="soft-button" disabled={busy||!native||!valid} onClick={()=>void run(async()=>{if(!artifact||!asset)return;if(['video','image','audio'].includes(asset.kind))await native?.open(storageProfile(),artifact.contentId!,asset.id);else await native?.reveal(storageProfile(),artifact.contentId!,asset.id);})}>{asset?.kind==='document'?(pt?'Mostrar arquivo':'Show file'):(pt?'Abrir mídia':'Open media')}</button><small>{valid?(pt?'Versão conferida ao abrir':'Version verified on open'):(pt?'Versão mudou ou foi removida':'Version changed or removed')}</small></div>}</article>;
 })}</div>{!artifact?<button className="soft-button" disabled={!native||busy} onClick={()=>setChoose(true)}>{pt?'Conferir e salvar entrega':'Verify and save delivery'}</button>:<div className="delivery-actions"><span>{!current?(pt?'Versão anterior':'Earlier version'):result?.decision==='approved'?(pt?'Aprovada':'Approved'):result?.decision==='rejected'?(pt?'Rejeitada':'Rejected'):result?.decision==='revision-requested'?(pt?'Ajuste solicitado':'Changes requested'):(pt?'Aguardando revisão':'Awaiting review')}</span><button className="soft-button" disabled={!current||busy} onClick={()=>{setReview(structuredClone(artifact));}}>{pt?'Revisar arquivos':'Review files'}</button><button className="text-link" onClick={()=>window.dispatchEvent(new CustomEvent('mainsagents:open-content',{detail:{contentId:artifact.contentId}}))}>{pt?'Abrir conteúdo':'Open content'}</button></div>}{error&&<p role="alert">{error}</p>}{result?.notes&&<p>{result.notes}</p>}
 {choose&&<FlowDialog title={pt?'Salvar arquivos da entrega':'Save delivered files'} description={pt?'Os arquivos serão lidos e verificados antes de associar ao conteúdo.':'Files are read and verified before linking to content.'} onClose={()=>{if(!busy)setChoose(false)}}><SelectMenu value={contentId} ariaLabel={pt?'Conteúdo da entrega':'Delivery content'} onChange={setContentId} options={[{value:'',label:pt?'Escolha o conteúdo':'Choose content'},...state.contents.filter(item=>item.workspaceId===agent.workspaceId).map(item=>({value:item.id,label:item.title}))]}/>{error&&<p role="alert">{error}</p>}<button className="primary-button" disabled={busy||!contentId} onClick={()=>void run(async()=>{await captureChatDelivery(session.id,message.id,message.content,contentId);setChoose(false);})}>{busy?(pt?'Conferindo…':'Verifying…'):(pt?'Salvar entrega':'Save delivery')}</button></FlowDialog>}
 {review&&<FileDeliveryReview artifact={review} onClose={()=>setReview(null)}/>}
 {current&&result?.decision==='revision-requested'&&<button className="soft-button" onClick={()=>sendMessage(agent,`${pt?'Ajuste a entrega de arquivos':'Revise the file delivery'} v${artifact?.version}: ${result.notes}\n${delivery.files.map(file=>file.path).join('\n')}\n${pt?'Produza arquivos novos sem sobrescrever os anteriores e devolva os caminhos reais.':'Produce new files without overwriting earlier versions and return real output paths.'}`,[],session.id)}>{pt?'Enviar ajuste ao agente':'Send changes to agent'}</button>}
 </section>;
}
