import {useEffect,useState} from 'react';
import {useLanguage} from '../../app/LanguageProvider';
import {storageProfile} from '../../data/IndexedDbStateStore';
interface Job {id:string;sourceSessionId:string;targetSessionId:string;title:string;status:string;error?:string;attempts:number;partialOutput?:string}
export function NativeDelegationWork({sessionId}:{sessionId:string}){
 const {locale}=useLanguage(),pt=locale==='pt-BR',[jobs,setJobs]=useState<Job[]>([]),[error,setError]=useState(''),[working,setWorking]=useState(''),[resend,setResend]=useState<Record<string,boolean>>({});
 useEffect(()=>{if(!window.mainsAgentsDesktop?.state)return;let active=true;const refresh=async()=>{try{const response=await fetch(`/api/content/delegations?profile=${encodeURIComponent(storageProfile())}`,{cache:'no-store'});if(!response.ok)return;const data=await response.json();if(active)setJobs((data.jobs??[]).filter((job:Job)=>[job.sourceSessionId,job.targetSessionId].includes(sessionId)));}catch{}};void refresh();const timer=setInterval(()=>void refresh(),1400);return()=>{active=false;clearInterval(timer);};},[sessionId]);
 async function act(job:Job,action:'retry'|'cancel'){setWorking(job.id);setError('');try{const response=await fetch(`/api/content/delegations/${encodeURIComponent(job.id)}/${action}?profile=${encodeURIComponent(storageProfile())}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({resend:!!resend[job.id]})});const data=await response.json();if(!response.ok)throw new Error(data.error);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setWorking('');}}
 const visible=jobs.filter(job=>job.status!=='completed');if(!visible.length&&!error)return null;
 return <section className="runtime-actions" aria-label={pt?'Trabalho entre agentes':'Agent work'}>{visible.map(job=><article className="runtime-action" key={job.id}><header><strong>{job.title}</strong><span>{['queued','running'].includes(job.status)?(pt?'Na fila local / trabalhando':'Queued locally / working'):(pt?'Precisa de atenção':'Needs attention')}</span></header>{job.error&&<p>{job.error}</p>}{job.partialOutput&&<details><summary>{pt?'Resposta parcial salva':'Saved partial response'}</summary><pre>{job.partialOutput}</pre></details>}{['error','interrupted'].includes(job.status)&&job.attempts<3&&<><label><input type="checkbox" checked={!!resend[job.id]} onChange={event=>setResend(current=>({...current,[job.id]:event.target.checked}))}/>{pt?'Conferi o histórico e autorizo enviar novamente se o resultado não puder ser recuperado.':'I checked the history and authorize another send if the result cannot be recovered.'}</label><footer><button className="soft-button" disabled={!!working} onClick={()=>void act(job,'retry')}>{pt?'Recuperar trabalho':'Recover work'}</button></footer></>}{['queued','running'].includes(job.status)&&<footer><button className="soft-button" disabled={!!working} onClick={()=>void act(job,'cancel')}>{pt?'Interromper':'Stop'}</button></footer>}</article>)}{error&&<p role="alert">{error}</p>}</section>;
}
