import {useState} from 'react';
import {useLanguage} from '../../app/LanguageProvider';
import {RuntimeActionApprovals} from './RuntimeActionApprovals';
import {SelectMenu} from '../common/SelectMenu';
import '../../styles/runtime-actions.css';
interface Diagnostics {checkedAt:string;runtime:string;account:string;modelCheck:string;models:{id:string;name:string}[];discovery:string;servers:{name:string;status:string;tools:string[];readEvidence?:{checkedAt:string;tool:string;agentId:string}[]}[];agents:{id:string;name:string;provider?:string;skills:{name:string;status:string;path?:string;mentions?:string[];dependencies?:{name:string;status:string;missingTools?:string[]}[]}[]}[]}
const ptLabels:Record<string,string>={running:'Em execução',connected:'Conectado',authenticated:'Autenticado','login-required':'Precisa de login','not-installed':'CLI não instalada',error:'Não foi possível verificar','check-failed':'Não foi possível verificar',completed:'Concluído',failed:'Falhou',disabled:'Desativado',unavailable:'Indisponível',discovered:'Ferramentas encontradas',empty:'Sem ferramentas','not-discovered':'Não foi encontrado',readable:'Arquivo legível',missing:'Caminho não encontrado',unreadable:'Não foi possível ler','too-large':'Arquivo muito grande','missing-tools':'Ferramentas necessárias ausentes','invalid-declaration':'Requisitos declarados inválidos','check-in-media-editor':'Verificar no editor de mídia','unsupported-provider':'MCP indisponível neste provedor',available:'Instalado'};
export function RuntimeDiagnostics(){
 const {locale}=useLanguage(),pt=locale==='pt-BR';
 const [media,setMedia]=useState<{ffmpeg:boolean;ffprobe:boolean}|null>(null);
 const [data,setData]=useState<Diagnostics|null>(null),[claude,setClaude]=useState<{state:string;message?:string}|null>(null),[working,setWorking]=useState(false),[error,setError]=useState(''),[testing,setTesting]=useState(false),[probeAgent,setProbeAgent]=useState(''),[notice,setNotice]=useState('');
 const label=(value:string)=>pt?ptLabels[value]??value:value.replaceAll('-',' ');
 async function get<T>(url:string):Promise<T>{const response=await fetch(url,{cache:'no-store'}),value=await response.json();if(!response.ok)throw new Error(value.error??'CLI unavailable');return value;}
 async function check(){setWorking(true);setError('');const results=await Promise.allSettled([get<Diagnostics>('/api/codex/diagnostics'),get<{state:string;message?:string}>('/api/providers/claude/diagnostics'),get<{ffmpeg:boolean;ffprobe:boolean}>('/api/content/media/capabilities')]);if(results[0].status==='fulfilled')setData(results[0].value);else setError(String(results[0].reason.message??results[0].reason));if(results[1].status==='fulfilled')setClaude(results[1].value);else setClaude({state:'check-failed'});setMedia(results[2].status==='fulfilled'?results[2].value:null);setWorking(false);}
 async function probe(){setTesting(true);setError('');setNotice('');try{const response=await fetch('/api/codex/diagnostics/read-test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({agentId:probeAgent,server:'zernio'})}),value=await response.json();if(!response.ok)throw new Error(value.error);setNotice(pt?'Leitura real confirmada. Nenhum turno de IA foi iniciado.':'Real read confirmed. No AI turn was started.');await check();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setTesting(false);}}
 return <section className="runtime-diagnostics"><header><strong>{pt?'Capacidades das CLIs e dos agentes':'CLI and agent capabilities'}</strong><button className="soft-button" disabled={working||testing} onClick={()=>void check()}>{working?(pt?'Verificando…':'Checking…'):(pt?'Verificar capacidades':'Check capabilities')}</button></header><small>{pt?'Confere autenticação, catálogo MCP e requisitos declarados das skills sem gerar respostas de IA.':'Checks authentication, MCP catalog and declared skill requirements without generating AI responses.'}</small>
 {error&&<p role="alert">{error}</p>}{claude&&<ul><li><strong>Claude Code CLI · {label(claude.state)}</strong><span>{claude.message}</span><small>{pt?'Usa o login da CLI. Somente pesquisa e leitura de arquivos; MCP, escrita e controle do computador bloqueados. Modelos são aliases do provedor; a disponibilidade depende da sua conta.':'Uses CLI login. Only research and file reads; MCP, writes and computer control are blocked. Models are provider aliases; availability depends on your account.'}</small></li></ul>}
 {data&&<><ul><li><strong>Codex CLI · {label(data.runtime)}</strong><span>{label(data.account)} · {data.models.length} {pt?'modelos disponíveis':'available models'} · {pt?'catálogo':'catalog'}: {label(data.modelCheck)}</span></li>{data.servers.map(server=><li key={server.name}><strong>{server.name} · {label(server.status)}</strong><span>{server.tools.length} {pt?'ferramentas · aprovação em cada chamada permitida':'tools · approval for every permitted call'}</span>{server.tools.length>0&&<details><summary>{pt?'Ver ferramentas':'View tools'}</summary>{server.tools.join(', ')}</details>}{server.readEvidence?.map((proof,index)=><small key={index}>{pt?'Última leitura confirmada':'Last confirmed read'}: {proof.tool} · {new Date(proof.checkedAt).toLocaleString(locale)} · {data.agents.find(agent=>agent.id===proof.agentId)?.name??proof.agentId}</small>)}</li>)}</ul>
 <small>{pt?'Catálogo não comprova acesso aos dados. Os recibos mostram leituras realmente concluídas, com data; não garantem que o acesso continue disponível.':'Catalog discovery does not prove data access. Receipts show actual completed reads and their date; they do not guarantee continued access.'}</small>
 {data.servers.some(server=>server.name==='zernio'&&server.status==='discovered'&&server.tools.includes('accounts_list'))&&<div className="runtime-action"><strong>{pt?'Testar acesso real ao Zernio':'Test real Zernio access'}</strong><p>{pt?'Consulta accounts_list, após sua aprovação abaixo. Sem inferência de IA, criação ou publicação.':'Calls accounts_list after your approval below. No AI inference, creation or publication.'}</p><SelectMenu value={probeAgent} onChange={setProbeAgent} ariaLabel={pt?'Agente do teste':'Test agent'} options={[{value:'',label:pt?'Escolha um agente Codex':'Choose a Codex agent'},...data.agents.filter(agent=>(agent.provider??'codex')==='codex').map(agent=>({value:agent.id,label:agent.name}))]}/><button className="soft-button" disabled={testing||!probeAgent} onClick={()=>void probe()}>{testing?(pt?'Aguardando decisão / consulta…':'Awaiting decision / read…'):(pt?'Preparar teste de leitura':'Prepare read test')}</button><RuntimeActionApprovals/>{notice&&<p role="status">{notice}</p>}</div>}
 <ul>{data.agents.map(agent=><li key={agent.id}><strong>{agent.name}</strong>{agent.skills.length?agent.skills.map(skill=><div key={skill.name}>{skill.name} · {label(skill.status)}{skill.dependencies?.length?skill.dependencies.map(requirement=><small key={requirement.name}>{requirement.name}: {label(requirement.status==='check-in-media-editor'&&media?(media[requirement.name as 'ffmpeg'|'ffprobe']?'available':'unavailable'):requirement.status)}{requirement.missingTools?.length?` (${requirement.missingTools.join(', ')})`:''}</small>):skill.mentions?.length?<small>{pt?'Menciona, sem declarar dependências':'Mentions without declaring dependencies'}: {skill.mentions.join(', ')}</small>:null}</div>):<span>{pt?'Sem skills associadas':'No associated skills'}</span>}</li>)}</ul><small>{pt?'Verificado em':'Checked at'} {new Date(data.checkedAt).toLocaleString(locale)}</small></>}
 <details><summary>{pt?'Histórico de aprovações do chat':'Chat approval history'}</summary><RuntimeActionApprovals history/></details></section>;
}
