import test from 'node:test';
import assert from 'node:assert/strict';
import {collectChatInbox,emptyChatInbox,seenChatSession} from '../src/features/chat/chatInbox.ts';
import {parseBackup,composeImport} from '../src/data/backupFormat.ts';
const session={id:'s',agentId:'a',title:'Task',createdAt:'2026-10-04',updatedAt:'2026-10-04',messages:[{id:'done',type:'message',role:'agent',content:'Actual result',createdAt:'2026-10-04',deliveryState:'completed'},{id:'partial',type:'message',role:'agent',content:'Streaming',createdAt:'2026-10-04',deliveryState:'streaming'}]};
const agents=[{id:'a',name:'Editor',workspaceId:'w'}];
test('Inbox excludes partial responses and foreign workspaces; reading a session only clears its current events',()=>{let state=emptyChatInbox();assert.equal(collectChatInbox([session],agents,state,'other').length,0);assert.equal(collectChatInbox([session],agents,state,'w').length,1);state=seenChatSession(state,session);assert.equal(collectChatInbox([session],agents,state,'w').length,0);const completed={...session,messages:session.messages.map(item=>({...item,deliveryState:'completed'}))};assert.equal(collectChatInbox([completed],agents,state,'w')[0].id,'message:partial');assert.equal(seenChatSession(state,session),state);});
test('Inbox keeps interrupted results, errors and failed handoffs actionable without counting a user message',()=>{const s={...session,messages:[{id:'err',type:'activity',label:'Login required',status:'error'},{...session.messages[0],deliveryState:'interrupted'},{id:'u',type:'message',role:'user',content:'Request'}],handoffs:[{id:'job',title:'Video',status:'interrupted',error:'Stopped',workspaceId:'w',updatedAt:'2026-10-04'}]};const result=collectChatInbox([s],agents,emptyChatInbox(),'w');assert.equal(result.length,3);assert(result.every(item=>item.kind==='blocked'));});
test('Inbox read state and notification choices survive backup, malformed receipts are refused',()=>{const data={'chat-inbox':{...seenChatSession(emptyChatInbox(),session),initialized:true,notified:['message:done']}};const file=parseBackup(JSON.stringify({format:'mainsagents-backup',version:1,data}));assert.deepEqual(composeImport({},file,'replace'),data);assert.throws(()=>parseBackup(JSON.stringify({...file,data:{'chat-inbox':{...data['chat-inbox'],seen:{s:[7]}}}})),/Invalid chat inbox/);});
