import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtempSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createFileDeliveries} from '../editorial-file-deliveries.mjs';
import {inspectLocalAsset} from '../editorial-local-files.mjs';
import {decodeChatDelivery} from '../chat-delivery-protocol.mjs';
function fixture(){const root=mkdtempSync(join(tmpdir(),'files-delivery-')),path=join(root,'result.txt');writeFileSync(path,'Real file output.');const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE editorial_state(profile_id TEXT PRIMARY KEY,revision INTEGER,state_json TEXT,updated_at TEXT)');db.prepare('INSERT INTO editorial_state VALUES (?,?,?,?)').run('owner',1,JSON.stringify({schemaVersion:1,topics:[{id:'t',workspaceId:'w'}],contents:[{id:'c',workspaceId:'w',topicId:'t',title:'Video',productionStage:'video-review'}],artifacts:[],runs:[],approvals:[]}),new Date().toISOString());let profile='owner';const message={id:'m',type:'message',role:'agent',deliveryState:'completed',content:JSON.stringify({kind:'files',summary:'Output ready for review',files:[{path,caption:'Real result'}]})};const sessions=[{id:'s',agentId:'a',messages:[message]}];const service=createFileDeliveries(db,{getCurrentProfile:()=>profile,getSessions:()=>sessions,getAgents:()=>[{id:'a',workspaceId:'w'}],inspect:path=>inspectLocalAsset(path,{stabilityMs:0})});const input=()=>({revision:db.prepare('SELECT revision FROM editorial_state').get().revision,sessionId:'s',messageId:'m',expectedContent:message.content,contentId:'c'});return {db,path,service,message,input,state:()=>JSON.parse(db.prepare('SELECT state_json FROM editorial_state').get().state_json),profile:value=>{profile=value;}};}
test('only an explicit file delivery with absolute local paths is recognized',()=>{assert.equal(decodeChatDelivery(JSON.stringify({kind:'files',summary:'No actual file',files:[{path:'https://example.com/video.mp4'}]})),null);assert.equal(decodeChatDelivery(JSON.stringify({kind:'files',summary:'No actual file',files:[{path:'relative.txt'}]})),null);});
test('capture verifies real bytes, links one content, and retries cannot duplicate artifacts or asset versions',async()=>{const f=fixture();try{const result=await f.service.capture('owner',f.input()),artifact=result.state.artifacts[0];assert.equal(artifact.type,'file-delivery');assert.equal(artifact.source.messageId,'m');assert.match(artifact.data.files[0].sha256,/^[0-9a-f]{64}$/);assert.equal(result.state.assets.length,1);assert.equal(result.state.approvals.length,0);const again=await f.service.capture('owner',f.input());assert.equal(again.revision,result.revision);assert.equal(again.state.artifacts.length,1);await assert.rejects(f.service.capture('owner',{...f.input(),contentId:'other'}));}finally{f.db.close();}});
test('approval records exact file version, revision feedback revokes readiness without deleting earlier decisions',async()=>{const f=fixture();try{let result=await f.service.capture('owner',f.input()),artifact=result.state.artifacts[0];const input={revision:result.revision,artifactId:artifact.id,expectedArtifact:artifact,decision:'approved',notes:'Reviewed output'};result=await f.service.review('owner',input);assert.equal(result.state.contents[0].productionStage,'ready');assert.equal(result.state.approvals[0].action,'file-review');result=await f.service.review('owner',{...input,revision:result.revision,decision:'revision-requested',notes:'Change the intro'});assert.equal(result.state.contents[0].productionStage,'video-review');assert.equal(result.state.approvals.length,2);assert.equal(result.state.approvals[1].decision,'approved');}finally{f.db.close();}});
test('missing or changed bytes, stale delivery, partial reply and foreign profile block capture/approval',async()=>{const f=fixture();try{f.message.deliveryState='streaming';await assert.rejects(f.service.capture('owner',f.input()),/completed/);f.message.deliveryState='completed';let result=await f.service.capture('owner',f.input()),artifact=result.state.artifacts[0];writeFileSync(f.path,'Different file bytes.');await assert.rejects(f.service.review('owner',{revision:result.revision,artifactId:artifact.id,expectedArtifact:artifact,decision:'approved'}),/missing or changed/);await assert.rejects(f.service.review('owner',{revision:result.revision,artifactId:artifact.id,expectedArtifact:{...artifact,version:99},decision:'rejected'}),/delivery changed/);assert.equal(f.state().approvals.length,0);f.profile('other');await assert.rejects(f.service.capture('owner',f.input()),/profile changed/);}finally{f.db.close();}});
