import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {startCodexBridge} from '../codex-bridge.mjs';import {createContentWorkflowBridge} from '../content-workflow-bridge.mjs';
test('official transport delegates locally without a frontend, gates the child MCP write and saves parent/child results',async()=>{
 const root=mkdtempSync(join(tmpdir(),'mains-native-runtime-')),cli=join(root,'fake-cli.mjs'),shared=join(root,'shared'),counter=join(root,'writes');mkdirSync(shared);
 writeFileSync(cli,`import{createInterface}from'node:readline';import{writeFileSync}from'node:fs';let serial=0,parent,child;const threads=new Map();const send=m=>process.stdout.write(JSON.stringify(m)+'\\n');const finish=(thread,turn,text)=>{turn.status='completed';turn.items.push({type:'agentMessage',text});thread.status={type:'idle'};send({method:'item/completed',params:{threadId:thread.id,turnId:turn.id,item:turn.items.at(-1)}});send({method:'turn/completed',params:{threadId:thread.id,turnId:turn.id,turn}})};createInterface({input:process.stdin}).on('line',line=>{const m=JSON.parse(line),p=m.params??{};if(m.id===900&&m.result){if(m.result.action==='accept'){writeFileSync(${JSON.stringify(counter)},'1');send({method:'item/completed',params:{threadId:child.thread.id,turnId:child.turn.id,item:{type:'mcpToolCall',server:'publora',tool:'publish',arguments:{text:'EXACT_REVIEWED'},result:{content:[]}}}});finish(child.thread,child.turn,'CHILD_CONFIRMED')}else finish(child.thread,child.turn,'CHILD_DENIED');return;}if(m.id===901&&m.result){finish(parent.thread,parent.turn,'PARENT_RECEIVED: '+m.result.contentItems[0].text);return;}if(m.id===undefined)return;let result={};if(m.method==='config/read')result={config:{mcp_servers:{publora:{url:'http://isolated',default_tools_approval_mode:'auto',tools:{publish:{approval_mode:'auto'}}}}}};if(m.method==='thread/start'){if(p.config.mcp_servers.publora.default_tools_approval_mode!=='prompt'||p.config.mcp_servers.publora.tools.publish.approval_mode!=='prompt')throw Error('Ungated MCP');const thread={id:'thread-'+(++serial),status:{type:'idle'},turns:[],instructions:p.developerInstructions};threads.set(thread.id,thread);result={thread};}if(m.method==='thread/resume'||m.method==='thread/read')result={thread:threads.get(p.threadId)};if(m.method==='turn/start'){const thread=threads.get(p.threadId),turn={id:'turn-'+(++serial),status:'inProgress',items:[{type:'userMessage',content:p.input}]};thread.turns.push(turn);thread.status={type:'active'};result={turn};if(thread.instructions.includes('You are Source')){parent={thread,turn};setTimeout(()=>send({id:901,method:'item/tool/call',params:{threadId:thread.id,turnId:turn.id,callId:'specialist-call',tool:'mainsagents_delegate',arguments:{targetAgentId:'target',title:'Briefing',instructions:'Produce the requested result.',files:[]}}}),10)}else{if(!thread.instructions.includes('TARGET_OWN_INSTRUCTIONS')||!thread.instructions.includes('C:/fixture/video-skill.md'))throw Error('Lost target identity');child={thread,turn};setTimeout(()=>send({id:900,method:'mcpServer/elicitation/request',params:{threadId:thread.id,turnId:turn.id,serverName:'publora',mode:'form',message:'Allow the publora MCP server to run tool "publish"?',_meta:{codex_approval_kind:'mcp_tool_call',tool_params:{text:'EXACT_REVIEWED'}},requestedSchema:{type:'object',properties:{}}}}),10)}}send({id:m.id,result})});`);
 const previous=process.env.MAINSAGENTS_CODEX_CLI_PATH;process.env.MAINSAGENTS_CODEX_CLI_PATH=cli;let bridge,content;
 const agents=[{id:'source',name:'Source',role:'Content',workspaceId:'space',tools:['subagents'],instructions:'Source instructions'},{id:'target',name:'Target',role:'Video',workspaceId:'space',tools:[],instructions:'TARGET_OWN_INSTRUCTIONS',skills:['video-skill'],skillFiles:{'video-skill':'C:/fixture/video-skill.md'}}],sessions=[{id:'session',agentId:'source',messages:[],title:'Source',createdAt:'2026',updatedAt:'2026'}];
 try{content=createContentWorkflowBridge({dbPath:join(root,'state.sqlite'),getCurrentProfile:()=> 'owner',getAgents:()=>agents,getSessions:()=>sessions,getChatRuntime:()=>bridge?.chatRuntime});bridge=await startCodexBridge({port:0,cwd:root,runtimeHome:join(root,'runtime'),sharedHome:shared,actions:content.actions,getBinding:content.binding,getAgents:content.agents,delegations:content.delegations});const base=`http://127.0.0.1:${bridge.port}`,headers={'x-mainsagents-bridge-token':bridge.token,'content-type':'application/json'};
 const connect=await fetch(base+'/api/codex/sessions',{method:'POST',headers,body:JSON.stringify({config:{localSessionId:'session'}})});assert.equal(connect.status,200);sessions[0].codexThreadId=(await connect.json()).threadId;
 const started=await (await fetch(base+'/api/codex/executions',{method:'POST',headers,body:JSON.stringify({threadId:sessions[0].codexThreadId,content:'Send the task to Target.'})})).json();assert(started.executionId);
 const deadline=Date.now()+5000;while(!content.actions.list('owner').length&&Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,5));const approval=content.actions.list('owner')[0];assert.equal(approval.status,'pending');assert.equal(approval.agentId,'target');assert.deepEqual(approval.arguments,{text:'EXACT_REVIEWED'});assert.throws(()=>readFileSync(counter));content.actions.decide('owner',approval.id,{hash:approval.hash,decision:'approve'});
 const stream=await (await fetch(base+`/api/codex/executions/${started.executionId}/events`,{headers})).text();assert(stream.includes('agent.delegation-queued'));assert(!stream.includes('"agent.delegate"'));assert(stream.includes('PARENT_RECEIVED: CHILD_CONFIRMED'));assert.equal(readFileSync(counter,'utf8'),'1');const saved=content.delegations.snapshot('owner');assert.equal(saved.jobs[0].status,'completed');assert(saved.sessions.some(session=>session.agentId==='target'&&session.messages.some(message=>message.content==='CHILD_CONFIRMED')));assert(saved.sessions.some(session=>session.agentId==='source'&&session.messages.some(message=>message.content==='PARENT_RECEIVED: CHILD_CONFIRMED')));assert.equal(content.actions.list('owner')[0].status,'succeeded');
 }finally{await content?.close();await bridge?.close();if(previous===undefined)delete process.env.MAINSAGENTS_CODEX_CLI_PATH;else process.env.MAINSAGENTS_CODEX_CLI_PATH=previous;}
});
