import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createNativeAgentDelegations} from '../native-agent-delegations.mjs';
import {mergeNativeDelegations} from '../src/features/chat/nativeDelegations.ts';
const source={id:'content',name:'Content',role:'Writer',workspaceId:'space',providerId:'codex',tools:['subagents','files'],instructions:'My workflow',skills:['source-skill']},target={...source,id:'video',name:'Video',instructions:'Own editing instructions',skills:['video-skill']};
const sourceSession={id:'source-session',agentId:'content',title:'Source',messages:[],createdAt:'2026',updatedAt:'2026',agentConnection:{enabled:true,targetAgentId:'video'}};
const binding={profileId:'owner',sessionId:sourceSession.id,agentId:source.id};
const params={threadId:'source-thread',turnId:'source-turn',callId:'call',arguments:{targetAgentId:'video',title:'Test task',instructions:'Reply with the exact result.',files:[]}};
const config={targets:[{id:'video'}]};
const manualInput={requestId:'12345678-1234-1234-1234-123456789abc',sourceAgentId:source.id,sourceSessionId:sourceSession.id,request:params.arguments,context:[{nodeId:'note',kind:'note',label:'Canvas note',content:'Keep this context'}]};
const wait=async predicate=>{for(let attempt=0;attempt<500;attempt++){if(predicate())return;await new Promise(resolve=>setTimeout(resolve,2));}throw new Error('Timed out waiting for native work');};
function fixture(db=new DatabaseSync(':memory:'),runtimeOverride){let calls=0;const connected=[],sessions=[structuredClone(sourceSession)],agents=[source,target],runtime={connect:async(session,agent)=>{connected.push({session,agent});return 'thread-'+session.id;},send:async()=>({executionId:'turn-'+(++calls)}),events:async function*(id){yield {type:'message.delta',delta:'PARTIAL'};yield {type:'message.completed',content:'SPECIALIST_RECEIVED'};yield {type:'execution.completed'};},readThread:async()=>({status:{type:'idle'},turns:[]}),cancel:async()=>{},...runtimeOverride};const service=createNativeAgentDelegations(db,{getCurrentProfile:()=> 'owner',getAgents:()=>agents,getSessions:()=>sessions,getRuntime:()=>runtime});return {db,service,connected,sessions,agents,calls:()=>calls};}
test('native delegation finishes without React, persists both sessions, reuses the connected chat and keeps target instructions/skills',async()=>{const f=fixture();try{assert.deepEqual(await f.service.dispatch(binding,params,config),{success:true,content:'SPECIALIST_RECEIVED'});const first=f.service.snapshot('owner');assert.equal(first.jobs[0].status,'completed');assert.equal(f.connected[0].agent.instructions,target.instructions);assert.deepEqual(f.connected[0].agent.skills,['video-skill']);assert.match(first.sessions.find(session=>session.agentId==='video').messages[0].content,/Task from Content/);const repeat=await f.service.dispatch(binding,params,config);assert.equal(repeat.success,true);assert.equal(f.calls(),1);await f.service.dispatch(binding,{...params,callId:'call-two'},config);assert.equal(f.service.snapshot('owner').jobs[1].targetSessionId,first.jobs[0].targetSessionId);assert.equal(f.calls(),2);}finally{await f.service.close();f.db.close();}});
test('foreign targets, cycles, configuration drift, missing files and unsupported providers cannot start inference',async()=>{const f=fixture();try{assert.throws(()=>f.service.dispatch(binding,{...params,arguments:{...params.arguments,targetAgentId:'content'}},config));f.agents[1]={...target,providerId:'gemini'};assert.throws(()=>f.service.dispatch(binding,params,config));f.agents[1]=target;const pending=f.service.dispatch(binding,params,config);f.agents[1]={...target,instructions:'Changed'};assert.equal((await pending).success,false);assert.equal(f.calls(),0);}finally{await f.service.close();f.db.close();}});
test('cancel persists intent, stops native work and ignores its late completion',async()=>{let release;const f=fixture(undefined,{events:async function*(id,signal){yield {type:'message.delta',delta:'saved partial'};await new Promise(resolve=>{release=resolve;signal.addEventListener('abort',resolve,{once:true});});yield {type:'message.completed',content:'LATE_SUCCESS'};yield {type:'execution.completed'};}});try{const pending=f.service.dispatch(binding,params,config);await wait(()=>f.service.snapshot('owner').jobs[0]?.partialOutput);const job=f.service.snapshot('owner').jobs[0];await f.service.cancel('owner',job.id);release();assert.equal((await pending).success,false);await wait(()=>f.service.snapshot('owner').jobs[0].status==='cancelled');assert.equal(f.service.snapshot('owner').jobs[0].result,undefined);}finally{await f.service.close();f.db.close();}});
test('reopening keeps partial messages and recovers a finished CLI turn without another send',async()=>{const db=new DatabaseSync(':memory:');const first=fixture(db,{events:async function*(id,signal){yield {type:'message.delta',delta:'retained'};await new Promise(resolve=>signal.addEventListener('abort',resolve,{once:true}));throw new Error('closed');}});const pending=first.service.dispatch(binding,params,config);await wait(()=>first.service.snapshot('owner').jobs[0]?.partialOutput);const id=first.service.snapshot('owner').jobs[0].id;await first.service.close();await pending;assert.equal(first.service.snapshot('owner').jobs[0].status,'interrupted');const second=fixture(db,{readThread:async()=>({status:{type:'idle'},turns:[{id:'turn-1',status:'completed',items:[{type:'agentMessage',text:'RECOVERED'}]}]})});try{second.service.retry('owner',id,{});await wait(()=>second.service.snapshot('owner').jobs[0].status==='completed');assert.equal(second.calls(),0);assert.equal(second.service.snapshot('owner').jobs[0].result,'RECOVERED');}finally{await second.service.close();db.close();}});
test('native session merge preserves user edits and other messages, links the same chats and never downgrades a completed response',()=>{const original=[{...sourceSession,agentConnection:{enabled:true,targetAgentId:'video'}},{id:'child',agentId:'video',title:'My title',modelId:'my-model',messages:[{id:'mine',type:'message',role:'user',content:'My later message'},{id:'codex-turn',type:'message',role:'agent',content:'FINAL',deliveryState:'completed'}],createdAt:'2026',updatedAt:'2027'}];const snapshot={sessions:[{...original[1],title:'Server title',modelId:'other',nativeMessageIds:['codex-turn'],messages:[{id:'codex-turn',type:'message',role:'agent',content:'PARTIAL',deliveryState:'streaming'}]}],handoffs:[{id:'job',sourceSessionId:sourceSession.id,sourceAgentId:'content',targetSessionId:'child',targetAgentId:'video',status:'completed'}],jobs:[]};const merged=mergeNativeDelegations(original,snapshot,['content','video']);assert.equal(merged[1].title,'My title');assert.equal(merged[1].modelId,'my-model');assert.equal(merged[1].messages[1].content,'FINAL');assert.equal(merged[1].messages.length,2);assert.equal(merged[0].agentConnection.targetSessionId,'child');assert.deepEqual(mergeNativeDelegations(merged,snapshot,['content','video']),merged);});
test('a lost turn-start receipt is reconciled by its unique marker without resending',async()=>{let sentText,sends=0;const f=fixture(undefined,{send:async(thread,text)=>{sends++;sentText=text;throw new Error('Lost receipt');},readThread:async()=>({status:{type:'idle'},turns:[{id:'lost-turn',status:'completed',items:[{type:'userMessage',content:[{type:'text',text:sentText}]},{type:'agentMessage',text:'RECOVERED_ONCE'}]}]})});try{assert.equal((await f.service.dispatch(binding,params,config)).success,false);const job=f.service.snapshot('owner').jobs[0];assert.equal(job.sending,true);f.service.retry('owner',job.id,{});await wait(()=>f.service.snapshot('owner').jobs[0].status==='completed');assert.equal(sends,1);assert.equal(f.service.snapshot('owner').jobs[0].result,'RECOVERED_ONCE');}finally{await f.service.close();f.db.close();}});
test('nested specialist calls have a separate bounded execution slot and cycles still cannot dispatch',async()=>{let f,childResult;const third={...target,id:'third',name:'Third'};f=fixture(undefined,{send:async(thread,content,agent)=>{if(agent.id==='video'){const child=f.service.snapshot('owner').sessions.find(session=>session.agentId==='video');assert.throws(()=>f.service.dispatch({profileId:'owner',sessionId:child.id,agentId:'video'},{...params,turnId:'nested',arguments:{...params.arguments,targetAgentId:'content'}},{targets:[{id:'content'}]}));childResult=f.service.dispatch({profileId:'owner',sessionId:child.id,agentId:'video'},{...params,threadId:thread,turnId:'nested',callId:'nested-call',arguments:{...params.arguments,targetAgentId:'third'}},{targets:[{id:'third'}]});return {executionId:'parent-child-turn'};}return {executionId:'grandchild-turn'};},events:async function*(id){if(id==='parent-child-turn')assert.equal((await childResult).success,true);yield {type:'message.completed',content:'NESTED_OK'};yield {type:'execution.completed'};}});f.agents.push(third);try{assert.equal((await f.service.dispatch(binding,params,config)).success,true);assert.equal(f.service.snapshot('owner').jobs.length,2);assert(f.service.snapshot('owner').jobs.every(job=>job.status==='completed'));}finally{await f.service.close();f.db.close();}});
test('a second local worker cannot interrupt or duplicate a running delegation',async()=>{let release;const first=fixture(undefined,{events:async function*(){yield {type:'message.delta',delta:'IN_PROGRESS'};await new Promise(resolve=>{release=resolve});yield {type:'message.completed',content:'ONE_RESULT'};yield {type:'execution.completed'};}});const pending=first.service.dispatch(binding,params,config);await wait(()=>first.service.snapshot('owner').jobs[0]?.partialOutput);const second=fixture(first.db);try{assert.equal(second.service.snapshot('owner').jobs[0].status,'running');second.service.kick();assert.equal(second.calls(),0);release();assert.equal((await pending).content,'ONE_RESULT');assert.equal(first.calls(),1);assert.equal(second.calls(),0);}finally{await second.service.close();await first.service.close();first.db.close();}});
test('manual handoffs use the durable queue, retain context, write the returned source message once and survive a lost receipt',async()=>{const f=fixture();try{const first=f.service.manual('owner',manualInput);assert.equal(first.manual,true);assert.equal(first.status,'queued');await wait(()=>f.service.snapshot('owner').jobs[0].status==='completed');const repeat=f.service.manual('owner',manualInput);assert.equal(repeat.id,first.id);assert.equal(f.calls(),1);const origin=f.service.snapshot('owner').sessions.find(session=>session.agentId===source.id);assert.equal(origin.messages.filter(message=>message.handoffId===first.id).length,1);const child=f.service.snapshot('owner').sessions.find(session=>session.agentId===target.id);assert.match(child.messages[0].content,/Keep this context/);assert.throws(()=>f.service.manual('owner',{...manualInput,request:{...manualInput.request,title:'Changed'}}),/request changed/);}finally{await f.service.close();f.db.close();}});
test('a Claude specialist keeps the CLI provider and remote session separate from Codex identifiers',async()=>{let options;const f=fixture(undefined,{send:async(thread,content,agent)=>{options=agent;return {executionId:'claude-turn'};}});f.agents[1]={...target,providerId:'claude'};try{const result=await f.service.dispatch(binding,params,config);assert.equal(result.success,true);const child=f.service.snapshot('owner').sessions.find(session=>session.agentId===target.id);assert.equal(child.providerId,'claude');assert.equal(child.codexThreadId,undefined);assert.equal(typeof child.remoteSessionId,'string');assert.equal(options.runtimeFirstMessage,true);assert.equal(options.instructions,target.instructions);}finally{await f.service.close();f.db.close();}});

test('a lost Claude send never retries inference without explicit resend confirmation',async()=>{
 let sends=0;const f=fixture(undefined,{send:async()=>{sends++;throw Error('Lost send receipt');},readThread:async()=>{throw Error('Must not attempt Codex reconciliation for Claude');}});f.agents[1]={...target,providerId:'claude'};
 try{assert.equal((await f.service.dispatch(binding,params,config)).success,false);const id=f.service.snapshot('owner').jobs[0].id;f.service.retry('owner',id,{});await wait(()=>f.service.snapshot('owner').jobs[0].status==='error');assert.equal(sends,1);assert.match(f.service.snapshot('owner').jobs[0].error,/not confirmed/);f.service.retry('owner',id,{resend:true});await wait(()=>f.service.snapshot('owner').jobs[0].status==='error');assert.equal(sends,2);}finally{await f.service.close();f.db.close();}
});
test('manual transfer from Claude preserves its configured role and is independent of the automatic connection switch',async()=>{
 const f=fixture();f.agents[0]={...source,providerId:'claude'};f.sessions[0].agentConnection.enabled=false;
 try{const job=f.service.manual('owner',manualInput);await wait(()=>f.service.snapshot('owner').jobs[0].status==='completed');assert.equal(f.calls(),1);assert.equal(f.service.snapshot('owner').jobs[0].id,job.id);assert.match(job.briefing,/My workflow|Reply with the exact result/);}finally{await f.service.close();f.db.close();}
});
