import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createContentWorkflowBridge} from '../content-workflow-bridge.mjs';
import {createChatImageArtifacts} from '../chat-image-artifacts.mjs';
import {createZernioPublicationConnector} from '../zernio-publication-connector.mjs';
import {runMediaProcess,probeVideo} from '../editorial-media.mjs';
import {inspectLocalAsset} from '../editorial-local-files.mjs';
import {createProductionFlow} from '../src/features/flows/flowModel.ts';
import {parseProductionSchedule,productionChatIntent,validateEditPlan} from '../production-protocol.mjs';
import {executionSnapshot,restoreExecution} from '../editorial-execution-backup.mjs';
const inspect=path=>inspectLocalAsset(path,{stabilityMs:0});
const scriptOptions={hooks:['A useful demo','Start here','This saves time'],ctas:['Save it','Try it'],paths:[{title:'Demo',outline:'Show the problem and demonstrate the practical solution.'},{title:'Story',outline:'Explain the example and how to apply it in daily work.'}],improvisationTopics:['Demo','Context'],thumbnailDirection:'Show a clear demo',draftScript:'A practical automation can save time in a repetitive task. Start with the problem, show the working example and explain how someone can apply this idea to their own daily routine.'};
async function until(check){const end=Date.now()+20000;while(Date.now()<end){if(check())return;await new Promise(resolve=>setTimeout(resolve,20));}throw Error('Production timed out');}
async function fixture(){
 const directory=mkdtempSync(join(tmpdir(),'production-coordinator-')),dbPath=join(directory,'state.sqlite'),input=join(directory,'recording.mp4'),png=join(directory,'tool.png');
 await runMediaProcess('ffmpeg',['-nostdin','-v','error','-n','-f','lavfi','-i','testsrc2=size=192x108:rate=24','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t','1.5','-c:v','libx264','-c:a','aac',input]);
 await runMediaProcess('ffmpeg',['-nostdin','-v','error','-n','-f','lavfi','-i','color=c=white:size=64x96','-frames:v','1',png]);
 const base={workspaceId:'space',instructions:'Keep my role and own skills',tools:['files'],skills:['own-skill'],providerId:'codex',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},agents=[{...base,id:'source',name:'Editor de Conteúdo',role:'Conteúdo'},{...base,id:'editor',name:'Editor de Vídeo',role:'Vídeo'}],flow=createProductionFlow('space','Content creation',agents),images=createChatImageArtifacts(join(directory,'images'));
 let serial=0,sends=0,creates=0,uploads=0,notionWrites=0,notes='Original note',held=false;const executions=new Map(),threads=new Map(),posts=new Map(),prompts=[];
 const runtime={createSession:async()=>{const id=`thread-${++serial}`;threads.set(id,{turns:[]});return id},resumeSession:async()=>{},readThread:async id=>threads.get(id),cancel:async()=>{},imageFile:image=>images.pathForImage(image),imageFromItem:(item,id)=>images.fromItem(item,id),send:async(thread,prompt,agent)=>{sends++;prompts.push({prompt,agent});const id=`execution-${++serial}`;let output,imageItem;if(prompt.includes('Retorne SOMENTE JSON: {"start"'))output=JSON.stringify({start:0,duration:1.5,format:'original',normalizeAudio:true,fadeSeconds:.15,summary:'Áudio normalizado e acabamento discreto'});else if(prompt.includes('Prepare legendas'))output=JSON.stringify({deliveries:['Instagram','TikTok'].map(platform=>({platform,caption:`Approved caption ${platform}`,coverPrompt:'A clear professional vertical cover'}))});else if(prompt.includes('Gere uma imagem de capa')){output='Imagem gerada';imageItem={id:`image-${id}`,type:'imageGeneration',status:'completed',result:readFileSync(png).toString('base64')}}else output=JSON.stringify(scriptOptions);executions.set(id,{thread,prompt,output,imageItem});return {executionId:id}},events:async function*(id,signal){if(held)await new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(Error('Interrupted')),{once:true}));const item=executions.get(id);yield {type:'message.completed',content:item.output};if(item.imageItem)yield images.fromItem(item.imageItem,id);threads.get(item.thread).turns.push({id,status:'completed',items:[{type:'userMessage',content:[{type:'text',text:item.prompt}]},{type:'agentMessage',text:item.output},...(item.imageItem?[item.imageItem]:[])]});yield {type:'execution.completed'}}};
 const fetchImpl=async(url,init={})=>{const u=new URL(url),path=u.pathname.split('/api/v1/')[1];if(init.method==='PUT'&&!path){for await(const chunk of init.body){}uploads++;return new Response('');}if(path==='accounts')return Response.json({accounts:[{_id:'ig',platform:'instagram',isActive:true,username:'IG'},{_id:'tt',platform:'tiktok',isActive:true,username:'TT'}]});if(path?.includes('creator-info'))return Response.json({privacyLevels:[{value:'PUBLIC_TO_EVERYONE',label:'Public'}],commercialContentTypes:[{value:'none',label:'None'}],postingLimits:{interactionSettings:{}}});if(path==='media/presign'){const n=++serial;return Response.json({uploadUrl:`https://media.zernio.com/upload/${n}`,publicUrl:`https://media.zernio.com/temp/${n}.jpg`});}if(path==='posts'&&init.method==='POST'){creates++;const body=JSON.parse(init.body),id=`post-${creates}`;posts.set(id,{...body,_id:id,status:body.isDraft?'draft':'scheduled',platforms:body.platforms.map(target=>({...target,status:body.isDraft?'draft':'scheduled'}))});return Response.json({post:posts.get(id)});}if(path?.startsWith('posts/'))return Response.json({post:posts.get(path.slice(6))});throw Error(`Unexpected endpoint ${url}`)};
 const options={dbPath,getCurrentProfile:()=> 'owner',getAgents:()=>agents,getFlows:()=>({flows:[flow]}),getSessions:()=>[],getRuntime:()=>runtime,inspect,mediaOptions:{inspect},getPublicationConnector:()=>createZernioPublicationConnector(()=> 'fixture-key',{fetchImpl}),getConnector:()=>({upsert:async(payload,ctx)=>{ctx.authorize();notionWrites++;ctx.saveCheckpoint({phase:'verified',pageId:'12345678-1234-1234-1234-123456789abc'});return {pageId:'12345678-1234-1234-1234-123456789abc',url:'https://www.notion.so/12345678123412341234123456789abc',artifactVersion:payload.artifact.version,verifiedAt:new Date().toISOString()}},readCard:async()=>({text:notes,fetchedAt:new Date().toISOString()})})};
 let bridge=createContentWorkflowBridge(options);const db=new DatabaseSync(dbPath),at=new Date().toISOString(),file=await inspect(input),topic={id:'topic',workspaceId:'space',requestId:'idea',inputKind:'text',input:'A useful automation idea',priority:'normal',status:'review',title:'An automation project',category:'Tech',summary:'A practical project for saving time.',whyItMatters:'It solves a repetitive daily problem.',angles:['Demo','Explain'],sources:[{title:'Reference',url:'https://example.com'}],factualQuestions:[],createdAt:at,updatedAt:at};
 db.prepare('INSERT INTO editorial_state VALUES(?,?,?,?)').run('owner',1,JSON.stringify({schemaVersion:1,topics:[topic],contents:[],artifacts:[],approvals:[],runs:[],assets:[],publications:[]}),at);bridge.jobs.configure('owner','space',{dataSourceId:'12345678-1234-1234-1234-123456789abc',autoSync:true});
 const start=()=>bridge.production.start('owner',{requestId:'start',flowId:flow.id,topicId:topic.id,expectedTopic:topic,notionDestination:bridge.jobs.connection('owner','space').dataSourceId,authorize:true});
 const current=()=>JSON.parse(db.prepare('SELECT state_json FROM editorial_state').get().state_json),run=id=>bridge.production.list('owner').find(p=>p.id===id);
 const command=(id,action,data={})=>bridge.production.command('owner',{id,revision:run(id).revision,requestId:`command-${++serial}`,action,...data});
 const attach=id=>{const p=run(id),state=current(),version={id:'original-v1',path:file.path,name:file.name,size:file.size,sha256:file.sha256,modifiedAt:file.modifiedAt,createdAt:at};state.assets.push({id:'original',workspaceId:'space',contentId:p.contentId,kind:'video',role:'source',status:'available',name:file.name,currentVersionId:version.id,versions:[version],createdAt:at,updatedAt:at});db.prepare('UPDATE editorial_state SET state_json=?,revision=revision+1').run(JSON.stringify(state));};
 return {directory,dbPath,input,file,db,flow,topic,start,run,command,attach,current,prompts,counts:()=>({sends,creates,uploads,notionWrites}),notes:value=>notes=value,hold:value=>held=value,completeSavedTurn:id=>{const step=run(id).step,item=executions.get(step.executionId);threads.get(step.threadId).turns.push({id:step.executionId,status:'completed',items:[{type:'userMessage',content:[{type:'text',text:item.prompt}]},{type:'agentMessage',text:item.output}]})},get bridge(){return bridge},reopen:async()=>{await bridge.close();bridge=createContentWorkflowBridge(options)},close:async()=>{await bridge.close();db.close()}};
}
test('semi-automatic production produces real edited video and covers, waits for approvals, rereads Notion and schedules each exact package once',async()=>{
 const f=await fixture();try{const p=f.start();assert.equal(f.start().id,p.id);await until(()=>['recording','blocked'].includes(f.run(p.id).stage));assert.equal(f.run(p.id).stage,'recording',f.run(p.id).error);assert.equal(f.counts().notionWrites,1);assert.equal(f.counts().creates,0);f.notes('NOTION_USER_EDIT');f.attach(p.id);await f.command(p.id,'video',{assetId:'original',format:'original',authorize:true});await until(()=>['video-review','blocked'].includes(f.run(p.id).stage));assert.equal(f.run(p.id).stage,'video-review',f.run(p.id).error);assert(f.prompts.some(x=>x.agent.id==='editor'&&x.prompt.includes('NOTION_USER_EDIT')));assert.equal(readFileSync(f.input).length,f.file.size);assert.equal(f.counts().creates,0);const video=f.run(p.id).outputVideo;assert.notEqual(video.sha256,f.file.sha256);await f.command(p.id,'approve-video',{authorize:true,expectedVideo:video});await f.command(p.id,'platforms',{platforms:['Instagram','TikTok']});await until(()=>['package-review','blocked'].includes(f.run(p.id).stage));assert.equal(f.run(p.id).stage,'package-review',f.run(p.id).error);assert.equal(f.counts().creates,0);assert(f.run(p.id).reviewDeliveries.every(d=>d.cover&&d.media.length===1));await f.command(p.id,'approve-package',{authorize:true,expectedHash:f.run(p.id).reviewHash});await f.command(p.id,'prepare-schedule',{text:'agende amanhã às 18h',timeZone:'America/Sao_Paulo',targets:[{platform:'Instagram',provider:'zernio',accountId:'ig'},{platform:'TikTok',provider:'zernio',accountId:'tt',networkSettings:{tiktokSettings:{privacy_level:'PUBLIC_TO_EVERYONE',commercialContentType:'none',allow_comment:false,allow_duet:false,allow_stitch:false,content_preview_confirmed:true,express_consent_given:true,video_made_with_ai:false}}}]});assert.equal(f.counts().creates,0);await f.command(p.id,'schedule',{authorize:true,expectedHash:f.run(p.id).scheduleHash});await until(()=>['complete','blocked'].includes(f.run(p.id).stage));assert.equal(f.run(p.id).stage,'complete',f.run(p.id).error);assert.equal(f.counts().creates,2);assert.equal(f.counts().uploads,4);const before=f.counts();await f.reopen();await new Promise(resolve=>setTimeout(resolve,850));assert.deepEqual(f.counts(),before);assert(f.current().publications.every(d=>d.receipt&&d.status==='scheduled'));}finally{await f.close()}
});
test('restart pauses uncertain inference, profile/config changes block work and imported productions never inherit authorization',async()=>{
 const f=await fixture();try{f.hold(true);const p=f.start();await until(()=>f.run(p.id).step?.phase==='streaming');await f.reopen();assert.equal(f.run(p.id).stage,'paused');await f.command(p.id,'resume',{authorize:true});await until(()=>f.run(p.id).stage==='blocked');assert.equal(f.counts().sends,1);const backup=executionSnapshot(f.db,'owner');restoreExecution(f.db,'owner',backup,'replace');assert.equal(f.run(p.id).imported,true);await assert.rejects(()=>f.command(p.id,'resume',{authorize:true}),/Backup restaura histórico/);}finally{await f.close()}
});
test('a completed saved turn recovers without another inference or duplicate Notion card',async()=>{const f=await fixture();try{f.hold(true);const p=f.start();await until(()=>f.run(p.id).step?.phase==='streaming');f.completeSavedTurn(p.id);await f.reopen();f.hold(false);await f.command(p.id,'resume',{authorize:true});await until(()=>['recording','blocked'].includes(f.run(p.id).stage));assert.equal(f.run(p.id).stage,'recording',f.run(p.id).error);assert.equal(f.counts().sends,1);assert.equal(f.counts().notionWrites,1);}finally{await f.close()}});
test('chat schedule compiler uses São Paulo dates, rejects missing dates/past times and the video planner cannot invent shell operations',()=>{
 const now=new Date('2026-10-05T23:00:00Z');assert.equal(parseProductionSchedule('agende amanhã às 18h','America/Sao_Paulo',now).plannedAt,'2026-10-06T21:00:00.000Z');assert.equal(parseProductionSchedule('agende às 18h','America/Sao_Paulo',now),null);assert.throws(()=>parseProductionSchedule('hoje às 18h','America/Sao_Paulo',now),/futuro/);assert.equal(productionChatIntent('aprovo este vídeo').type,'video');assert.equal(productionChatIntent('agende amanhã às 18h').type,'schedule');assert.throws(()=>validateEditPlan({start:0,duration:5,format:'portrait',normalizeAudio:true,fadeSeconds:.1},{duration:5},{format:'original'}),/recortar/);
});
test('AI call cap pauses before any extra dispatch and continues only after a reviewed, valid limit increase',async()=>{
 const f=await fixture();try{const p=f.bridge.production.start('owner',{requestId:'start-capped',flowId:f.flow.id,topicId:f.topic.id,expectedTopic:f.topic,notionDestination:f.bridge.jobs.connection('owner','space').dataSourceId,authorize:true,budget:{maxCalls:1,maxAttemptsPerStep:2}});
  assert.deepEqual([p.budget.maxCalls,p.budget.maxAttemptsPerStep,p.budget.legacy],[1,2,false]);
  await until(()=>['recording','blocked'].includes(f.run(p.id).stage));assert.equal(f.run(p.id).stage,'recording',f.run(p.id).error);assert.deepEqual(f.run(p.id).budget.calls.map(c=>c.status),['completed']);
  f.attach(p.id);await f.command(p.id,'video',{assetId:'original',format:'original',authorize:true});await until(()=>f.run(p.id).stage==='paused');
  let run=f.run(p.id);assert.equal(f.counts().sends,1,'no dispatch beyond the cap');assert.equal(run.budgetStop.kind,'calls');assert.equal(run.resumeStage,'planning-edit');assert.match(run.error,/Limite de chamadas de IA.*\(1\/1\).*Nada foi enviado/);
  await assert.rejects(()=>f.command(p.id,'resume',{authorize:true}),/limite revisado/);
  for(const limits of [{maxCalls:0,maxAttemptsPerStep:2},{maxCalls:41,maxAttemptsPerStep:2},{maxCalls:2.5,maxAttemptsPerStep:2},{maxCalls:3,maxAttemptsPerStep:6},{maxCalls:'3',maxAttemptsPerStep:2}])await assert.rejects(()=>f.command(p.id,'adjust-budget',{authorize:true,reviewedCalls:1,limits}),/Escolha de/);
  await assert.rejects(()=>f.command(p.id,'adjust-budget',{authorize:true,reviewedCalls:0,limits:{maxCalls:3,maxAttemptsPerStep:2}}),/uso mudou/);
  await assert.rejects(()=>f.command(p.id,'adjust-budget',{reviewedCalls:1,limits:{maxCalls:3,maxAttemptsPerStep:2}}),/após revisar/);
  await f.command(p.id,'adjust-budget',{authorize:true,reviewedCalls:1,limits:{maxCalls:3,maxAttemptsPerStep:2}});assert.equal(f.run(p.id).stage,'paused','raising a limit never resumes automatically');assert.equal(f.counts().sends,1);
  assert.match(f.run(p.id).events.find(e=>e.action==='budget-limits').detail,/Chamadas 1→3/);
  await f.command(p.id,'resume',{authorize:true});await until(()=>['video-review','blocked','paused'].includes(f.run(p.id).stage));run=f.run(p.id);assert.equal(run.stage,'video-review',run.error);assert.equal(f.counts().sends,2);assert.equal(run.budget.calls.length,2);assert.equal(run.budgetStop,undefined);
 }finally{await f.close()}
});
test('uncertain sends survive restart, count conservatively and stop at the per-step attempt limit',async()=>{
 const f=await fixture();try{f.hold(true);const p=f.start();await until(()=>f.run(p.id).step?.phase==='streaming');assert.equal(f.run(p.id).budget.calls[0].status,'sent');
  await f.reopen();assert.equal(f.run(p.id).stage,'paused');
  await f.command(p.id,'resume',{authorize:true});await until(()=>f.run(p.id).stage==='blocked');let run=f.run(p.id);assert.equal(run.budget.calls[0].status,'uncertain');assert.equal(f.counts().sends,1);
  await f.command(p.id,'resume',{authorize:true,resend:true});await until(()=>f.run(p.id).step?.attempt===2&&f.run(p.id).step?.phase==='streaming');assert.equal(f.counts().sends,2);
  await f.reopen();await f.command(p.id,'resume',{authorize:true,resend:true});await until(()=>f.run(p.id).budgetStop);run=f.run(p.id);
  assert.equal(run.stage,'paused');assert.equal(run.budgetStop.kind,'attempts');assert.equal(f.counts().sends,2,'resend authorization cannot exceed the attempt limit');assert.deepEqual(run.budget.calls.map(c=>c.status),['uncertain','uncertain']);
  await f.reopen();assert.equal(f.run(p.id).budget.calls.length,2,'restart neither resets nor refunds reservations');
 }finally{await f.close()}
});
