import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createRuntimeActionApprovals} from '../runtime-action-approvals.mjs';
import {chatActionConfig} from '../codex-action-policy.mjs';
const binding={profileId:'owner',sessionId:'session',agentId:'editor',agentName:'Editor',workspaceId:'content',hash:'config-version'};
const message={id:9,method:'mcpServer/elicitation/request',params:{threadId:'thread',turnId:'turn',serverName:'publora',mode:'form',message:'Allow the publora MCP server to run tool "publish"?',_meta:{codex_approval_kind:'mcp_tool_call',tool_params:{text:'Reviewed text',network:'linkedin'}},requestedSchema:{type:'object',properties:{}}}};
function fixture(){const db=new DatabaseSync(':memory:');let current=binding;const replies=[];const service=createRuntimeActionApprovals(db,{getCurrentProfile:()=> 'owner',getBinding:()=>current});return {db,service,replies,change:()=>{current={...binding,hash:'changed'}},receive:(m=message)=>service.receive(m,binding,value=>replies.push(value))};}
test('each exact MCP call waits for one explicit decision; stale data, wrong profile and duplicate approval cannot grant permission',()=>{
 const f=fixture();try{const id=f.receive(),row=f.service.list('owner')[0];assert.equal(row.status,'pending');assert.equal(f.replies.length,0);assert.throws(()=>f.service.decide('other',id,{hash:row.hash,decision:'approve'}));assert.throws(()=>f.service.decide('owner',id,{hash:'changed',decision:'approve'}));assert.equal(f.replies.length,0);f.service.decide('owner',id,{hash:row.hash,decision:'approve'});assert.deepEqual(f.replies,[{action:'accept',content:{}}]);assert.throws(()=>f.service.decide('owner',id,{hash:row.hash,decision:'approve'}));assert.equal(f.replies.length,1);f.service.observe({method:'item/completed',params:{threadId:'thread',turnId:'turn',item:{type:'mcpToolCall',server:'publora',tool:'publish',arguments:message.params._meta.tool_params,result:{content:[]}}}});assert.equal(f.service.list('owner')[0].status,'succeeded');}finally{f.service.close();f.db.close();}
});
test('agent changes, cancel and malformed or secret forms fail closed',()=>{const f=fixture();try{const id=f.receive(),row=f.service.list('owner')[0];f.change();assert.throws(()=>f.service.decide('owner',id,{hash:row.hash,decision:'approve'}));assert.equal(f.replies[0].action,'decline');assert.equal(f.service.list('owner')[0].status,'interrupted');f.receive({...message,id:10,params:{...message.params,_meta:{...message.params._meta,tool_params:{api_key:'secret'}}}});assert.equal(f.service.list('owner').length,1);assert.equal(f.replies.at(-1).action,'decline');}finally{f.service.close();f.db.close();}});
test('approval is distinct from execution and an interrupted grant is never reported as a successful write',()=>{const f=fixture();try{const id=f.receive(),row=f.service.list('owner')[0];f.service.decide('owner',id,{hash:row.hash,decision:'approve'});assert.equal(f.service.list('owner')[0].status,'approved');f.service.interrupt('turn');assert.equal(f.service.list('owner')[0].status,'interrupted');}finally{f.service.close();f.db.close();}});
test('thread-only policy overrides automatic MCP grants, disables unreviewable app/plugin routes and strips null config',async()=>{const original={mcp_servers:{publora:{url:'http://local',default_tools_approval_mode:'auto',tools:{publish:{approval_mode:'auto'}},env:null}},features:{apps:true}};const copy=structuredClone(original);const config=await chatActionConfig({request:async()=>({config:original})});assert.equal(config.mcp_servers.publora.default_tools_approval_mode,'prompt');assert.equal(config.mcp_servers.publora.tools.publish.approval_mode,'prompt');assert.equal(config.mcp_servers.publora.env,undefined);assert.equal(config.features.apps,false);assert.deepEqual(original,copy);});
