import {PublicationNetworkSettings} from './PublicationNetworkSettings';
import {useStudioDraftField,studioDraftKey} from '../../features/content/studioDrafts';
import {useEffect,useState} from 'react';
import {useContentWorkflow} from '../../features/content/ContentWorkflowProvider';
import {useLanguage} from '../../app/LanguageProvider';
import type {EditorialContent,PublicationDelivery,PublicationStatus,Platform} from '../../features/content/model';
import {publicationPlatforms} from '../../../publication-model.mjs';
import {localTimeToInstant,zonedDateTime} from '../../../publication-time.mjs';
import {SelectMenu} from '../common/SelectMenu';
import {FlowDialog} from '../common/FlowDialog';
import './content-publications.css';


const labels:Record<PublicationStatus,[string,string]>={draft:['Rascunho','Draft'],'in-review':['Em revisão','In review'],approved:['Aprovado para envio','Approved to send'],sending:['Envio pendente','Sending'],scheduled:['Agendamento confirmado','Schedule confirmed'],published:['Publicado','Published'],failed:['Falha','Failed']};
export const publicationLabel=(status:PublicationStatus,pt:boolean)=>labels[status][pt?0:1];
const defaultZone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Sao_Paulo';
const zones=['America/Sao_Paulo','America/Manaus','America/Recife','America/New_York','Europe/Lisbon','UTC'];

export function ContentPublications({content}:{content:EditorialContent}){
  const {state,publicationCommand}=useContentWorkflow(),{locale}=useLanguage(),pt=locale==='pt-BR';
  const [editing,setEditing]=useState<PublicationDelivery|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const deliveries=(state.publications??[]).filter(item=>item.contentId===content.id&&item.workspaceId===content.workspaceId);
  const add=async(platform:Platform)=>{setBusy(true);setError('');try{const timeZone=defaultZone();await publicationCommand({action:'create',contentId:content.id,platform,draft:{text:'',assetIds:[],timeZone}})}catch(failure){setError(String((failure as Error).message))}finally{setBusy(false)}};
  return <section className="editorial-card content-publications" aria-label={pt?'Entregas por rede':'Network deliveries'}>
    <div className="editorial-section-head"><div><h2>{pt?'Entregas por rede':'Network deliveries'}</h2><p className="editorial-hint">{pt?'Revise texto, arquivos e horário de cada rede. Um horário planejado ainda não é um agendamento.':'Review text, files and time for each network. A planned time is not a confirmed schedule.'}</p></div><button type="button" className="text-link" onClick={()=>window.dispatchEvent(new CustomEvent('mainsagents:publication-calendar'))}>{pt?'Ver calendário':'View calendar'}</button></div>
    <div className="publication-rows">{deliveries.map(item=><button type="button" className="publication-row" key={item.id} onClick={()=>setEditing(structuredClone(item))}><b>{item.platform}</b><span>{publicationLabel(item.status,pt)}<small>v{item.version}{item.plannedAt?` · ${pt?'Planejado':'Planned'}: ${new Date(item.plannedAt).toLocaleString(locale,{timeZone:item.timeZone})} (${item.timeZone})`:''}</small></span><span>{pt?'Abrir':'Open'}</span></button>)}</div>
    <div className="editorial-actions">{publicationPlatforms.filter(platform=>!deliveries.some(item=>item.platform===platform)).map(platform=><button type="button" className="soft-button" key={platform} disabled={busy} onClick={()=>void add(platform as Platform)}>+ {platform}</button>)}</div>
    {error&&<p className="delivery-error" role="alert">{error}</p>}
    {editing&&<PublicationEditor delivery={editing} onClose={()=>setEditing(null)}/>}
  </section>;
}

export function PublicationEditor({delivery,onClose}:{delivery:PublicationDelivery;onClose:()=>void}){
  const {state,publicationCommand}=useContentWorkflow(),{locale}=useLanguage(),pt=locale==='pt-BR';
  const [snapshot,setSnapshot]=useState(delivery);
  const scope=studioDraftKey('publication',delivery.workspaceId,snapshot.id,String(snapshot.version),snapshot.operation?.id??'local');
  const [text,setText]=useStudioDraftField<string>(scope,'text',snapshot.text),[timeZone,setTimeZone]=useStudioDraftField<string>(scope,'zone',snapshot.timeZone);
  const [planned,setPlanned]=useStudioDraftField<string>(scope,'planned',zonedDateTime(snapshot.plannedAt,snapshot.timeZone)),[selected,setSelected]=useStudioDraftField<string[]>(scope,'files',snapshot.media.map(item=>item.assetId));
  const [networkSettings,setNetworkSettings]=useStudioDraftField<NonNullable<PublicationDelivery['networkSettings']>>(scope,'network-settings',snapshot.networkSettings??{});
  const [coverAssetId,setCoverAssetId]=useStudioDraftField<string>(scope,'cover-asset',snapshot.cover?.assetId??'');
  const [notes,setNotes]=useStudioDraftField<string>(scope,'notes',''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
  const live=(state.publications??[]).find(item=>item.id===delivery.id);
  const stale=JSON.stringify(live)!==JSON.stringify(snapshot);
  const assets=(state.assets??[]).filter(item=>item.contentId===delivery.contentId&&item.workspaceId===delivery.workspaceId);
  const changed=coverAssetId!==(snapshot.cover?.assetId??'')||JSON.stringify(networkSettings)!==JSON.stringify(snapshot.networkSettings??{})||text!==snapshot.text||timeZone!==snapshot.timeZone||planned!==zonedDateTime(snapshot.plannedAt,snapshot.timeZone)||JSON.stringify(selected)!==JSON.stringify(snapshot.media.map(item=>item.assetId));
  const locked=['sending','scheduled','published'].includes(snapshot.status)||Boolean(snapshot.operation&&snapshot.operation.phase!=='preview');
  const command=async(action:string)=>{setBusy(true);setSaved(false);setError('');try{
    await publicationCommand({action,id:snapshot.id,contentId:snapshot.contentId,expectedDelivery:snapshot,notes,draft:{text,timeZone,coverAssetId,...(Object.keys(networkSettings).length?{networkSettings}:{}),plannedAt:localTimeToInstant(planned,timeZone),assetIds:selected}});
    // State arrives through the provider. Close after a decision to prevent stale double submission.
    if(action!=='edit')onClose();else setSaved(true);
  }catch(failure){setError(String((failure as Error).message))}finally{setBusy(false)}};
  // Refresh only after our own save, never silently replace a version under review.
  useEffect(()=>{if(saved&&live&&JSON.stringify(live)!==JSON.stringify(snapshot)){setSnapshot(structuredClone(live));setSaved(false)}},[saved,live,snapshot]);
  return <FlowDialog title={`${delivery.platform} · ${pt?'Entrega':'Delivery'}`} description={`${state.contents.find(item=>item.id===delivery.contentId)?.title??''} · v${snapshot.version} · ${publicationLabel(snapshot.status,pt)}`} onClose={()=>{if(!busy)onClose()}}><div className="delivery-review-fields publication-editor">
    {stale&&!saved&&<p role="alert" className="delivery-error">{pt?'Esta entrega mudou. Feche e abra novamente para revisar a versão atual.':'This delivery changed. Close and reopen to review the current version.'}</p>}
    <label>{pt?'Texto da publicação':'Post text'}<textarea aria-label={pt?'Texto da publicação':'Post text'} value={text} disabled={locked||busy} onChange={event=>setText(event.target.value)}/></label>
    <fieldset className="publication-files"><legend>{pt?'Arquivos desta entrega':'Delivery files'}</legend>{assets.length?assets.map(asset=><label key={asset.id}><input type="checkbox" disabled={locked||busy||asset.status!=='available'} checked={selected.includes(asset.id)} onChange={()=>setSelected(items=>items.includes(asset.id)?items.filter(id=>id!==asset.id):[...items,asset.id])}/>{asset.name}<small>{asset.status}</small></label>):<p className="editorial-hint">{pt?'Adicione arquivos na biblioteca do conteúdo para selecioná-los aqui.':'Add files to the content library to select them here.'}</p>}{selected.some(id=>!assets.some(asset=>asset.id===id))&&<p role="alert">{pt?'Um arquivo foi removido.':'A file was removed.'}<button className="text-link" onClick={()=>setSelected(items=>items.filter(id=>assets.some(asset=>asset.id===id)))}>{pt?'Remover vínculo ausente':'Remove missing link'}</button></p>}</fieldset>
    <PublicationNetworkSettings platform={snapshot.platform} settings={networkSettings} onChange={setNetworkSettings} disabled={locked||busy} mediaType={selected.every(id=>assets.find(a=>a.id===id)?.kind==='image')?'photo':'video'}/>
    <label>{pt?'Capa do vídeo':'Video cover'}<SelectMenu ariaLabel={pt?'Capa do vídeo':'Video cover'} value={coverAssetId} disabled={locked||busy} onChange={setCoverAssetId} options={[{value:'',label:pt?'Sem capa personalizada':'No custom cover'},...assets.filter(asset=>asset.kind==='image').map(asset=>({value:asset.id,label:asset.name,disabled:asset.status!=='available'}))]}/><small>{pt?'Para capas de vídeo, utilize Zernio. A capa é enviada separadamente do vídeo.':'Use Zernio for video covers. The cover is uploaded separately from the video.'}</small></label>
    <label>{pt?'Fuso do horário planejado':'Planned time zone'}<SelectMenu ariaLabel={pt?'Fuso horário':'Time zone'} value={timeZone} disabled={locked||busy} onChange={zone=>{if(planned){try{const instant=localTimeToInstant(planned,timeZone);setPlanned(zonedDateTime(instant,zone));}catch{setPlanned('');}}setTimeZone(zone)}} options={[...new Set([timeZone,...zones])].map(value=>({value,label:value}))}/></label>
    <label>{pt?'Data e hora planejadas':'Planned date and time'}<input type="datetime-local" aria-label={pt?'Data e hora planejadas':'Planned date and time'} value={planned} disabled={locked||busy} onChange={event=>setPlanned(event.target.value)}/></label>
    <p className="editorial-hint">{pt?'Salvar ou aprovar organiza esta entrega localmente. O envio ao provedor terá uma autorização separada.':'Saving or approving organizes this delivery locally. Sending to the provider will require separate authorization.'}</p>
    <label>{pt?'Observação da revisão':'Review note'}<textarea value={notes} disabled={locked||busy} onChange={event=>setNotes(event.target.value)}/></label>
    {error&&<p role="alert" className="delivery-error">{error}</p>}
    {(snapshot.status==='approved'||snapshot.operation)&&<PublicationSender delivery={snapshot} disabled={busy||stale||changed} onChanged={()=>setSaved(true)} onBusy={setBusy}/>}
    {snapshot.history.length>0&&<details><summary>{pt?'Versões e decisões':'Versions and decisions'}</summary>{[...snapshot.history].reverse().map((entry,index)=><div className="publication-history" key={index}><b>v{entry.version} · {publicationLabel(entry.status,pt)}</b><small>{new Date(entry.at).toLocaleString(locale)}</small><p>{entry.notes}</p><details><summary>{pt?'Texto revisado':'Reviewed text'}</summary><p>{entry.payload?.text}</p></details></div>)}</details>}
  </div><footer className="delivery-review-footer publication-footer">
    <button className="soft-button" disabled={busy||stale||locked||!changed} onClick={()=>void command('edit')}>{pt?'Salvar alterações':'Save changes'}</button>
    {snapshot.status==='draft'&&<button className="primary-button" disabled={busy||stale||changed||!text.trim()&&!selected.length} onClick={()=>void command('submit')}>{pt?'Enviar para revisão':'Submit for review'}</button>}
    {snapshot.status==='in-review'&&<><button className="soft-button" disabled={busy||stale||changed} onClick={()=>void command('revise')}>{pt?'Pedir ajuste':'Request changes'}</button><button className="soft-button" disabled={busy||stale||changed} onClick={()=>void command('reject')}>{pt?'Rejeitar':'Reject'}</button><button className="primary-button" disabled={busy||stale||changed} onClick={()=>void command('approve')}>{pt?'Aprovar esta entrega':'Approve delivery'}</button></>}
  </footer></FlowDialog>;
}

function PublicationSender({delivery,disabled,onChanged,onBusy}:{delivery:PublicationDelivery;disabled:boolean;onChanged:()=>void;onBusy:(busy:boolean)=>void}){
  const {publicationAccounts,publicationTransport}=useContentWorkflow(),{locale}=useLanguage(),pt=locale==='pt-BR';
  const [accounts,setAccounts]=useState<Array<{id:string;name:string}>>([]),[account,setAccount]=useState(''),[mode,setMode]=useState('draft'),[externalId,setExternalId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[cancelConfirm,setCancelConfirm]=useState(false);
  const supported=['LinkedIn','Instagram','TikTok'].includes(delivery.platform),op=delivery.operation;
  const [provider,setProvider]=useState<'publora'|'zernio'>(op?.provider??(delivery.platform==='LinkedIn'?'publora':'zernio'));const providerName=(op?.provider??provider)==='publora'?'Publora':'Zernio';
  const load=async()=>{setBusy(true);onBusy(true);setError('');try{const result=await publicationAccounts(provider,delivery.platform);setAccounts(result.accounts);setAccount('');if(!result.accounts.length)setError(pt?`Nenhuma conta ${delivery.platform} ativa no ${providerName}. Confira a conexão.`:`No active ${delivery.platform} account in ${providerName}. Check its connection.`)}catch(failure){setError((failure as Error).message)}finally{setBusy(false);onBusy(false)}};
  const act=async(action:'prepare'|'execute'|'reconcile'|'cancel'|'continue')=>{setBusy(true);onBusy(true);setError('');try{await publicationTransport(action,{id:delivery.id,expectedDelivery:delivery,provider:op?.provider??provider,accountId:op?.accountId??account,mode:action==='continue'?'draft':op?.mode??mode,authorize:action==='execute'||action==='cancel'||action==='continue',externalId});onChanged()}catch(failure){setError((failure as Error).message);onChanged()}finally{setBusy(false);onBusy(false)}};
  return <section className="publication-sender" aria-label={pt?`Enviar ao ${providerName}`:`Send to ${providerName}`}><h3>{providerName}</h3>
    {!supported?<p className="editorial-hint">{pt?'Envio nativo disponível para LinkedIn, Instagram e TikTok. YouTube permanece apenas no planejamento local.':'Native sending supports LinkedIn, Instagram and TikTok. YouTube remains local planning.'}</p>:<>
      {!op&&<>{delivery.platform==='LinkedIn'&&<label>{pt?'Provedor':'Provider'}<SelectMenu ariaLabel={pt?'Provedor de publicação':'Publishing provider'} value={provider} disabled={busy||disabled} onChange={value=>{setProvider(value as 'publora'|'zernio');setAccounts([]);setAccount('')}} options={[{value:'publora',label:'Publora'},{value:'zernio',label:'Zernio'}]}/></label>}<p className="editorial-hint">{pt?'Escolha a conta e confira o destino antes de autorizar. Consultar contas não envia conteúdo.':'Choose the account and review the destination before authorizing. Checking accounts does not send content.'}</p><button className="soft-button" disabled={busy||disabled} onClick={()=>void load()}>{pt?`Consultar contas do ${providerName}`:`Check ${providerName} accounts`}</button>
      {accounts.length>0&&<><label>{pt?'Conta da publicação':'Publishing account'}<SelectMenu ariaLabel={pt?'Conta LinkedIn':'LinkedIn account'} value={account} disabled={busy||disabled} onChange={setAccount} options={[{value:'',label:pt?'Selecione uma conta':'Choose an account'},...accounts.map(item=>({value:item.id,label:`${item.name} (${item.id})`}))]}/></label><label>{pt?'Destino':'Destination'}<SelectMenu ariaLabel={pt?`Destino no ${providerName}`:`${providerName} destination`} value={mode} disabled={busy||disabled} onChange={setMode} options={[{value:'draft',label:pt?`Rascunho no ${providerName}`:`${providerName} draft`},{value:'schedule',label:pt?'Agendar no horário planejado':'Schedule at planned time'}]}/></label><button className="soft-button" disabled={busy||disabled||!account||mode==='schedule'&&!delivery.plannedAt} onClick={()=>void act('prepare')}>{pt?'Conferir envio':'Review send'}</button></>}
      </>}
      {op&&<>{Boolean(op.files?.length)&&<p className="editorial-hint">{pt?'Arquivos a enviar':'Files to upload'}: {op.files?.map(f=>`${f.name} (${(f.size/1024/1024).toFixed(1)} MB)`).join(', ')}</p>}<p><b>{op.accountId}</b><br/>{op.mode==='draft'?(pt?'Criar rascunho externo; não publicar.':'Create external draft; do not publish.'):(pt?'Agendar publicação: ':'Schedule publication: ')+(delivery.plannedAt?new Date(delivery.plannedAt).toLocaleString(locale,{timeZone:delivery.timeZone}):'')}{op.mode==='schedule'&&` (${delivery.timeZone})`}</p>
      {op.phase==='preview'?<><p className="editorial-hint">{pt?`A autorização envia exatamente o texto e os arquivos aprovados acima. A publicação agendada será executada pelo ${providerName} no horário escolhido.`:`Authorization sends exactly the approved text and files above. ${providerName} executes scheduled publication at the chosen time.`}</p><button className="primary-button" disabled={busy||disabled} onClick={()=>void act('execute')}>{pt?(op.mode==='draft'?'Autorizar criação do rascunho':'Autorizar agendamento'):(op.mode==='draft'?'Authorize draft creation':'Authorize scheduling')}</button><button className="text-link" disabled={busy||disabled} onClick={()=>void act('prepare')}>{pt?'Renovar prévia':'Renew preview'}</button></>:<><p className="editorial-hint" role="status">{op.phase==='confirmed'&&delivery.receipt?`${pt?'Estado confirmado':'Confirmed state'}: ${delivery.receipt.status} · ${new Date(delivery.receipt.checkedAt).toLocaleString(locale)}`:(pt?'Resultado não confirmado. Consulte antes de tentar qualquer novo envio.':'Unconfirmed result. Check before attempting any new send.')}</p>{op.externalId?<p>ID: {op.externalId}</p>:<label>{pt?`ID do grupo de post encontrado no ${providerName}`:`Post group ID found in ${providerName}`}<input value={externalId} onChange={event=>setExternalId(event.target.value)} disabled={busy||disabled}/><small>{pt?'Usado apenas para consultar e verificar; não cria um post.':'Only queries and verifies; does not create a post.'}</small></label>}<button className="soft-button" disabled={busy||disabled||!op.externalId&&!externalId} onClick={()=>void act('reconcile')}>{pt?`Consultar resultado no ${providerName}`:`Check result in ${providerName}`}</button>{op.phase==='uncertain'&&op.stage==='uploading'&&<button className="soft-button" disabled={busy||disabled} onClick={()=>void act('continue')}>{pt?'Retomar upload como rascunho':'Resume upload as a draft'}</button>}{delivery.status==='scheduled'&&op.phase==='confirmed'&&<><button className="text-link" disabled={busy||disabled} onClick={()=>setCancelConfirm(!cancelConfirm)}>{pt?'Cancelar agendamento':'Cancel schedule'}</button>{cancelConfirm&&<><p role="alert">{pt?`O post será transformado em rascunho no ${providerName}. Autorize apenas se deseja cancelar este horário.`:`The post will become a draft in ${providerName}. Authorize only if you want to cancel this schedule.`}</p><button className="soft-button" disabled={busy||disabled} onClick={()=>void act('cancel')}>{pt?`Autorizar cancelamento no ${providerName}`:`Authorize cancellation in ${providerName}`}</button></>}</>}</>}
      </>}
    </>}{supported&&op?.phase==='confirmed'&&['draft','scheduled'].includes(delivery.receipt?.status??'')&&<PublicationChange delivery={delivery} disabled={busy||disabled} onChanged={onChanged} onBusy={onBusy}/>} {error&&<p className="delivery-error" role="alert">{error}</p>}
  </section>;
}

function PublicationChange({delivery,disabled,onChanged,onBusy}:{delivery:PublicationDelivery;disabled:boolean;onChanged:()=>void;onBusy:(busy:boolean)=>void}){
  const {preparePublicationChange,publicationTransport}=useContentWorkflow(),{locale}=useLanguage(),pt=locale==='pt-BR';
  const changeScope=studioDraftKey('publication-change',delivery.workspaceId,delivery.id,String(delivery.version),delivery.operation?.id??'none');
  const [open,setOpen]=useState(false),[text,setText]=useStudioDraftField<string>(changeScope,'text',delivery.text),[zone,setZone]=useStudioDraftField<string>(changeScope,'zone',delivery.timeZone),[planned,setPlanned]=useStudioDraftField<string>(changeScope,'planned',zonedDateTime(delivery.plannedAt,delivery.timeZone)),[mode,setMode]=useStudioDraftField<string>(changeScope,'mode',delivery.receipt?.status==='scheduled'?'schedule':'draft');
  const [preview,setPreview]=useState<{id:string;expiresAt:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{setPreview(null);setOpen(false)},[delivery]);
  const act=async()=>{setBusy(true);onBusy(true);setError('');try{
    if(!preview){const result=await preparePublicationChange({id:delivery.id,expectedDelivery:delivery,mode,draft:{text,timeZone:zone,plannedAt:mode==='schedule'?localTimeToInstant(planned,zone):undefined}});setPreview(result.preview);}
    else {await publicationTransport('change',{id:delivery.id,expectedDelivery:delivery,changeId:preview.id,authorize:true});setPreview(null);setOpen(false);onChanged();}
  }catch(e){setError((e as Error).message);if(preview)onChanged();}finally{setBusy(false);onBusy(false)}};
  return <div className="publication-change"><button type="button" className="text-link" disabled={disabled||busy} onClick={()=>{setOpen(!open);setPreview(null);setError('')}}>{pt?`Editar ou reagendar no ${delivery.operation?.provider==='zernio'?'Zernio':'Publora'}`:`Edit or reschedule in ${delivery.operation?.provider==='zernio'?'Zernio':'Publora'}`}</button>{open&&<div className="delivery-review-fields">
    <p className="editorial-hint">{pt?'Altera o mesmo post e guarda uma nova versão aprovada. Confira o texto e o horário antes de autorizar.':'Updates the same post and keeps a new approved version. Review text and time before authorizing.'}</p>
    <label>{pt?'Novo texto':'New text'}<textarea aria-label={pt?'Novo texto':'New text'} value={text} disabled={disabled||busy||!!preview} onChange={e=>setText(e.target.value)}/></label>
    <label>{pt?'Novo destino':'New destination'}<SelectMenu ariaLabel={pt?'Novo destino':'New destination'} value={mode} disabled={disabled||busy||!!preview} onChange={setMode} options={[{value:'draft',label:pt?'Rascunho':'Draft'},{value:'schedule',label:pt?'Agendado':'Scheduled'}]}/></label>
    {mode==='schedule'&&<><label>{pt?'Fuso horário da alteração':'Edit time zone'}<SelectMenu ariaLabel={pt?'Fuso horário da alteração':'Edit time zone'} value={zone} disabled={disabled||busy||!!preview} onChange={next=>{if(planned){try{setPlanned(zonedDateTime(localTimeToInstant(planned,zone),next))}catch{setPlanned('')}}setZone(next)}} options={[...new Set([zone,...zones])].map(value=>({value,label:value}))}/></label><label>{pt?'Novo horário':'New time'}<input type="datetime-local" aria-label={pt?'Novo horário':'New time'} value={planned} disabled={disabled||busy||!!preview} onChange={e=>setPlanned(e.target.value)}/></label></>}
    {preview&&<p role="status">{pt?'Prévia pronta para o post':'Preview ready for post'} {delivery.operation?.externalId} · {delivery.operation?.accountId}. {pt?'A alteração só é enviada ao autorizar abaixo.':'The change is sent only after authorization below.'}</p>}
    <button className={preview?'primary-button':'soft-button'} disabled={disabled||busy||!text.trim()||mode==='schedule'&&!planned} onClick={()=>void act()}>{preview?(pt?`Autorizar alteração no ${delivery.operation?.provider==='zernio'?'Zernio':'Publora'}`:`Authorize change in ${delivery.operation?.provider==='zernio'?'Zernio':'Publora'}`):(pt?'Conferir alteração':'Review change')}</button>{preview&&<button className="text-link" disabled={disabled||busy} onClick={()=>setPreview(null)}>{pt?'Voltar para editar':'Back to edit'}</button>}
    {error&&<p role="alert" className="delivery-error">{error}</p>}
  </div>}</div>;
}
