import {useEffect,useRef,useState} from 'react';
import {useContentWorkflow} from '../../features/content/ContentWorkflowProvider';
import {useLanguage} from '../../app/LanguageProvider';
import type {CalendarAccount,CalendarSource,ProviderPost,CalendarProvider} from '../../features/content/publicationCalendar';
import {SelectMenu} from '../common/SelectMenu';
import {FlowDialog} from '../common/FlowDialog';
import {zonedDateTime} from '../../../publication-time.mjs';
import {storageProfile} from '../../data/IndexedDbStateStore';
import {PublicationTile,imagePreviewUrl} from './PublicationTile';

const statuses={draft:['Rascunho','Draft'],scheduled:['Agendado','Scheduled'],published:['Publicado','Published'],failed:['Falhou','Failed'],cancelled:['Cancelado','Cancelled'],publishing:['Publicando','Publishing'],partial:['Resultado parcial','Partial result']};
export function ProviderCalendar({workspaceId,zone,month}:{workspaceId:string;zone:string;month:string}){
 const {publicationCalendar,calendarAccounts,syncCalendar,configureCalendarRefresh}=useContentWorkflow(),{locale}=useLanguage(),pt=locale==='pt-BR';
 const [sources,setSources]=useState<CalendarSource[]>([]),[provider,setProvider]=useState<CalendarProvider>('publora'),[accounts,setAccounts]=useState<CalendarAccount[]>([]),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[post,setPost]=useState<ProviderPost|null>(null),[filter,setFilter]=useState('all');
 const generation=useRef(0);
 useEffect(()=>{const current=++generation.current;setSources([]);setAccounts([]);setSelected([]);setPost(null);setError('');setBusy(false);void publicationCalendar(workspaceId).then(data=>{if(current===generation.current)setSources(data.sources)}).catch(e=>{if(current===generation.current)setError(e.message)});return()=>{generation.current++}},[workspaceId,publicationCalendar]);
 const savedIds=JSON.stringify(sources.find(x=>x.provider===provider)?.accountIds??[]);
 useEffect(()=>{setAccounts([]);setSelected(JSON.parse(savedIds))},[provider,savedIds]);
 useEffect(()=>{
  const refresh=()=>{const current=generation.current;void publicationCalendar(workspaceId).then(data=>{if(current===generation.current)setSources(data.sources)}).catch(()=>{});};
  const timer=setInterval(refresh,60000);window.addEventListener('mainsagents:provider-calendar-changed',refresh);
  return()=>{clearInterval(timer);window.removeEventListener('mainsagents:provider-calendar-changed',refresh)};
 },[workspaceId,publicationCalendar]);
 const setAutomatic=async(enabled:boolean,intervalMinutes:number)=>{const current=generation.current;setBusy(true);setError('');try{const next=await configureCalendarRefresh(workspaceId,provider,enabled,intervalMinutes);if(current===generation.current)setSources(items=>[...items.filter(x=>x.provider!==provider),next]);}catch(e){if(current===generation.current)setError((e as Error).message)}finally{if(current===generation.current)setBusy(false)}};
 const act=async(sync:boolean)=>{const current=generation.current;setBusy(true);setError('');try{
  if(sync){const next=await syncCalendar(workspaceId,provider,selected);if(current===generation.current)setSources(items=>[...items.filter(x=>x.provider!==provider),next]);}
  else {const data=await calendarAccounts(workspaceId,provider);if(current===generation.current)setAccounts(data.accounts);}
 }catch(e){if(current===generation.current){setError((e as Error).message);try{const data=await publicationCalendar(workspaceId);if(current===generation.current)setSources(data.sources)}catch{/* keep the last local snapshot */}}}finally{if(current===generation.current)setBusy(false)}};
 const source=sources.find(x=>x.provider===provider);
 const all=sources.flatMap(x=>x.items).filter(x=>filter==='all'||x.provider===filter);
 const date=(item:ProviderPost)=>item.status==='published'?item.publishedAt??item.scheduledAt:item.scheduledAt;
 const posts=all.filter(x=>date(x)&&zonedDateTime(date(x),zone).startsWith(month)).sort((a,b)=>date(a)!.localeCompare(date(b)!));
 const name=(item:ProviderPost)=>sources.find(x=>x.provider===item.provider)?.accounts?.find(x=>x.id===item.accountId)?.name??item.accountId;
 const tile=(item:ProviderPost)=><PublicationTile className="provider-post" key={item.key} id={`provider-${item.key}`} title={item.text|| (pt?'Publicação com mídia':'Media post')} platform={item.platform} status={item.status} statusLabel={statuses[item.status][pt?0:1]} time={date(item)?zonedDateTime(date(item),zone).slice(11,16):undefined} cover={imagePreviewUrl(item.thumbnailUrl)} pt={pt} onClick={()=>setPost(item)}/>;
 const [year,number]=month.split('-').map(Number),days=new Date(Date.UTC(year,number,0)).getUTCDate(),offset=(new Date(Date.UTC(year,number-1,1)).getUTCDay()+6)%7;
 return <section className="provider-calendar" aria-label={pt?'Posts dos provedores':'Provider posts'}>
  <div className="editorial-section-head"><div><h3>{pt?'Posts dos provedores':'Provider posts'}</h3><p className="editorial-hint">{pt?'Consulte seus MCPs para ver o que já existe no Publora e Zernio. Esta consulta não publica nem altera posts.':'Query your MCPs to see existing Publora and Zernio posts. This query does not publish or change posts.'}</p></div></div>
  <div className="provider-calendar-controls"><SelectMenu ariaLabel={pt?'Provedor para consultar':'Provider to query'} value={provider} disabled={busy} onChange={x=>setProvider(x as CalendarProvider)} options={[{value:'publora',label:'Publora'},{value:'zernio',label:'Zernio'}]}/><button className="soft-button" disabled={busy} onClick={()=>void act(false)}>{pt?'Escolher contas':'Choose accounts'}</button><button className="primary-button" disabled={busy||!selected.length} onClick={()=>void act(true)}>{busy?(pt?'Consultando…':'Checking…'):(pt?'Atualizar agendamentos':'Refresh schedules')}</button></div>
  {accounts.length>0&&<fieldset className="provider-calendar-accounts"><legend>{pt?'Contas deste workspace':'Accounts for this workspace'}</legend>{accounts.map(x=><label key={x.id}><input type="checkbox" disabled={busy} checked={selected.includes(x.id)} onChange={()=>setSelected(ids=>ids.includes(x.id)?ids.filter(id=>id!==x.id):[...ids,x.id])}/><span>{x.name}<small>{x.platform} · {x.id}</small></span></label>)}</fieldset>}
  {(source?.accountIds.length??0)>0&&<div className="provider-calendar-controls"><label><input type="checkbox" aria-label={pt?'Atualização automática do calendário':'Automatic calendar refresh'} checked={Boolean(source?.autoRefresh?.enabled)} disabled={busy} onChange={e=>void setAutomatic(e.target.checked,source?.autoRefresh?.intervalMinutes??15)}/>{pt?'Atualizar automaticamente enquanto o app está aberto':'Refresh automatically while the app is open'}</label><SelectMenu ariaLabel={pt?'Intervalo de atualização':'Refresh interval'} value={String(source?.autoRefresh?.intervalMinutes??15)} disabled={busy} onChange={value=>void setAutomatic(Boolean(source?.autoRefresh?.enabled),Number(value))} options={[5,15,30,60].map(minutes=>({value:String(minutes),label:minutes+' min'}))}/></div>}
  {provider==='zernio'&&<CalendarApiKey disabled={busy} onChanged={()=>{setAccounts([]);setSelected([]);setError('')}}/>}
  {source?.checkedAt&&<p className="editorial-hint">{pt?'Última consulta':'Last query'}: {new Date(source.checkedAt).toLocaleString(locale)} · {source.transport==='api'?'API':'MCP'} · {source.accounts?.map(x=>x.name).join(', ')}{!source.complete&&` · ${pt?'Consulta limitada: alguns posts podem faltar.':'Limited query: some posts may be missing.'}`}</p>}
  {sources.filter(x=>x.error).map(x=><p className="delivery-error" role="status" key={x.provider}>{x.provider}: {pt?'A última consulta falhou. Os dados anteriores foram mantidos.':'Last query failed. Previous data was preserved.'}</p>)}
  {error&&<p className="delivery-error" role="alert">{error}</p>}
  <SelectMenu ariaLabel={pt?'Filtrar origem dos posts':'Filter post source'} value={filter} onChange={setFilter} options={[{value:'all',label:pt?'Todos os provedores':'All providers'},{value:'publora',label:'Publora'},{value:'zernio',label:'Zernio'}]}/>
  <div className="calendar-grid provider-calendar-grid">{(pt?['Seg','Ter','Qua','Qui','Sex','Sáb','Dom']:['Mon','Tue','Wed','Thu','Fri','Sat','Sun']).map(day=><span className="calendar-weekday" key={day}>{day}</span>)}{Array.from({length:offset},(_,i)=><div className="calendar-spacer" key={`empty-${i}`}/>)}{Array.from({length:days},(_,i)=>{const day=`${month}-${String(i+1).padStart(2,'0')}`;return <div className="calendar-day" key={day}><time dateTime={day}>{i+1}</time>{posts.filter(x=>zonedDateTime(date(x),zone).slice(0,10)===day).map(tile)}</div>})}</div>
  <div className="calendar-agenda provider-calendar-posts">{posts.map(tile)}</div>
  {!posts.length&&<p className="editorial-hint">{pt?'Nenhum post consultado para este mês. Escolha suas contas e atualize os agendamentos.':'No queried posts for this month. Choose accounts and refresh schedules.'}</p>}
  <details><summary>{pt?'Posts sem horário':'Posts without time'} ({all.filter(x=>!date(x)).length})</summary><div className="provider-calendar-posts">{all.filter(x=>!date(x)).map(tile)}</div></details>
  {post&&<FlowDialog title={`${post.provider==='publora'?'Publora':'Zernio'} · ${post.platform}`} description={`${name(post)} · ${statuses[post.status][pt?0:1]}`} onClose={()=>setPost(null)}><div className="provider-post-detail"><p>{post.text}</p><small>ID: {post.postId}</small><small>{pt?'Conta':'Account'}: {post.accountId}</small>{date(post)&&<small>{new Date(date(post)!).toLocaleString(locale,{timeZone:zone})} ({zone})</small>}<small>{pt?'Consultado em':'Checked at'}: {new Date(post.checkedAt).toLocaleString(locale)}</small><p className="editorial-hint">{pt?'Este registro veio do provedor. Para alterar o post, use o Publora ou Zernio.':'This record came from the provider. Edit it in Publora or Zernio.'}</p></div></FlowDialog>}
 </section>;
}

function CalendarApiKey({disabled,onChanged}:{disabled:boolean;onChanged:()=>void}){
 const api=window.mainsAgentsDesktop?.calendarKey,{locale}=useLanguage(),pt=locale==='pt-BR';
 const [status,setStatus]=useState<{configured:boolean;secureStorage:boolean}|null>(null),[key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;if(api)void api.status(storageProfile()).then(x=>{if(active)setStatus(x)}).catch(()=>{if(active)setError(pt?'Não foi possível consultar a conexão API.':'Could not check the API connection.')});return()=>{active=false}},[api,pt]);
 const act=async(remove:boolean)=>{if(!api)return;setBusy(true);setError('');try{setStatus(await (remove?api.remove(storageProfile()):api.save(storageProfile(),key.trim())));onChanged()}catch{setError(pt?'Não foi possível salvar a conexão. Confira a chave e o armazenamento seguro.':'Could not save the connection. Check the key and secure storage.')}finally{setKey('');setBusy(false)}};
 return <details className="provider-calendar-api"><summary>{pt?'Alternativa por API do Zernio':'Zernio API alternative'}{status?.configured?' · API': ' · MCP'}</summary><p className="editorial-hint">{pt?'Se o MCP retornar apenas resumos, cadastre sua chave aqui. Ela fica criptografada neste computador e permite consultar contas/posts e enviar somente entregas que você autorizar separadamente.':'If MCP returns only summaries, save your key here. It stays encrypted on this computer and queries accounts/posts and sends only deliveries you separately authorize.'}</p>{api?<>{status?.configured?<><p className="editorial-hint">{pt?'Chave cadastrada. As próximas consultas usarão a API.':'Key saved. Future queries will use the API.'}</p><button className="soft-button" disabled={busy||disabled} onClick={()=>void act(true)}>{pt?'Remover chave e usar MCP':'Remove key and use MCP'}</button></>:<><label>{pt?'Chave API do Zernio':'Zernio API key'}<input type="password" autoComplete="off" spellCheck={false} aria-label={pt?'Chave API do Zernio':'Zernio API key'} value={key} disabled={busy||disabled||!status?.secureStorage} onChange={e=>setKey(e.target.value)}/></label><button className="soft-button" disabled={busy||disabled||!/^sk_[a-fA-F0-9]{64}$/.test(key.trim())||!status?.secureStorage} onClick={()=>void act(false)}>{pt?'Salvar chave com segurança':'Save key securely'}</button>{status&&!status.secureStorage&&<p className="delivery-error">{pt?'Armazenamento criptografado indisponível.':'Encrypted storage unavailable.'}</p>}</>}{error&&<p role="alert" className="delivery-error">{error}</p>}</>:<p className="editorial-hint">{pt?'Cadastro seguro de chave disponível no app desktop.':'Secure key setup is available in the desktop app.'}</p>}</details>;
}
