import {useState} from 'react';
import type {PublicationDelivery,Platform} from '../../features/content/model';
import {useContentWorkflow} from '../../features/content/ContentWorkflowProvider';
import {useLanguage} from '../../app/LanguageProvider';
import {SelectMenu} from '../common/SelectMenu';
type Settings=NonNullable<PublicationDelivery['networkSettings']>;
export function PublicationNetworkSettings({platform,settings,onChange,disabled,mediaType}:{platform:Platform;settings:Settings;onChange:(s:Settings)=>void;disabled:boolean;mediaType:'video'|'photo'}){
 const {publicationAccounts,publicationOptions}=useContentWorkflow(),{locale}=useLanguage(),pt=locale==='pt-BR';
 const [accounts,setAccounts]=useState<Array<{id:string;name:string}>>([]),[account,setAccount]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [options,setOptions]=useState<Awaited<ReturnType<typeof publicationOptions>>|null>(null);
 if(platform==='Instagram')return <fieldset className="publication-network"><legend>Instagram</legend><label>{pt?'Formato':'Format'}<SelectMenu ariaLabel={pt?'Formato Instagram':'Instagram format'} value={settings.contentType??'feed'} disabled={disabled} onChange={value=>onChange(value==='story'?{contentType:'story'}:{shareToFeed:settings.shareToFeed??true})} options={[{value:'feed',label:pt?'Feed / Reel (vídeo)':'Feed / Reel (video)'},{value:'story',label:'Story'}]}/></label>{settings.contentType!=='story'&&<label><input type="checkbox" checked={settings.shareToFeed??true} disabled={disabled} onChange={e=>onChange({shareToFeed:e.target.checked})}/>{pt?'Mostrar Reel também no feed':'Show Reel in feed too'}</label>}</fieldset>;
 if(platform!=='TikTok')return null;
 const t=settings.tiktokSettings??{privacy_level:'',commercialContentType:'none',allow_comment:false,allow_duet:false,allow_stitch:false,content_preview_confirmed:false,express_consent_given:false,video_made_with_ai:false};
 const change=(key:string,value:string|boolean)=>onChange({tiktokSettings:{...t,[key]:value}});
 const load=async()=>{setBusy(true);setError('');try{if(!account){setAccounts((await publicationAccounts('zernio','TikTok')).accounts);return;}setOptions(await publicationOptions(account,mediaType));}catch(e){setError((e as Error).message);}finally{setBusy(false)}};
 return <fieldset className="publication-network"><legend>{pt?'Privacidade e consentimento TikTok':'TikTok privacy and consent'}</legend><p className="editorial-hint">{pt?'Consulte a conta e revise estas opções antes de aprovar. O envio confere novamente os limites da conta escolhida.':'Query the account and review these options before approval. Sending rechecks the selected account limits.'}</p><button className="soft-button" disabled={disabled||busy} onClick={()=>void load()}>{pt?(account?'Consultar opções da conta':'Consultar contas TikTok'):(account?'Query account settings':'Query TikTok accounts')}</button>{accounts.length>0&&<SelectMenu ariaLabel={pt?'Conta TikTok para opções':'TikTok settings account'} value={account} disabled={disabled||busy} onChange={value=>{setAccount(value);setOptions(null)}} options={[{value:'',label:pt?'Selecione a conta':'Select account'},...accounts.map(a=>({value:a.id,label:a.name}))]}/>}
 <label>{pt?'Privacidade':'Privacy'}<SelectMenu ariaLabel={pt?'Privacidade TikTok':'TikTok privacy'} value={t.privacy_level} disabled={disabled||!options} onChange={v=>change('privacy_level',v)} options={[{value:'',label:pt?'Escolha explicitamente':'Choose explicitly'},...(options?.privacyLevels??(t.privacy_level?[{value:t.privacy_level,label:t.privacy_level}]:[]))]}/></label>
 <label>{pt?'Conteúdo comercial':'Commercial content'}<SelectMenu ariaLabel={pt?'Conteúdo comercial TikTok':'TikTok commercial content'} value={t.commercialContentType} disabled={disabled||!options} onChange={v=>change('commercialContentType',v)} options={options?.commercialContentTypes??[{value:t.commercialContentType,label:t.commercialContentType}]}/></label>
 {(['allow_comment','allow_duet','allow_stitch','video_made_with_ai','content_preview_confirmed','express_consent_given'] as const).filter(k=>mediaType==='video'||!['allow_duet','allow_stitch'].includes(k)).map(key=><label key={key}><input type="checkbox" checked={t[key]} disabled={disabled||options?.postingLimits.interactionSettings[key]?.enabled===false} onChange={e=>change(key,e.target.checked)}/>{{allow_comment:pt?'Permitir comentários':'Allow comments',allow_duet:pt?'Permitir duetos':'Allow duets',allow_stitch:pt?'Permitir costura':'Allow stitch',video_made_with_ai:pt?'Vídeo feito com IA':'Video made with AI',content_preview_confirmed:pt?'Revisei o texto e a mídia desta versão':'I reviewed this version’s text and media',express_consent_given:pt?'Concordo com o envio deste conteúdo ao TikTok':'I consent to sending this content to TikTok'}[key]}</label>)}
 {error&&<p className="delivery-error" role="alert">{error}</p>}</fieldset>;
}
