import type { Agent, AgentTool } from '../features/agents/model/Agent';
import { agentStatusLabels, agentToolDetails, getAgentInitials } from '../features/agents/model/Agent';
import { useLanguage } from '../app/LanguageProvider';

const availableTools = Object.keys(agentToolDetails) as AgentTool[];

export function AgentSettings({agent,onBack,onEdit}:{agent:Agent;onBack:()=>void;onEdit:()=>void}) {
  const {t}=useLanguage();
  return <div className="page"><div className="page-head"><div><p className="eyebrow">{t('Agent settings')}</p><h1>{agent.name}</h1><p>{t('Define the role, tools, skills, and default working behavior.')}</p></div><button className="soft-button" onClick={onBack}>{t('Back to agents')}</button></div><div className="agent-settings-hero"><span className="agent-monogram">{getAgentInitials(agent)}</span><div><b>{agent.name}</b><span>{agent.role} · {t(agentStatusLabels[agent.status])}</span></div><button className="primary-button" onClick={onEdit}>{t('Edit agent')}</button></div><section className="settings-panel agent-settings-panel"><label className="field"><span>{t('Name')}</span><input value={agent.name} readOnly/></label><label className="field"><span>{t('Role')}</span><input value={agent.role} readOnly/></label><label className="field full"><span>{t('Description')}</span><input value={agent.description} readOnly/></label><label className="field full"><span>{t('Instructions')}</span><textarea rows={5} value={agent.instructions} readOnly/></label>{availableTools.map((tool)=>{const detail=agentToolDetails[tool];const enabled=agent.tools.includes(tool);return <div className="setting-row" key={tool}><div className="setting-copy"><b>{t(detail.label)}</b><p>{t(detail.description)}</p></div><button className={`toggle ${enabled?'on':''}`} aria-label={t(detail.label)} aria-pressed={enabled} disabled/></div>})}{agent.skillsDirectory&&<div className="setting-row"><div className="setting-copy"><b>{t('Skills')}</b><p>{agent.skillsDirectory}</p><div className="skill-list">{(agent.skills??[]).map((skill)=><span key={skill}>{skill}</span>)}</div></div></div>}</section></div>;
}
