import {useMemo, useState} from 'react';
import {ReactFlow, Background, Controls, Handle, Position, MarkerType, type Node, type NodeProps} from '@xyflow/react';
import {useCanvas} from '../components/canvas/CanvasProvider';
import {useAgents} from '../features/agents/AgentsProvider';
import {useWorkspaces} from '../app/WorkspaceProvider';
import {useLanguage} from '../app/LanguageProvider';
import {AgentAvatar} from '../components/agents/AgentAvatar';
import {AgentStatus} from '../components/agents/AgentStatus';
import {Icon} from '../components/common/Icon';
import {arrangeRelations} from '../components/canvas/flowLayout';
import type {Agent} from '../features/agents/model/Agent';
type RelationshipNode=Node<{title:string;summary:string;kind:string;agent?:Agent},'relationship'>;
function RelationshipCard({data,selected}:NodeProps<RelationshipNode>){const {t}=useLanguage();return <article className={`relationship-card ${selected?'selected':''}`}><Handle type="target" position={Position.Top}/><div className="relationship-heading">{data.agent?<AgentAvatar name={data.agent.name} image={data.agent.avatarImage}/>:<span className="relationship-symbol"><Icon name="note"/></span>}<div><strong>{data.title}</strong><small>{data.agent?.role||data.kind}</small></div></div><p>{data.summary}</p><footer>{data.agent?<AgentStatus status={data.agent.status}/>:<span>{data.kind}</span>}{data.agent&&<span>{data.agent.tools.length} {t('tools')}</span>}</footer><Handle type="source" position={Position.Bottom}/></article>}
const nodeTypes={relationship:RelationshipCard};
export function Flow({onOpenCanvas,onSelectAgent}:{onOpenCanvas:()=>void;onSelectAgent:(id:string)=>void}){
 const {nodes,edges,selectNode}=useCanvas(),{agents}=useAgents(),{currentWorkspaceId}=useWorkspaces(),{locale,t}=useLanguage();
 const pt=locale==='pt-BR';const [selectedId,setSelectedId]=useState<string|null>(null);
 const graph=useMemo(()=>arrangeRelations(nodes.map(node=>({id:node.id,type:'relationship' as const,position:{...node.position},style:{width:270},data:{title:node.data.title||node.data.caption||node.data.label,summary:String(node.data.summary||node.data.description||node.data.hook||node.data.text||node.data.preview||node.data.browserUrl||''),kind:t(node.data.label),agent:agents.find(agent=>agent.workspaceId===currentWorkspaceId&&agent.id===(node.data.agentId||node.data.chatAgentId))}})),edges),[nodes,edges,agents,currentWorkspaceId,t]);
 const selected=graph.find(node=>node.id===selectedId);
 return <div className="page full relationship-page"><div className="relationship-topline"><div><strong>{pt?'Fluxo do workspace':'Workspace flow'}</strong><p>{pt?'As conexões do Canvas, organizadas para leitura.':'Canvas connections, arranged for reading.'}</p></div><button className="soft-button" onClick={onOpenCanvas}><Icon name="canvas"/>{pt?'Editar no Canvas':'Edit in Canvas'}</button></div><ReactFlow<RelationshipNode> key={currentWorkspaceId} nodes={graph.map(node=>({...node,selected:node.id===selectedId}))} edges={edges.map(edge=>({...edge,type:'smoothstep',markerEnd:{type:MarkerType.ArrowClosed,width:16,height:16},style:{stroke:'var(--muted)',strokeWidth:1.2}}))} nodeTypes={nodeTypes} fitView fitViewOptions={{padding:.2,maxZoom:1}} nodesDraggable={false} nodesConnectable={false} edgesReconnectable={false} elementsSelectable onNodeClick={(_,node)=>setSelectedId(node.id)} onPaneClick={()=>setSelectedId(null)} deleteKeyCode={null} minZoom={.25} maxZoom={1.5} proOptions={{hideAttribution:true}}><Background gap={24} size={.65} color="var(--border)"/><Controls showInteractive={false}/></ReactFlow>{!nodes.length&&<div className="canvas-empty-state"><span className="empty-symbol"><Icon name="link"/></span><h2>{pt?'Conecte suas primeiras ideias':'Connect your first ideas'}</h2><p>{pt?'Adicione objetos ao Canvas e conecte seus pontos. As relações aparecerão aqui.':'Add Canvas objects and connect their handles. Their relationships will appear here.'}</p><button className="primary-button" onClick={onOpenCanvas}>{pt?'Abrir Canvas':'Open Canvas'}</button></div>}{selected&&<aside className="relationship-detail"><button className="icon-button" aria-label={t('Close')} onClick={()=>setSelectedId(null)}><Icon name="close"/></button><h3>{selected.data.title}</h3><p>{selected.data.summary||selected.data.kind}</p><button className="soft-button" onClick={()=>{selectNode(currentWorkspaceId,selected.id);onOpenCanvas()}}>{pt?'Localizar no Canvas':'Locate in Canvas'}</button>{selected.data.agent&&<button className="primary-button" onClick={()=>onSelectAgent(selected.data.agent!.id)}>{pt?'Conversar com agente':'Chat with agent'}</button>}</aside>}<span className="relationship-disclaimer">{pt?'Visualização das relações · não executa workflows automaticamente':'Relationship view · does not automatically execute workflows'}</span></div>
}
