import {useEffect,useRef,useState} from 'react';
import {ReactFlow,Background,Controls,MarkerType,type NodeChange,type Connection} from '@xyflow/react';
import {useAgents} from '../features/agents/AgentsProvider';
import {useChat} from '../features/chat/ChatProvider';
import {useWorkspaces} from '../app/WorkspaceProvider';
import {useLanguage} from '../app/LanguageProvider';
import {useContentWorkflow} from '../features/content/ContentWorkflowProvider';
import {usePersistentState} from '../data/localPersistence';
import {storageProfile} from '../data/IndexedDbStateStore';
import {Icon} from '../components/common/Icon';
import {SelectMenu} from '../components/common/SelectMenu';
import {FlowDialog} from '../components/common/FlowDialog';
import {ContentAssetLibrary} from '../components/content/ContentAssetLibrary';
import {ContentMediaEditor} from '../components/content/ContentMediaEditor';
import {ContentPublications} from '../components/content/ContentPublications';
import {ProductionFlowBox,flowIcons,flowDescriptions,type ProductionNode} from '../components/flows/ProductionFlowBox';
import {CanvasRelations} from './CanvasRelations';
import {boxKinds,boxTitle,createProductionFlow,initialProductionFlows,duplicateProductionFlow,bindFlowContent,canConnectFlow,linkFlow,upstreamFlowBox,type FlowBox,type ProductionFlow,type ProductionFlows} from '../features/flows/flowModel';
import type {LocalAssetInspection} from '../features/content/assetModel';
import './flow.css';
import {useProduction} from '../features/production/ProductionProvider';
import {productionStageLabel} from '../features/production/model';
import {ProductionDialog} from '../components/production/ProductionDialog';
const nodeTypes={production:ProductionFlowBox};

export function Flow({onOpenCanvas,onSelectAgent,onOpenStudio}:{onOpenCanvas:()=>void;onSelectAgent:(id:string)=>void;onOpenStudio?:()=>void}){
 const {agents}=useAgents(),chat=useChat(),editorial=useContentWorkflow(),{currentWorkspaceId}=useWorkspaces(),{locale}=useLanguage(),pt=locale==='pt-BR';
 const production=useProduction();const [productionOpen,setProductionOpen]=useState(false);
 const [saved,setSaved]=usePersistentState<ProductionFlows>('production-flows',()=>initialProductionFlows(currentWorkspaceId,agents,pt));
 const flows=saved.flows.filter(item=>item.workspaceId===currentWorkspaceId),flow=flows.find(item=>item.id===saved.activeByWorkspace[currentWorkspaceId])??flows[0];
 const available=agents.filter(agent=>agent.workspaceId===currentWorkspaceId),contents=editorial.state.contents.filter(item=>item.workspaceId===currentWorkspaceId),content=contents.find(item=>item.id===flow?.contentId);
 const videos=(editorial.state.assets??[]).filter(asset=>content&&asset.contentId===content.id&&asset.workspaceId===currentWorkspaceId&&asset.kind==='video');
 const activeProduction=production.runs.find(run=>run.flowId===flow?.id&&run.contentId===content?.id);
 const stageIndex=activeProduction?(['writing','notion'].includes(activeProduction.stage)?1:['recording','planning-edit','editing'].includes(activeProduction.stage)?2:['video-review','platforms','preparing-package','generating-cover','package-review'].includes(activeProduction.stage)?3:['schedule','scheduling','complete'].includes(activeProduction.stage)?4:-1):-1;
 const [mode,setMode]=useState<'production'|'relations'>('production'),[selectedId,setSelectedId]=useState<string>(),[dialog,setDialog]=useState<'create'|'rename'|'delete'|'delete-box'|'add'|null>(null),[name,setName]=useState('');
 const [busy,setBusy]=useState<string>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[brief,setBrief]=useState(''),[sendConfirm,setSendConfirm]=useState(false);
 const [attachment,setAttachment]=useState<{token:string;flowId:string;workspaceId:string;boxId:string;paths?:string[];targetId?:string}>(),[attachmentChoice,setAttachmentChoice]=useState('new'),[recordingTitle,setRecordingTitle]=useState('');
 const attachmentRef=useRef(attachment);attachmentRef.current=attachment;
 const [measured,setMeasured]=useState<Record<string,{width:number;height:number}>>({});
 const running=useRef(false),live=useRef({flowId:flow?.id,contentId:content?.id,scriptId:content?.approvedScriptArtifactId,workspaceId:currentWorkspaceId});live.current={flowId:flow?.id,contentId:content?.id,scriptId:content?.approvedScriptArtifactId,workspaceId:currentWorkspaceId};
 useEffect(()=>{setSelectedId(undefined);setError('');setNotice('');setSendConfirm(false);setBrief('')},[flow?.id,content?.id,currentWorkspaceId]);
 const update=(change:(current:ProductionFlow)=>ProductionFlow)=>{if(!flow)return;const id=flow.id;setSaved(current=>({...current,flows:current.flows.map(item=>item.id===id?{...change(item),updatedAt:new Date().toISOString()}:item)}))};
 const patch=(id:string,change:Partial<FlowBox>)=>update(current=>({...current,nodes:current.nodes.map(node=>node.id===id?{...node,...change}:node)}));
 const add=(next:ProductionFlow)=>setSaved(current=>({...current,flows:[...current.flows,next],activeByWorkspace:{...current.activeByWorkspace,[currentWorkspaceId]:next.id}}));
 const inspect=(id:string)=>{setSelectedId(id);setSendConfirm(false);setError('');setNotice('')};
 const openChat=(box:FlowBox)=>{
  const agent=available.find(item=>item.id===box.agentId);if(!flow||!agent){inspect(box.id);return;}
  if(box.sessionId?.startsWith('delegated-')&&!chat.sessions.some(session=>session.id===box.sessionId)){setNotice(pt?'Carregando a conversa do especialista. Tente novamente em um instante.':'Loading the specialist chat. Try again in a moment.');return;}
  const candidates=flow.nodes.filter(node=>node.agentId===agent.id);
  const prior=chat.sessions.find(session=>session.id===box.sessionId&&session.agentId===agent.id&&session.contentId===content?.id)??chat.sessions.find(session=>candidates.some(node=>node.sessionId===session.id)&&session.agentId===agent.id&&session.contentId===content?.id);
  const session=prior??chat.createSession(agent.id,`${flow.name}${content?` · ${content.title}`:''}`.slice(0,120),agent.providerId??'codex',agent.modelId,content?{contentId:content.id,topicId:content.topicId}:undefined);
  patch(box.id,{sessionId:session.id});chat.openSession(agent.id,session.id);onSelectAgent(agent.id);
 };
 const run=async(id:string,action:()=>Promise<void>)=>{if(running.current)return;running.current=true;setBusy(id);setError('');setNotice('');try{await action()}catch(failure){setError(failure instanceof Error?failure.message:String(failure))}finally{running.current=false;setBusy(undefined)}};
 const guard=()=>{if(live.current.flowId!==flow?.id||live.current.contentId!==content?.id||live.current.scriptId!==content?.approvedScriptArtifactId||live.current.workspaceId!==currentWorkspaceId)throw Error(pt?'O fluxo ou roteiro mudou. Confira o conteúdo antes de continuar.':'The flow or script changed. Check the content before continuing.')};
 const attach=async(files:LocalAssetInspection[])=>{guard();if(!content)throw Error(pt?'Escolha o conteúdo deste fluxo.':'Choose this flow’s content.');if(!files.length)return;if(files.some(file=>file.status!=='available'||file.kind!=='video'))throw Error(pt?'Selecione somente vídeos locais verificáveis.':'Select only verifiable local videos.');await editorial.attachFiles(content.id,files,'source');setNotice(pt?'Vídeo associado ao conteúdo. Prepare o envio ao editor.':'Video linked to the content. Prepare the editor briefing.')};
 const requestAttachment=(id:string,paths?:string[])=>{
  inspect(id);const native=window.mainsAgentsDesktop?.files;if(!native){setError(pt?'Este ambiente não disponibiliza arquivos locais. Abra o aplicativo desktop instalado para adicionar vídeos.':'Local files are unavailable here. Open the installed desktop app to add videos.');return;}
  if(!flow)return;
  if(!content){setAttachmentChoice(contents.length?contents[0].id:'new');setRecordingTitle(flow.name);setAttachment({token:crypto.randomUUID(),flowId:flow.id,workspaceId:currentWorkspaceId,boxId:id,paths});return;}
  void run(id,async()=>{await attach(paths?await native.inspect(storageProfile(),content.id,paths):await native.select(storageProfile(),content.id));});
 };
 const pick=(id:string)=>requestAttachment(id);
 const drop=(id:string,files:File[])=>{const native=window.mainsAgentsDesktop?.files;if(!native){requestAttachment(id);return;}const paths=files.map(file=>native.pathForFile(file));if(!paths.length||paths.length>20||paths.some(path=>!path)){setError(pt?'Arraste até 20 vídeos do Explorador de Arquivos.':'Drop up to 20 videos from File Explorer.');return;}requestAttachment(id,paths);};
 const associateRecording=()=>{if(!attachment||!flow)return;const request=attachment;void run(request.boxId,async()=>{
  const target=attachmentChoice==='new'?await editorial.createRecordingContent(currentWorkspaceId,recordingTitle):contents.find(item=>item.id===attachmentChoice);
  if(!target)throw Error(pt?'Escolha um conteúdo válido.':'Choose a valid content.');
  if(attachmentRef.current?.token!==request.token||live.current.flowId!==request.flowId||live.current.workspaceId!==request.workspaceId)return;
  update(current=>bindFlowContent(current,target.id,chat.sessions));setAttachment({...request,targetId:target.id});
 });};
 useEffect(()=>{
  if(!attachment)return;
  if(attachment.flowId!==flow?.id||attachment.workspaceId!==currentWorkspaceId){setAttachment(undefined);return;}
  if(!attachment.targetId||busy||content?.id!==attachment.targetId)return;
  const request=attachment;setAttachment(undefined);inspect(request.boxId);
  void run(request.boxId,async()=>{const native=window.mainsAgentsDesktop?.files;if(!native)throw Error(pt?'Arquivos locais indisponíveis neste ambiente.':'Local files are unavailable here.');await attach(request.paths?await native.inspect(storageProfile(),content.id,request.paths):await native.select(storageProfile(),content.id));});
 },[attachment,flow?.id,currentWorkspaceId,content?.id,busy]);
 const summary=(box:FlowBox)=>{
  const agent=available.find(item=>item.id===box.agentId),session=chat.sessions.find(item=>item.id===box.sessionId&&item.agentId===box.agentId&&item.contentId===content?.id),runState=chat.getRunState(session?.id);
  let detail=content?.title??(pt?'Comece uma conversa para esta produção.':'Start a conversation for this production.'),status=pt?'Pronto para conversar':'Ready to chat',tone:'quiet'|'active'|'attention'|'done'='quiet';
  if(activeProduction){const stage=activeProduction.stage,internal=box.kind==='content-agent'?['writing','notion']:box.kind==='video-agent'?['planning-edit','editing']:box.kind==='publishing-agent'?['preparing-package','generating-cover','package-review','schedule','scheduling','complete']:['recording'];const stageStatus=box.kind==='content-agent'&&!internal.includes(stage)?(pt?'Conteúdo estruturado':'Content structured'):box.kind==='video-input'&&videos.length?(pt?'Gravação recebida':'Recording received'):internal.includes(stage)?productionStageLabel(stage,pt):(pt?'Etapa aguardando':'Stage waiting');return {detail:activeProduction.topic.title,status:stageStatus,tone:stage==='blocked'||stage==='paused'?'attention' as const:['writing','notion','planning-edit','editing','preparing-package','generating-cover','scheduling'].includes(stage)&&internal.includes(stage)?'active' as const:stage==='complete'?'done' as const:'quiet' as const};}
  if(box.kind==='video-input'){detail=videos.length?`${videos.length} ${pt?'vídeo(s)':'video(s)'} · ${videos[0].name}`:(pt?'Solte seu vídeo aqui':'Drop your video here');status=videos.length?(pt?'Gravação recebida':'Recording received'):(pt?'Aguardando gravação':'Waiting for recording');tone=videos.length?'done':'quiet';if(videos.some(item=>item.status!=='available')){status=pt?'Verificar arquivos':'Check files';tone='attention'}}
  else if(!agent){detail=pt?'Escolha um agente deste workspace.':'Choose an agent in this workspace.';status=pt?'Escolher agente':'Choose agent';tone='attention'}
  else if(box.kind==='content-agent'){const notion=editorial.jobs.find(job=>job.contentId===content?.id&&job.result);if(notion)detail=pt?'Card do Notion confirmado':'Notion card confirmed';if(content?.status==='script-review'){status=pt?'Aguardando aprovação':'Waiting for approval';tone='attention'}else if(content?.approvedScriptArtifactId){status=pt?'Roteiro aprovado':'Script approved';tone='done'}}
  else if(box.kind==='video-agent'){const outputs=videos.filter(item=>item.role==='output'),active=editorial.workJobs.some(job=>job.contentId===content?.id&&job.agent.id===agent.id&&['running','queued'].includes(job.status))||editorial.mediaJobs.some(job=>job.contentId===content?.id&&['running','queued'].includes(job.status));detail=outputs.length?`${outputs.length} ${pt?'arquivo(s) de resultado':'output file(s)'}`:(pt?'O especialista recebe o vídeo e seu briefing.':'The specialist receives video and briefing.');status=active?(pt?'Trabalhando':'Working'):outputs.length?(pt?'Resultado para revisão':'Output for review'):(pt?'Aguardando vídeo':'Waiting for video');tone=active?'active':outputs.length?'attention':'quiet';const handoff=chat.handoffs.find(item=>item.targetSessionId===box.sessionId);if(!active&&!outputs.length&&handoff?.status==='completed'){detail=pt?'Abra a conversa para revisar o retorno do especialista.':'Open the chat to review the specialist response.';status=pt?'Resposta recebida':'Response received';tone='attention'}else if(!active&&!outputs.length&&videos.some(item=>item.role==='source')){status=pt?'Preparar briefing':'Prepare briefing'}}
  else {const deliveries=(editorial.state.publications??[]).filter(item=>item.contentId===content?.id&&item.workspaceId===currentWorkspaceId),confirmed=deliveries.filter(item=>['scheduled','published'].includes(item.status)&&item.receipt?.version===item.version).length;detail=deliveries.length?`${deliveries.length} ${pt?'entrega(s) por rede':'channel deliverables'} · ${confirmed} ${pt?'confirmada(s)':'confirmed'}`:(pt?'Use o vídeo revisado para preparar capas e legendas.':'Use the reviewed video for covers and captions.');status=confirmed?(pt?'Agendamento confirmado':'Schedule confirmed'):(pt?'Preparar pacote':'Prepare package');tone=confirmed?'done':'quiet'}
  if(['thinking','searching','using-tool'].includes(runState)&&box.kind!=='video-input'){status=pt?'Trabalhando':'Working';tone='active'}if(runState==='error'&&box.kind!=='video-input'){status=pt?'Precisa de atenção':'Needs attention';tone='attention'}if(busy===box.id){status=pt?'Verificando':'Verifying';tone='active'}
  return {detail,status,tone};
 };
 const graph:ProductionNode[]=flow?.nodes.map(box=>({id:box.id,type:'production',position:box.position,selected:box.id===selectedId,measured:measured[box.id],style:{width:300},data:{box,agent:available.find(agent=>agent.id===box.agentId),pt,...summary(box),busy:busy===box.id,open:()=>box.kind==='video-input'?inspect(box.id):openChat(box),configure:()=>inspect(box.id),pick:()=>pick(box.id),drop:(files:File[])=>drop(box.id,files)}}))??[];
 const selected=flow?.nodes.find(node=>node.id===selectedId),nextEditor=selected&&flow?.edges.filter(edge=>edge.source===selected.id&&edge.kind==='sequence').map(edge=>flow.nodes.find(node=>node.id===edge.target)).find(node=>node?.kind==='video-agent');
 const sourceBox=flow&&selected?upstreamFlowBox(flow,selected.id,'content-agent'):undefined,source=available.find(agent=>agent.id===sourceBox?.agentId),editor=available.find(agent=>agent.id===nextEditor?.agentId);
 const send=()=>{if(!selected)return;void run(selected.id,async()=>{if(!content||!source||!editor||!brief.trim())throw Error(pt?'Confira conteúdo, agentes e briefing.':'Check content, agents and briefing.');const native=window.mainsAgentsDesktop?.files;if(!native)throw Error(pt?'Use o app desktop.':'Use the desktop app.');const checks=await native.verify(storageProfile(),content.id);guard();const originals=videos.filter(asset=>asset.role==='source');if(!originals.length||originals.some(asset=>!checks.some(check=>check.id===asset.id&&check.versionId===asset.currentVersionId&&check.inspection.status==='available'&&check.inspection.sha256===asset.versions.find(version=>version.id===asset.currentVersionId)?.sha256)))throw Error(pt?'Um vídeo mudou ou está ausente. Verifique os arquivos.':'A video changed or is missing. Verify files.');await editorial.verifyFiles(checks);guard();const origin=chat.sessions.find(session=>session.id===sourceBox?.sessionId&&session.agentId===source.id&&session.contentId===content.id)??chat.createSession(source.id,flow!.name,source.providerId??'codex',source.modelId,{contentId:content.id,topicId:content.topicId});
const script=editorial.state.artifacts.find(item=>item.id===content.approvedScriptArtifactId&&item.contentId===content.id&&item.type==='script');
if(!script)throw Error(pt?'Confira o roteiro aprovado antes de enviar.':'Check the approved script before sending.');
update(current=>({...current,nodes:current.nodes.map(node=>node.id===sourceBox!.id?{...node,sessionId:origin.id}:node)}));
const handoff=await chat.delegateToAgent(source,origin.id,{targetAgentId:editor.id,title:content.title.slice(0,120),instructions:brief.trim()+'\n\n'+(pt?'Roteiro aprovado: ':'Approved script: ')+JSON.stringify(script.data),files:originals.map(asset=>asset.versions.find(version=>version.id===asset.currentVersionId)!.path),sessionMode:'continue'});
update(current=>({...current,nodes:current.nodes.map(node=>node.id===sourceBox!.id?{...node,sessionId:origin.id}:node.id===nextEditor!.id?{...node,sessionId:handoff.targetSessionId}:node)}));setSendConfirm(false);setNotice(pt?'Briefing enviado. Acompanhe o especialista na conversa ou no Estúdio.':'Briefing sent. Follow the specialist in chat or Studio.');})};
 const openStudio=()=>{if(content)window.dispatchEvent(new CustomEvent('mainsagents:open-content',{detail:{contentId:content.id,topicId:content.topicId}}));else onOpenStudio?.()};
 const onConnect=(connection:Connection)=>{if(connection.source&&connection.target)update(current=>linkFlow(current,connection.source!,connection.target!))};
 const onNodesChange=(changes:NodeChange<ProductionNode>[])=>{
  if(changes.some(change=>change.type==='dimensions'))setMeasured(current=>{let changed=false;const next={...current};for(const change of changes)if(change.type==='dimensions'&&change.dimensions&&change.dimensions.width>0&&change.dimensions.height>0){const old=current[change.id];if(old?.width!==change.dimensions.width||old.height!==change.dimensions.height){next[change.id]=change.dimensions;changed=true;}}return changed?next:current;});
  if(changes.some(change=>change.type==='position'&&change.position))update(current=>({...current,nodes:current.nodes.map(node=>{const change=changes.find(item=>item.type==='position'&&item.id===node.id);return change?.type==='position'&&change.position?{...node,position:change.position}:node})}));
 };
 const saveName=()=>{if(!name.trim())return;if(dialog==='create')add(createProductionFlow(currentWorkspaceId,name,agents,pt));else update(current=>({...current,name:name.trim().slice(0,120)}));setDialog(null)};
 return <section className="production-flow-page page full" data-od-id="production-flows">
  <header className="production-flow-header"><div className="flow-view-tabs"><button aria-pressed={mode==='production'} onClick={()=>setMode('production')}>{pt?'Meus fluxos':'My flows'}</button><button aria-pressed={mode==='relations'} onClick={()=>setMode('relations')}>{pt?'Relações do Canvas':'Canvas relationships'}</button></div>{mode==='production'&&<div className="flow-picker"><Icon name="link"/><SelectMenu ariaLabel={pt?'Fluxo atual':'Current flow'} value={flow?.id??''} options={flows.length?flows.map(item=>({value:item.id,label:item.name})):[{value:'',label:pt?'Nenhum fluxo':'No flows'}]} onChange={id=>setSaved(current=>({...current,activeByWorkspace:{...current.activeByWorkspace,[currentWorkspaceId]:id}}))}/>{flow&&<><button className="icon-button" aria-label={pt?'Renomear fluxo':'Rename flow'} onClick={()=>{setName(flow.name);setDialog('rename')}}><Icon name="edit"/></button><button className="icon-button" aria-label={pt?'Duplicar fluxo':'Duplicate flow'} onClick={()=>add(duplicateProductionFlow(flow,pt))}><Icon name="copy"/></button><button className="icon-button" aria-label={pt?'Remover fluxo':'Remove flow'} onClick={()=>setDialog('delete')}><Icon name="trash"/></button></>}</div>}{mode==='production'&&<div className="production-flow-actions"><button className="soft-button" onClick={()=>{setName(pt?'Novo fluxo':'New flow');setDialog('create')}}><Icon name="plus"/>{pt?'Novo fluxo':'New flow'}</button></div>}</header>
  {mode==='relations'?<CanvasRelations onOpenCanvas={onOpenCanvas} onSelectAgent={onSelectAgent}/>:<>
   <div className="flow-context-bar"><div className="production-summary"><span className="flow-stage-trail" aria-label={activeProduction?productionStageLabel(activeProduction.stage,pt):(pt?'Etapas da produção':'Production stages')}>{(pt?['Aprovar ideia','Roteiro e Notion','Vídeo','Revisão','Agendamento']:['Approve idea','Script and Notion','Video','Review','Schedule']).map((label,index)=><span className={stageIndex===index?'current':stageIndex>index?'done':''} key={label}>{label}</span>)}</span><button className="soft-button" onClick={()=>setProductionOpen(true)}>{activeProduction?(pt?'Acompanhar produção':'Follow production'):(pt?'Iniciar produção':'Start production')}</button></div>
   <div className="production-flow-context"><label>{pt?'Conteúdo':'Content'}<SelectMenu ariaLabel={pt?'Conteúdo do fluxo':'Flow content'} value={content?.id??''} disabled={!flow||!!busy} onChange={id=>update(current=>bindFlowContent(current,id||undefined,chat.sessions))} options={[{value:'',label:pt?'Escolher conteúdo do Estúdio':'Choose Studio content'},...contents.map(item=>({value:item.id,label:item.title}))]}/></label>{flow&&<button className="soft-button" onClick={()=>setDialog('add')}><Icon name="plus"/>{pt?'Adicionar caixa':'Add box'}</button>}</div></div>
   <div className="production-flow-body">{flow?<ReactFlow<ProductionNode> key={`${currentWorkspaceId}:${flow.id}`} nodes={graph} edges={flow.edges.map(edge=>({...edge,type:'smoothstep',label:edge.kind==='context'?(pt?'Contexto':'Context'):(pt?'Continuar':'Continue'),markerEnd:{type:MarkerType.ArrowClosed,width:16,height:16},style:{stroke:'var(--accent)',strokeWidth:1.3,strokeDasharray:edge.kind==='context'?'5 5':undefined},labelStyle:{fill:'var(--muted)',fontSize:10},labelBgStyle:{fill:'var(--bg)'}}))} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onConnect={onConnect} isValidConnection={connection=>!!connection.source&&!!connection.target&&canConnectFlow(flow,connection.source,connection.target)} onNodeClick={(_,node)=>inspect(node.id)} onPaneClick={()=>setSelectedId(undefined)} fitView={window.innerWidth>=760} defaultViewport={window.innerWidth<760?{x:24-(flow.nodes[0]?.position.x??0)*.9,y:32-(flow.nodes[0]?.position.y??0)*.9,zoom:.9}:undefined} fitViewOptions={{padding:.2,maxZoom:.9}} minZoom={.2} maxZoom={1.5} deleteKeyCode={null} proOptions={{hideAttribution:true}}><Background gap={24} size={.7} color="var(--border)"/><Controls showInteractive={false}/></ReactFlow>:<div className="production-flow-empty"><Icon name="link"/><h2>{pt?'Um fluxo para sua produção':'A flow for your production'}</h2><p>{pt?'Crie um fluxo e organize suas conversas e materiais.':'Create a flow and organize conversations and materials.'}</p><button className="primary-button" onClick={()=>{setName(pt?'Fluxo de criação de conteúdo':'Content creation flow');setDialog('create')}}>{pt?'Criar fluxo':'Create flow'}</button></div>}
    {selected&&flow&&<aside className="production-flow-detail" key={`${flow.id}:${selected.id}`} aria-label={pt?'Configuração da caixa':'Box settings'}><div className="flow-detail-heading"><Icon name={flowIcons[selected.kind]}/><h2>{selected.title}</h2><button className="icon-button" aria-label={pt?'Fechar configuração':'Close settings'} onClick={()=>setSelectedId(undefined)}><Icon name="close"/></button></div><p>{flowDescriptions(pt)[selected.kind]}</p><label>{pt?'Nome da caixa':'Box name'}<input value={selected.title} maxLength={120} onChange={event=>{if(event.target.value.trim())patch(selected.id,{title:event.target.value})}}/></label>
     {selected.kind!=='video-input'&&<><label>{pt?'Agente':'Agent'}<SelectMenu ariaLabel={pt?'Agente da caixa':'Box agent'} value={available.some(agent=>agent.id===selected.agentId)?selected.agentId??'':''} options={[{value:'',label:pt?'Selecione um agente':'Choose an agent'},...available.map(agent=>({value:agent.id,label:agent.name}))]} onChange={agentId=>patch(selected.id,{agentId:agentId||undefined,sessionId:undefined})}/></label><button className="primary-button" disabled={!available.some(agent=>agent.id===selected.agentId)} onClick={()=>openChat(selected)}><Icon name="message"/>{pt?'Abrir conversa deste fluxo':'Open this flow’s chat'}</button><small>{pt?'A conversa continua na sessão salva, com as instruções e skills do agente.':'The chat continues in its saved session, with the agent’s instructions and skills.'}</small></>}
     {selected.kind==='video-input'&&<><button className="primary-button" disabled={!!busy} onClick={()=>pick(selected.id)}>{pt?'Adicionar vídeo do PC':'Add local video'}</button>{!content&&<p>{pt?'Escolha o conteúdo no topo para associar os vídeos à mesma pauta.':'Choose the content above to link videos to the same topic.'}</p>}{content&&<ContentAssetLibrary content={content}/>}<button className="soft-button" disabled={!!busy||!content?.approvedScriptArtifactId||!editor||!source||!source.tools.includes('subagents')||!videos.some(item=>item.role==='source'&&item.status==='available')} onClick={()=>{setSendConfirm(true);setBrief(pt?'Edite os vídeos originais seguindo o roteiro aprovado. Entregue um arquivo real e informe alterações ou impedimentos. Aguarde minha revisão.':'Edit original videos following the approved script. Deliver a real file and report changes or blockers. Await my review.')}}>{pt?'Preparar envio ao editor':'Prepare editor briefing'}</button><small>{pt?'Conecte ao Editor de Vídeo, escolha os agentes e aprove o roteiro. O agente de origem precisa ter colaboração habilitada.':'Connect to the Video Editor, choose agents and approve the script. The source agent needs collaboration enabled.'}</small>{sendConfirm&&<div className="flow-send-review"><strong>{editor?.name}</strong><label>Briefing<textarea value={brief} maxLength={32000} onChange={event=>setBrief(event.target.value)}/></label><p>{videos.filter(item=>item.role==='source').map(item=>item.name).join(', ')}</p><button className="primary-button" disabled={!!busy||!brief.trim()} onClick={send}>{pt?'Enviar vídeos e briefing':'Send videos and briefing'}</button></div>}</>}
     {selected.kind==='video-agent'&&content&&<><ContentMediaEditor content={content}/><button className="soft-button" onClick={openStudio}>{pt?'Revisar resultado no Estúdio':'Review result in Studio'}</button></>}
     {selected.kind==='publishing-agent'&&content&&<ContentPublications content={content}/>}
     {selected.kind==='content-agent'&&content&&editorial.jobs.filter(job=>job.contentId===content.id&&job.result).slice(-1).map(job=><a className="soft-button" key={job.id} href={job.result!.url} target="_blank" rel="noopener noreferrer"><Icon name="external"/>{pt?'Abrir card no Notion':'Open Notion card'}</a>)}
     <button className="soft-button" onClick={openStudio}><Icon name="script"/>{content?(pt?'Abrir conteúdo no Estúdio':'Open content in Studio'):(pt?'Criar conteúdo no Estúdio':'Create content in Studio')}</button>
     <button className="text-link" onClick={()=>setDialog('delete-box')}><Icon name="trash"/>{pt?'Remover caixa':'Remove box'}</button>
     <div className="flow-links"><h3>{pt?'Conexões':'Connections'}</h3>{flow.edges.filter(edge=>edge.source===selected.id).map(edge=><div key={edge.id}><span>{flow.nodes.find(node=>node.id===edge.target)?.title}</span><SelectMenu ariaLabel={pt?'Tipo de conexão':'Connection type'} value={edge.kind} options={[{value:'sequence',label:pt?'Próxima etapa':'Next stage'},{value:'context',label:pt?'Contexto':'Context'}]} onChange={kind=>{if(!canConnectFlow(flow,edge.source,edge.target,kind as 'sequence'|'context',edge.id)){setError(pt?'Esta ligação criaria um ciclo.':'This would create a cycle.');return;}update(current=>({...current,edges:current.edges.map(item=>item.id===edge.id?{...item,kind:kind as 'sequence'|'context'}:item)}))}}/><button className="icon-button" aria-label={pt?'Remover conexão':'Remove connection'} onClick={()=>update(current=>({...current,edges:current.edges.filter(item=>item.id!==edge.id)}))}><Icon name="close"/></button></div>)}<small>{pt?'Conecte as caixas arrastando seus pontos laterais.':'Connect boxes by dragging their side handles.'}</small></div>
    </aside>}
   </div><footer className="production-flow-footer"><span>{flow?.nodes.length??0} {pt?'caixas':'boxes'} · {flow?.edges.length??0} {pt?'conexões':'connections'}</span><span>{pt?'As etapas internas continuam na conversa de cada agente.':'Internal stages stay in each agent’s conversation.'}</span></footer>
   {(error||notice)&&<div className={`flow-notice ${error?'error':''}`} role={error?'alert':'status'}>{error||notice}<button className="icon-button" aria-label={pt?'Dispensar aviso':'Dismiss notice'} onClick={()=>{setError('');setNotice('')}}><Icon name="close"/></button></div>}
  </>}
  {productionOpen&&<ProductionDialog workspaceId={currentWorkspaceId} flowId={flow?.id} sessionId={activeProduction?.sourceSession.id??flow?.nodes.find(n=>n.kind==='content-agent')?.sessionId} onClose={()=>setProductionOpen(false)} onSelectAgent={onSelectAgent}/>}
  {attachment&&!attachment.targetId&&<FlowDialog title={pt?'Associar gravação ao fluxo':'Link recording to this flow'} onClose={()=>setAttachment(undefined)}><div className="flow-name-form">
   <p>{pt?'Escolha o conteúdo deste vídeo ou cadastre um aqui. Seus arquivos ficam no PC; este vínculo não cria cards no Notion nem aprova roteiro ou edição.':'Choose this video’s content or create one here. Files stay on your PC; this link does not create Notion cards or approve scripts or editing.'}</p>
   <SelectMenu ariaLabel={pt?'Conteúdo da gravação':'Recording content'} value={attachmentChoice} onChange={setAttachmentChoice} disabled={!!busy} options={[{value:'new',label:pt?'Criar conteúdo para esta gravação':'Create content for this recording'},...contents.map(item=>({value:item.id,label:item.title}))]}/>
   {attachmentChoice==='new'&&<label>{pt?'Título do conteúdo':'Content title'}<input value={recordingTitle} maxLength={120} disabled={!!busy} onChange={event=>setRecordingTitle(event.target.value)}/></label>}
   {error&&<p role="alert">{error}</p>}
   <button className="primary-button" disabled={!!busy||!editorial.ready||(attachmentChoice==='new'&&!recordingTitle.trim())} onClick={associateRecording}>{pt?(attachment.paths?'Associar e adicionar vídeos':'Continuar e escolher vídeo'):(attachment.paths?'Link and add videos':'Continue and choose video')}</button>
  </div></FlowDialog>}
  {(dialog==='create'||dialog==='rename')&&<FlowDialog title={dialog==='create'?(pt?'Novo fluxo':'New flow'):(pt?'Renomear fluxo':'Rename flow')} onClose={()=>setDialog(null)}><form className="flow-name-form" onSubmit={event=>{event.preventDefault();saveName()}}><label>{pt?'Nome do fluxo':'Flow name'}<input data-autofocus value={name} maxLength={120} onChange={event=>setName(event.target.value)}/></label>{dialog==='create'&&<p>{pt?'Quatro caixas conectadas para começar: conteúdo, gravação, edição e publicação.':'Start with four connected boxes: content, recording, editing and publishing.'}</p>}<button className="primary-button" type="submit" disabled={!name.trim()}>{dialog==='create'?(pt?'Criar fluxo':'Create flow'):(pt?'Salvar nome':'Save name')}</button></form></FlowDialog>}
  {dialog==='add'&&flow&&<FlowDialog title={pt?'Adicionar caixa':'Add box'} onClose={()=>setDialog(null)}><div className="flow-box-choices">{boxKinds.map(kind=><button className="flow-option" key={kind} onClick={()=>{const id=`box-${crypto.randomUUID()}`;update(current=>({...current,nodes:[...current.nodes,{id,kind,title:boxTitle(kind,pt),position:{x:80+current.nodes.length*350,y:140}}]}));setSelectedId(id);setDialog(null)}}><Icon name={flowIcons[kind]}/><div><strong>{boxTitle(kind,pt)}</strong><span>{flowDescriptions(pt)[kind]}</span></div></button>)}</div></FlowDialog>}
  {dialog==='delete'&&flow&&<FlowDialog title={pt?'Remover este fluxo?':'Remove this flow?'} description={pt?'Agentes, conversas, vídeos e conteúdos continuam salvos. Apenas esta organização será removida.':'Agents, chats, videos and content remain saved. Only this layout will be removed.'} onClose={()=>setDialog(null)}><div className="flow-name-form"><button className="soft-button" onClick={()=>setDialog(null)}>{pt?'Manter fluxo':'Keep flow'}</button><button className="primary-button" onClick={()=>{const id=flow.id;setSaved(current=>{const remaining=current.flows.filter(item=>item.id!==id),activeByWorkspace={...current.activeByWorkspace};delete activeByWorkspace[currentWorkspaceId];const next=remaining.find(item=>item.workspaceId===currentWorkspaceId);if(next)activeByWorkspace[currentWorkspaceId]=next.id;return {...current,flows:remaining,activeByWorkspace}});setDialog(null)}}>{pt?'Remover fluxo':'Remove flow'}</button></div></FlowDialog>}
  {dialog==='delete-box'&&selected&&<FlowDialog title={pt?'Remover esta caixa?':'Remove this box?'} description={pt?'Somente a caixa e suas conexões saem deste fluxo. Conversas, arquivos e agentes continuam salvos.':'Only this box and its connections are removed. Chats, files and agents stay saved.'} onClose={()=>setDialog(null)}><div className="flow-name-form"><button className="soft-button" onClick={()=>setDialog(null)}>{pt?'Manter caixa':'Keep box'}</button><button className="primary-button" onClick={()=>{const id=selected.id;update(current=>({...current,nodes:current.nodes.filter(node=>node.id!==id),edges:current.edges.filter(edge=>edge.source!==id&&edge.target!==id)}));setSelectedId(undefined);setDialog(null)}}>{pt?'Remover caixa':'Remove box'}</button></div></FlowDialog>}
 </section>;
}
