import { useState } from 'react';
import { useWorkspaces } from '../app/WorkspaceProvider';
import { useLanguage } from '../app/LanguageProvider';

function Toggle({initial,label}:{initial:boolean;label:string}) { const [on,setOn]=useState(initial);return <button className={`toggle ${on?'on':''}`} aria-label={label} aria-pressed={on} onClick={()=>setOn(!on)}/> }
export function Settings() {
  const {currentWorkspace}=useWorkspaces();
  const {locale,setLocale,t}=useLanguage();
  return <div className="page"><div className="page-head"><div><p className="eyebrow">{t('Workspace')}</p><h1>{t('Settings')}</h1><p>{t('General preferences for {{name}} and its agents.',{name:currentWorkspace.name})}</p></div></div><div className="settings-grid"><nav className="settings-nav"><button className="active">{t('General')}</button><button>{t('Agents')}</button><button>{t('Models')}</button><button>{t('Shortcuts')}</button></nav><section className="settings-panel"><div className="setting-row"><div className="setting-copy"><b>{t('Interface language')}</b><p>{t('Choose the language used throughout MainsAgents.')}</p></div><select className="language-select" value={locale} onChange={(event)=>setLocale(event.target.value as 'en-US'|'pt-BR')} aria-label={t('Language')}><option value="en-US">English (US)</option><option value="pt-BR">Português (Brasil)</option></select></div><div className="setting-row"><div className="setting-copy"><b>{t('Agent activity')}</b><p>{t('Show concise tool activity inside conversations.')}</p></div><Toggle initial label={t('Agent activity')}/></div><div className="setting-row"><div className="setting-copy"><b>{t('Keep canvas context')}</b><p>{t('Attach selected canvas objects when starting a new session.')}</p></div><Toggle initial label={t('Keep canvas context')}/></div><div className="setting-row"><div className="setting-copy"><b>{t('Reduced motion')}</b><p>{t('Minimize interface transitions and canvas feedback.')}</p></div><Toggle initial={false} label={t('Reduced motion')}/></div></section></div></div>;
}
