import { createContext, useContext, useEffect, useMemo, useState, type PropsWithChildren } from 'react';
import { usePersistentState } from '../data/localPersistence';

export type AppLocale = 'en-US' | 'pt-BR';
export type AppAppearance = 'light' | 'dark';

const pt: Record<string, string> = {
  'Reload skills':'Recarregar skills','Refreshing…':'Recarregando…','Could not refresh skills.':'Não foi possível recarregar as skills.',
  'No Markdown skills found in this folder.':'Nenhuma skill em Markdown foi encontrada nesta pasta.',
  'Choose a folder with .md files or SKILL.md skill folders.':'Escolha uma pasta com arquivos .md ou subpastas com SKILL.md.',
  'Could not load this website.':'Não foi possível carregar este site.',
  'Check the address and your connection, then try again.':'Confira o endereço e sua conexão e tente novamente.',
  'Loading website…':'Carregando site…', 'Website unavailable':'Site indisponível',
  'Desktop browser':'Navegador do app', Reload:'Recarregar',
  'For sites that block previews, use the desktop app or open a new window.':'Para sites que bloqueiam prévias, use o app desktop ou abra outra janela.',
  'Content Studio':'Estúdio de conteúdo', 'AI provider':'Provedor de IA', 'Choose who answers and how usage is billed.':'Escolha a IA que responde e como o uso é cobrado.', Provider:'Provedor', 'Close agent editor':'Fechar configuração do agente',
  Appearance:'Aparência', 'Choose a background and interface style.':'Escolha um fundo e o estilo da interface.', Light:'Claro', Dark:'Escuro', 'Light abstract wallpaper':'Fundo abstrato claro', 'Dark abstract wallpaper':'Fundo abstrato escuro',
  'Welcome back':'Bem-vindo de volta', 'Create your account':'Crie sua conta', 'Continue with Google':'Continuar com Google', 'or continue with email':'ou continue com email', 'New to MainsAgents?':'Novo no MainsAgents?', 'Already have an account?':'Já tem uma conta?', 'Use at least 12 characters.':'Use pelo menos 12 caracteres.', 'Please wait…':'Aguarde…', 'Open MainsAgents Desktop to sign in.':'Abra o MainsAgents Desktop para entrar.', 'Account created. Save your recovery code before continuing.':'Conta criada. Guarde o código de recuperação antes de continuar.', 'Google sign-in needs to be configured by the app developer.':'O login do Google precisa ser configurado pelo desenvolvedor do aplicativo.', 'Your work stays on this computer. Google is used only to verify your account.':'Seu trabalho fica neste computador. O Google é usado apenas para confirmar sua conta.', 'This code is shown only once and can restore access to your account.':'Este código é exibido uma única vez e pode recuperar o acesso à sua conta.',
  'Optional local account. The app works without signing in, and data is never synced to another device.':'Conta local opcional. O app funciona sem login, e os dados nunca são sincronizados com outro dispositivo.', 'Use an optional local account to keep a separate profile on this computer.':'Use uma conta local opcional para manter um perfil separado neste computador.',
  'Your workspace, tied to your account.':'Seu workspace, vinculado à sua conta.', 'Sign in to use MainsAgents. Your agents, sessions and history stay on this computer and are never synced to other devices.':'Entre para usar o MainsAgents. Seus agentes, sessões e histórico ficam neste computador e nunca são sincronizados com outros dispositivos.', 'Account service':'Serviço de contas', Email:'Email', Password:'Senha', 'Continue to MainsAgents':'Continuar para o MainsAgents', 'Create account':'Criar conta', 'Save this one-time recovery code somewhere safe:':'Guarde este código de recuperação de uso único em um local seguro:',
  'The account is stored on this computer. Work history never leaves this device.':'A conta fica salva neste computador. O histórico nunca sai deste dispositivo.',
  'Profile image':'Imagem de perfil','Add a photo or illustrated icon to recognize this agent.':'Adicione uma foto ou ilustração para identificar este agente.','Choose image':'Escolher imagem','Change image':'Trocar imagem','Remove':'Remover','Choose an image file.':'Escolha um arquivo de imagem.','Choose an image smaller than 10 MB.':'Escolha uma imagem menor que 10 MB.','Could not read this image.':'Não foi possível abrir esta imagem.','Model':'Modelo','Loading models…':'Carregando modelos…','Models unavailable':'Modelos indisponíveis','Open chat in center':'Abrir chat em tela cheia','Dock chat to side':'Fixar chat à esquerda','Close chat':'Fechar chat','Full view':'Tela cheia','Dock':'Encaixar',
  Home:'Início', Board:'Quadro', Canvas:'Canvas', Flow:'Fluxo', Agents:'Agentes', Sessions:'Sessões', Messages:'Mensagens', Settings:'Configurações', Workspace:'Workspace', Search:'Buscar', New:'Novo',
  'Drag a block or select one to add':'Arraste um bloco para o Canvas ou clique para adicionar','Drag':'Arraste','Add a chat':'Adicionar chat','Add a terminal':'Adicionar terminal','Terminal':'Terminal','Browser':'Navegador','Run a local command':'Executar comando neste computador','Type a command…':'Digite um comando…','Run':'Executar','Stop':'Parar','Starting…':'Iniciando…','Commands run on this PC in this workspace folder.':'Os comandos são executados neste computador, na pasta deste workspace.','Finished · exit {{code}}':'Concluído · saída {{code}}','Exited with code {{code}}':'Finalizou com o código {{code}}','Command cancelled':'Comando cancelado','Terminal run is unavailable.':'Esta execução do terminal não está mais disponível.','Could not read terminal output.':'Não foi possível ler a saída do terminal.','Could not start the command.':'Não foi possível iniciar o comando.','Note text':'Texto da nota','Write a note…':'Escreva uma nota…','Browser address':'Endereço do navegador','Enter a website address':'Digite o endereço de um site','Go':'Abrir','Canvas browser':'Navegador do Canvas','Some websites block embedded previews.':'Alguns sites bloqueiam a visualização incorporada.','Open website in a new window':'Abrir site em outra janela','Enter an address to open it here.':'Digite um endereço para abrir o site aqui.','Canvas chat':'Chat do Canvas','Message':'Mensagem','Send message':'Enviar mensagem','Message {{name}}…':'Mensagem para {{name}}…','Connected objects will be included with your message.':'Os objetos conectados serão incluídos na sua mensagem.','Start a conversation or connect objects to provide context.':'Inicie uma conversa ou conecte objetos para dar contexto.','Create an agent in this workspace to start a Canvas chat.':'Crie um agente neste workspace para iniciar um chat no Canvas.','Choose an agent to give this chat its own conversation.':'Escolha um agente para criar uma conversa independente neste chat.','Connected objects as context':'Objetos conectados como contexto','{{count}} connected objects as context':'{{count}} objetos conectados como contexto','Used {{count}} connected objects':'{{count}} objetos conectados nesta mensagem','Thinking…':'Pensando…','Searching…':'Pesquisando…','Using a tool…':'Usando uma ferramenta…',
  General:'Geral', Models:'Modelos', Shortcuts:'Atalhos', Language:'Idioma', 'Interface language':'Idioma da interface', 'Choose the language used throughout MainsAgents.':'Escolha o idioma usado em todo o MainsAgents.',
  'General preferences for {{name}} and its agents.':'Preferências gerais para {{name}} e seus agentes.', 'Agent activity':'Atividade dos agentes', 'Show concise tool activity inside conversations.':'Mostrar atividades de ferramentas de forma discreta nas conversas.',
  'Keep canvas context':'Manter contexto do Canvas', 'Attach selected canvas objects when starting a new session.':'Anexar objetos selecionados do Canvas ao iniciar uma sessão.', 'Reduced motion':'Movimento reduzido', 'Minimize interface transitions and canvas feedback.':'Reduzir transições da interface e feedback do Canvas.',
  'Your team':'Sua equipe', 'Specialists with clear roles, tools, and working context.':'Especialistas com funções, ferramentas e contexto de trabalho claros.', 'Create agent':'Criar agente', 'Create a specialist for your workflow':'Crie um especialista para seu fluxo de trabalho','Give an agent a clear role, add its skills, and start a conversation when it is ready.':'Defina a função, adicione skills e comece uma conversa quando o agente estiver pronto.','Create your first agent':'Criar meu primeiro agente',
  'Agent configuration':'Configuração do agente', 'New specialist':'Novo especialista', Identity:'Identidade', 'How this agent appears across the workspace.':'Como este agente aparece no workspace.', Name:'Nome', Role:'Função', Description:'Descrição', Behavior:'Comportamento', Instructions:'Instruções',
  'Set the permanent context this agent should follow.':'Defina o contexto permanente que este agente deve seguir.', Tools:'Ferramentas', 'Choose what this agent can access in the prototype.':'Escolha o que este agente pode acessar.', Skills:'Skills', 'Install a skill or point this agent to a folder containing SKILL.md files.':'Instale uma skill ou indique uma pasta com arquivos SKILL.md.',
  'Skills folder':'Pasta de skills', 'No folder selected':'Nenhuma pasta selecionada', 'Choose folder':'Escolher pasta', 'Install from GitHub':'Instalar do GitHub', 'Install skill':'Instalar skill', 'Installing…':'Instalando…', 'Install with npx':'Instalar com npx','Skill install command':'Comando para instalar skill','Remove skill command':'Remover comando da skill','Add another skill':'Adicionar outra skill','Add & install':'Adicionar e instalar','Enter an npx skills add command.':'Informe um comando npx skills add.','Install skills for this agent using an npx command, or point it to an existing skills folder.':'Instale skills para este agente com um comando npx ou selecione uma pasta que já contenha skills.', Cancel:'Cancelar', 'Save changes':'Salvar alterações',
  'Name and role are required.':'Nome e função são obrigatórios.', 'Delete agent':'Excluir agente', 'This permanently removes the local agent and its configuration.':'Isso remove permanentemente o agente local e sua configuração.', 'Confirm delete':'Confirmar exclusão', Delete:'Excluir',
  'Agent settings':'Configurações do agente', 'Define the role, tools, skills, and default working behavior.':'Defina a função, ferramentas, skills e comportamento padrão.', 'Back to agents':'Voltar para agentes', 'Edit agent':'Editar agente',
  'Mission Control':'Central de controle', 'See what is moving, where attention is needed, and what your agents delivered.':'Veja o que está em andamento, o que precisa de atenção e o que seus agentes entregaram.', 'agents working':'agentes trabalhando', 'needs your attention':'precisa da sua atenção', 'tasks completed today':'tarefas concluídas hoje',
  'Working now':'Em andamento', 'active tasks':'tarefas ativas', 'Needs your attention':'Precisa da sua atenção', Review:'Revisar', 'Recently completed':'Concluídas recentemente', 'delivered today':'entregues hoje', 'Make your first specialist':'Crie seu primeiro especialista','Create an agent for a real part of your content workflow, then give it a first assignment.':'Crie um agente para uma etapa real do seu fluxo de conteúdo e passe a primeira tarefa.','Create an agent to get your workspace moving.':'Crie um agente para começar a movimentar seu workspace.','Nothing is running right now. Give an agent its next task.':'Nada está em andamento. Passe a próxima tarefa para um agente.','Completed work will appear here.':'Os trabalhos concluídos aparecerão aqui.','A visual space for ideas and research':'Um espaço visual para ideias e pesquisas','Add a note, collect research, or turn an agent response into a Canvas object.':'Adicione uma nota, reúna pesquisas ou transforme uma resposta do agente em um objeto do Canvas.','Add a note':'Adicionar nota','Add research':'Adicionar pesquisa','Your task board is ready':'Seu quadro está pronto','Add a task and assign an agent. Move it across columns as the work progresses.':'Adicione uma tarefa e atribua um agente. Mova-a pelas colunas conforme o trabalho avança.','Add your first task':'Adicionar primeira tarefa',
  'Track work without losing the agent, sources, or output behind it.':'Acompanhe o trabalho sem perder o agente, as fontes ou o resultado.', Filter:'Filtrar', Research:'Pesquisa', Running:'Em andamento', Done:'Concluído',
  'Agent history':'Histórico dos agentes', 'Each conversation keeps its own messages, agent, and working context.':'Cada conversa mantém suas próprias mensagens, agente e contexto.', 'New session':'Nova sessão', 'Deleted agent':'Agente excluído', 'Independent session':'Sessão independente',
  Workspaces:'Workspaces', Rename:'Renomear', Save:'Salvar', 'New workspace':'Novo workspace', 'Codex connected':'Codex conectado',
  Chat:'Chat', Context:'Contexto', Idle:'Ocioso', Thinking:'Pensando', Searching:'Pesquisando', 'Tool usage':'Usando ferramenta', Finished:'Concluído', Error:'Erro', You:'Você', 'All sessions':'Todas as sessões', Copy:'Copiar', 'Add to Canvas':'Adicionar ao Canvas', 'Added to Canvas':'Adicionado ao Canvas', Active:'Ativa', Confirm:'Confirmar',
  'Agent context':'Contexto do agente', 'Local agent configuration':'Configuração local do agente', 'Canvas context will include selected objects when Codex is connected.':'O contexto do Canvas incluirá os objetos selecionados quando o Codex estiver conectado.', 'Cancel execution':'Cancelar execução', Send:'Enviar', Web:'Web',
  'Ready':'Pronto', 'Needs review':'Precisa de revisão', Completed:'Concluído', 'tools':'ferramentas', 'items':'itens', 'item':'item',
  Note:'Nota', Image:'Imagem', Add:'Adicionar', More:'Mais', object:'objeto', objects:'objetos', 'Canvas tools':'Ferramentas do Canvas', 'Content idea':'Ideia de conteúdo', Hook:'Hook', Script:'Roteiro', 'Ask Agent':'Perguntar ao agente', 'Send to Agent':'Enviar ao agente', Duplicate:'Duplicar', Connect:'Conectar', Group:'Agrupar', selected:'selecionados',
  'Exit {{code}}':'Saída {{code}}', 'Clear terminal':'Limpar terminal', 'Copy output':'Copiar saída', 'Could not copy output.':'Não foi possível copiar a saída.', 'Enter a command to get started.':'Digite um comando para começar.', 'Command is running…':'Comando em execução…', 'Could not stop the command.':'Não foi possível interromper o comando.', 'Each command starts a new shell in the workspace folder.':'Cada comando inicia um novo shell na pasta do workspace.',
  'Command palette':'Paleta de comandos', 'No results':'Nenhum resultado', 'Try another name or command.':'Tente outro nome ou comando.', Navigate:'Navegar', Open:'Abrir', Close:'Fechar', Actions:'Ações', Tasks:'Tarefas',
  'New Agent':'Novo agente', 'New Task':'Nova tarefa', 'New Session':'Nova sessão', 'Add Note':'Adicionar nota', 'Add Image':'Adicionar imagem', 'Open Canvas':'Abrir Canvas',  'Open Agent':'Abrir agente', 'Switch Workspace':'Trocar workspace',
  'Folder selection is available in the desktop app.':'A seleção de pasta está disponível no aplicativo desktop.', 'No SKILL.md files found in this folder.':'Nenhum arquivo SKILL.md foi encontrado nesta pasta.', 'Enter a skill repository.':'Informe um repositório de skill.', 'Skill installation is available in the desktop app.':'A instalação de skills está disponível no aplicativo desktop.', 'Could not install this skill.':'Não foi possível instalar esta skill.',
  'Web Search':'Pesquisa na Web', Files:'Arquivos', 'Canvas Context':'Contexto do Canvas', Subagents:'Subagentes', 'Search and read public sources.':'Pesquisar e ler fontes públicas.', 'Read files attached to the workspace.':'Ler arquivos anexados ao workspace.', 'Read selected nodes and create canvas results.':'Ler nodes selecionados e criar resultados no Canvas.', 'Delegate focused work to other agents.':'Delegar trabalhos específicos a outros agentes.',
  'Focus writing mode':'Modo de escrita ampliado', 'Give writing fields more space and improve readability while creating or editing.':'Amplia e destaca os campos de escrita durante a criação ou edição.',
   'Task title':'Título da tarefa', 'What needs to be done?':'O que precisa ser feito?', 'Choose an agent':'Escolha um agente', 'Create task':'Criar tarefa', 'Task created':'Tarefa criada', 'Add a clear description so the agent knows what to do.':'Adicione uma descrição clara para orientar o agente.', 'Zoom writing area':'Ampliar área de escrita',
  'Enter a task title.':'Informe um título para a tarefa.', Status:'Status', 'Add task':'Adicionar tarefa',
  'Text size':'Tamanho do texto', 'Adjust the entire interface for easier reading.':'Ajuste toda a interface para facilitar a leitura.',
  'Minimize zoom and transition effects.':'Reduza os efeitos de zoom e transição.',
  'Your data':'Seus dados', 'Export backup':'Exportar backup', 'Import backup':'Importar backup',
  'Save a local copy of your work or restore it on another computer.':'Salve uma cópia local do seu trabalho ou restaure em outro computador.',
  'Replace local data':'Substituir dados locais', 'Merge with local data':'Mesclar com dados locais',
  'Review the backup before importing. Replacing keeps only the selected backup.':'Confira o backup antes de importar. Substituir mantém apenas os dados do arquivo selecionado.',
  'Backup exported':'Backup exportado', 'Backup imported. Reloading…':'Backup importado. Reiniciando…',
  'Open a MainsAgents backup file.':'Abra um arquivo de backup do MainsAgents.',
  'Codex disconnected':'Codex desconectado', 'Toggle chat panel':'Alternar painel de chat',
  'Copied to clipboard':'Copiado para a área de transferência', 'Could not copy message':'Não foi possível copiar a mensagem',
  'Could not finish this response.':'Não foi possível concluir esta resposta.', 'Check the provider connection and send another message to retry.':'Confira a conexão com a IA e envie outra mensagem para tentar novamente.',
  'Resize sidebar':'Redimensionar barra lateral',
  'Task details':'Detalhes da tarefa', 'Edit task':'Editar tarefa', 'Task updated':'Tarefa atualizada', 'Task deleted':'Tarefa excluída', 'Open agent chat':'Abrir chat do agente', Undo:'Desfazer',
  'Welcome guide':'Guia de boas-vindas', 'Reopen the first-use steps and agent templates.':'Reabra os primeiros passos e os modelos de agentes.', 'Open guide':'Abrir guia',
  'Codex connection':'Conexão com o Codex', 'Connected and ready to chat.':'Conectado e pronto para conversar.', 'Sign in to Codex to send messages.':'Entre no Codex para enviar mensagens.', 'Codex is unavailable. Install the CLI and reconnect.':'O Codex está indisponível. Instale a CLI e reconecte.', 'Checking connection…':'Verificando conexão…', 'Sign in':'Entrar', Reconnect:'Reconectar', 'Check again':'Verificar novamente', 'Complete sign-in in the browser, then check again.':'Conclua o login no navegador e verifique novamente.',
  'Codex CLI connection':'Conexão com a CLI do Codex', 'Claude Code CLI connection':'Conexão com a CLI do Claude Code', 'Connected with Claude Code CLI.':'Conectado pela CLI do Claude Code.', 'Claude Code CLI is installed. Sign in through its own CLI flow.':'A CLI do Claude Code está instalada. Entre pela própria CLI.', 'Claude Code CLI is not installed on this computer.':'A CLI do Claude Code não está instalada neste computador.', 'Claude Code CLI connection needs attention.':'A conexão com a CLI do Claude Code precisa de atenção.', 'Could not check Claude Code CLI.':'Não foi possível verificar a CLI do Claude Code.', 'Copy install command':'Copiar comando de instalação', 'Copy sign-in command':'Copiar comando de login', 'Command copied. Run it in your terminal, then check the connection again.':'Comando copiado. Execute-o no terminal e verifique a conexão novamente.', 'Run this command in PowerShell or your terminal:':'Execute este comando no PowerShell ou no terminal:', 'MainsAgents does not read Claude credentials. Check Anthropic terms before distributing an app that runs Claude Code.':'O MainsAgents não acessa as credenciais do Claude. Consulte os termos da Anthropic antes de distribuir um app que execute Claude Code.',
  'Help and feedback':'Ajuda e feedback', 'Download a diagnostic report without private content or open an issue.':'Baixe um diagnóstico sem conteúdo privado ou abra uma issue.', 'Download diagnostics':'Baixar diagnóstico', 'Send feedback':'Enviar feedback',
  'Default Codex model':'Modelo padrão do Codex', 'Applies to new sessions. Existing sessions keep their model.':'Vale para novas sessões. Sessões existentes mantêm seu modelo.', 'Provider default':'Padrão do provedor', 'Uses your Codex CLI login and plan.':'Usa seu login e plano da CLI do Codex.', 'Uses your Claude Code CLI authentication and provider billing.':'Usa a autenticação da CLI do Claude Code e a cobrança do provedor.',
};

interface LanguageContextValue { locale:AppLocale; setLocale:(locale:AppLocale)=>void; appearance:AppAppearance; setAppearance:(appearance:AppAppearance)=>void; focusMode:boolean; setFocusMode:(enabled:boolean)=>void; textScale:number; setTextScale:(scale:number)=>void; reducedMotion:boolean; setReducedMotion:(enabled:boolean)=>void; t:(text:string,values?:Record<string,string|number>)=>string }
const LanguageContext=createContext<LanguageContextValue|null>(null);

export function LanguageProvider({children}:PropsWithChildren) {
  const [locale,setLocale]=usePersistentState<AppLocale>('language',navigator.language.startsWith('pt')?'pt-BR':'en-US');
  const [appearance,setAppearance]=useState<AppAppearance>(()=>{try{return localStorage.getItem('mainsagents-appearance')==='dark'?'dark':'light'}catch{return 'light'}});
  const [focusMode,setFocusMode]=usePersistentState<boolean>('focus-mode',true);
  const [textScale,setTextScale]=usePersistentState<number>('text-scale',100);
  const [reducedMotion,setReducedMotion]=usePersistentState<boolean>('reduced-motion',false);
  useEffect(()=>{document.documentElement.lang=locale},[locale]);
  useEffect(()=>{document.documentElement.dataset.appearance=appearance;document.documentElement.style.colorScheme=appearance;try{localStorage.setItem('mainsagents-appearance',appearance)}catch{}},[appearance]);
  useEffect(()=>{document.documentElement.style.setProperty('--ui-scale',String(Math.min(2,Math.max(1,textScale/100))))},[textScale]);
  useEffect(()=>{document.documentElement.classList.toggle('reduced-motion',reducedMotion);return()=>document.documentElement.classList.remove('reduced-motion')},[reducedMotion]);
  const value=useMemo<LanguageContextValue>(()=>({locale,setLocale,appearance,setAppearance,focusMode,setFocusMode,textScale,setTextScale,reducedMotion,setReducedMotion,t:(text,values)=>{
    let translated=locale==='pt-BR'?(pt[text]??text):text;
    for(const [key,value] of Object.entries(values??{}))translated=translated.replaceAll(`{{${key}}}`,String(value));
    return translated;
  }}),[appearance,focusMode,locale,reducedMotion,setFocusMode,setLocale,setReducedMotion,setTextScale,textScale]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage():LanguageContextValue { const value=useContext(LanguageContext);if(!value)throw new Error('useLanguage must be used inside LanguageProvider');return value; }
